// Peelr Questions Database - 500 unique questions
// 5 categories × 5 layers × 20 questions each

// Custom layer names for each category
const LAYER_NAMES = {
  friends: {
    1: { title: 'Ice Breakers', desc: 'Light and playful, easy conversations' },
    2: { title: 'Getting Real', desc: 'Moving past surface level' },
    3: { title: 'The Deep End', desc: 'Meaningful stories and experiences' },
    4: { title: 'Raw & Honest', desc: 'Vulnerable truths between friends' },
    5: { title: 'Soul Friends', desc: 'The kind of depth that changes friendships' }
  },
  family: {
    1: { title: 'Family Stories', desc: 'Memories and traditions' },
    2: { title: 'Understanding Roots', desc: 'Where we come from' },
    3: { title: 'Honest Reflections', desc: 'Family dynamics and truth' },
    4: { title: 'Healing Conversations', desc: 'Processing and growing together' },
    5: { title: 'Generational Bonds', desc: 'The deepest family connections' }
  },
  coworkers: {
    1: { title: 'Getting Started', desc: 'Professional icebreakers' },
    2: { title: 'Team Building', desc: 'Beyond work talk' },
    3: { title: 'Work & Life', desc: 'Balancing it all' },
    4: { title: 'Leadership & Growth', desc: 'Career and personal development' },
    5: { title: 'Purpose & Impact', desc: 'Why we do what we do' }
  },
  lovers: {
    1: { title: 'First Glances', desc: 'Playful and flirty' },
    2: { title: 'Opening Up', desc: 'Sharing yourself' },
    3: { title: 'True Colors', desc: 'Showing who you really are' },
    4: { title: 'Vulnerable Hearts', desc: 'Fears, hopes, and dreams' },
    5: { title: 'Soul Ties', desc: 'The deepest intimacy' }
  },
  strangers: {
    1: { title: 'Hello World', desc: 'Breaking the ice' },
    2: { title: 'Getting Curious', desc: 'Learning about each other' },
    3: { title: 'Real Talk', desc: 'Genuine connection' },
    4: { title: 'Unexpected Depth', desc: 'Strangers becoming something more' },
    5: { title: 'Brief Infinity', desc: 'Deep moments with someone you just met' }
  }
};

const QUESTIONS = {
  friends: {
    1: [
      "What's the most embarrassing song on your playlist right now?",
      "If you could instantly become an expert in one random skill, what would it be?",
      "What's your most irrational fear?",
      "What's the weirdest compliment you've ever received?",
      "If you had to eat one food for the rest of your life, what would it be?",
      "What's a conspiracy theory you secretly find believable?",
      "What's your go-to karaoke song?",
      "If you could live in any fictional world, which would you choose?",
      "What's something you're embarrassingly bad at?",
      "What's the most useless talent you have?",
      "If you could have dinner with any three people, dead or alive, who would they be?",
      "What's your most unpopular opinion?",
      "What's the strangest thing you believed as a child?",
      "If you could switch lives with anyone for a day, who would it be?",
      "What's your guilty pleasure TV show or movie?",
      "What would your perfect day look like?",
      "If you won the lottery tomorrow, what's the first thing you would buy?",
      "What's a skill you wish you had learned as a kid?",
      "What's your favorite way to waste time?",
      "If you could only listen to one music genre forever, what would it be?"
    ],
    2: [
      "What's something you pretend to understand but actually don't?",
      "When was the last time you changed your mind about something important?",
      "What's a risk you wish you had taken?",
      "What do you think people misunderstand about you?",
      "What's something you're working on improving about yourself?",
      "When do you feel most like yourself?",
      "What's a belief you've outgrown?",
      "What makes you feel most alive?",
      "What's something you've never told anyone?",
      "What's your biggest pet peeve about modern life?",
      "What's a mistake you're glad you made?",
      "What do you need more of in your life right now?",
      "What's something you do differently than most people?",
      "When do you feel most confident?",
      "What's a question you wish people would ask you?",
      "What's something you used to care about that you don't anymore?",
      "What makes you feel most vulnerable?",
      "What's a hard truth you've had to accept?",
      "What do you wish you cared less about?",
      "What's the best advice you've never taken?"
    ],
    3: [
      "What's a moment that changed the way you see the world?",
      "When have you felt most proud of yourself?",
      "What's something about your life right now that you haven't fully accepted?",
      "What's a conversation you've been avoiding?",
      "When was the last time you cried, and why?",
      "What's something you've lost that you wish you could get back?",
      "What's the hardest thing you've ever had to forgive someone for?",
      "When have you felt most misunderstood?",
      "What's something you're grieving?",
      "What part of your childhood do you miss most?",
      "What's a relationship that taught you the most about yourself?",
      "When did you last feel completely out of your depth?",
      "What's something you wish you could tell your younger self?",
      "What's a promise you made to yourself that you broke?",
      "What's the biggest sacrifice you've made for someone else?",
      "When have you felt most alone?",
      "What's something you've done that you're not proud of?",
      "What's a part of yourself you've had to let go of?",
      "What do you wish people knew about your struggles?",
      "What's the most significant thing you've ever lost that wasn't a person?"
    ],
    4: [
      "What are you most afraid people would think if they really knew you?",
      "What's a version of yourself you've had to let go of?",
      "What's something you're still healing from?",
      "When do you feel like you're not enough?",
      "What's a truth about yourself that's hard to admit?",
      "What do you wish you could forgive yourself for?",
      "What's the gap between who you are and who you want to be?",
      "What makes you feel most insecure?",
      "What's something you judge yourself harshly for?",
      "When do you feel most out of place in your own life?",
      "What's a fear that holds you back more than it should?",
      "What do you wish you could change about your past?",
      "What's something you're running from?",
      "When do you feel like you're pretending?",
      "What's a wound that hasn't fully healed?",
      "What do you need that you're not asking for?",
      "What's the hardest thing about being you right now?",
      "What part of yourself are you most ashamed of?",
      "What's something you're still learning to accept about yourself?",
      "What do you wish you had the courage to do?"
    ],
    5: [
      "What does loneliness feel like for you?",
      "What do you think your purpose is?",
      "What's the most defining relationship of your life so far?",
      "What does your inner critic sound like?",
      "What do you want to be remembered for?",
      "What's a decision that changed everything for you?",
      "What are you most grateful for that people don't see?",
      "What's the thing you most want to be asked right now?",
      "When have you felt most connected to something bigger than yourself?",
      "What would you do differently if you weren't afraid?",
      "What's the biggest lie you tell yourself?",
      "What does unconditional love mean to you?",
      "What's the hardest lesson you've had to learn?",
      "When do you feel most like you're becoming who you're meant to be?",
      "What are you holding onto that you need to release?",
      "What's a question you're afraid to know the answer to?",
      "What makes your life feel meaningful?",
      "What do you know now that you wish you knew sooner?",
      "What's the most honest thing you can say about yourself right now?",
      "If you died tomorrow, what would be left unsaid?"
    ]
  },

  family: {
    1: [
      "What's your favorite family tradition?",
      "What's the funniest family story you know?",
      "What's a meal that reminds you of home?",
      "Who in the family are you most like?",
      "What's a family saying or inside joke?",
      "What's your earliest memory of a family gathering?",
      "What holiday tradition means the most to you?",
      "Who tells the best stories in your family?",
      "What's something unique about your family culture?",
      "What's a family recipe you hope to pass down?",
      "What's the most memorable family vacation you've taken?",
      "What's a tradition you want to start in your own family someday?",
      "Who makes you laugh the most in your family?",
      "What's a family heirloom that has meaning to you?",
      "What's your favorite thing about family gatherings?",
      "What did your family do for fun when you were growing up?",
      "What's a family story that gets told over and over?",
      "Who in your family do you admire most?",
      "What's something your family does that you thought was normal but isn't?",
      "What's your favorite memory with a grandparent?"
    ],
    2: [
      "What values did your family instill in you?",
      "What's something you learned from your parents?",
      "What's a way you're different from your family?",
      "What do you wish you knew about your family history?",
      "What's something your family struggled with?",
      "What role do you play in your family dynamic?",
      "What's a family pattern you've noticed?",
      "What did your family teach you about money?",
      "What's something you appreciate about your upbringing now that you didn't then?",
      "What's a family value you disagree with?",
      "What did your family teach you about relationships?",
      "What's something you wish your family talked about more?",
      "What generational pattern do you want to break?",
      "What's a sacrifice your parents made that you now understand?",
      "What did your family teach you about emotions?",
      "What's something you inherited from your family beyond genetics?",
      "What's a way you're continuing your family legacy?",
      "What did your family teach you about success?",
      "What's something your parents got right?",
      "What's a belief from your family you've questioned as an adult?"
    ],
    3: [
      "What's something you wish you could tell your parents?",
      "What's the hardest thing about your family?",
      "When did you realize your parents were just people?",
      "What's something you resent about your family?",
      "What's a family wound that hasn't healed?",
      "What do you wish your family understood about you?",
      "What's a way your family let you down?",
      "What role did you play in your family that you didn't choose?",
      "What's something you've never said to a family member?",
      "What's a family expectation you couldn't meet?",
      "When did you feel most unseen by your family?",
      "What's something your family made you feel ashamed of?",
      "What's a family secret that affected you?",
      "What did your family teach you that you had to unlearn?",
      "What's something you needed from your family that you didn't get?",
      "What's the biggest misunderstanding in your family?",
      "What's a way you've disappointed your family?",
      "What do you grieve about your family?",
      "What's a conversation you need to have with a family member?",
      "What's something about your family you wish you could change?"
    ],
    4: [
      "What do you need to forgive your family for?",
      "What's the hardest thing you've had to accept about your parents?",
      "What cycle are you trying to break from your family?",
      "What's something you wish you had said to a family member before it was too late?",
      "What's a way your family shaped your relationship with yourself?",
      "What do you wish you could repair in your family?",
      "What's the biggest betrayal in your family history?",
      "What did you have to grieve about your childhood?",
      "What's a way you're parenting yourself differently than you were parented?",
      "What's something you've had to reparent yourself around?",
      "What family trauma are you still carrying?",
      "What do you wish your family had protected you from?",
      "What's something about your family you're still processing?",
      "What do you need to hear from a family member?",
      "What's a way your family's dysfunction affected your relationships?",
      "What do you wish you could go back and tell your child self about your family?",
      "What's the hardest truth you've accepted about your family?",
      "What boundary do you wish you had set with your family sooner?",
      "What's something you're working to heal from your family experience?",
      "What do you wish someone in your family would acknowledge?"
    ],
    5: [
      "What does family mean to you now?",
      "What's the greatest gift your family gave you?",
      "What generational strength runs in your family?",
      "What do you want to pass down to the next generation?",
      "What have you learned about yourself through your family?",
      "What's the most important thing your family taught you about love?",
      "What would you want to preserve about your family forever?",
      "What legacy do you want to create for your family?",
      "What's a way your family made you who you are today?",
      "What wisdom from your ancestors do you carry?",
      "What does it mean to belong to your family?",
      "What's the deepest way your family has shaped you?",
      "What healing do you hope to bring to your family line?",
      "What do you understand about your parents now that you're older?",
      "What's the most profound thing a family member ever taught you?",
      "What would you want your family to know about how you see them?",
      "What's the truest thing about your relationship with your family?",
      "What do you wish you could give your family?",
      "What does home mean to you in relation to family?",
      "What's the greatest act of love you've witnessed in your family?"
    ]
  },

  coworkers: {
    1: [
      "What's the best part of your workday?",
      "If you could do any job for a day, what would it be?",
      "What's your favorite productivity hack?",
      "What's the worst job you've ever had?",
      "What's your ideal work environment?",
      "If you could work from anywhere, where would it be?",
      "What's a skill you'd love to add to your resume?",
      "What's your coffee or tea order?",
      "What's the most unusual job you've had?",
      "What's your go-to lunch spot?",
      "If you could automate one part of your job, what would it be?",
      "What's your favorite way to unwind after work?",
      "What's the strangest thing that's happened to you at work?",
      "What podcast or playlist gets you through the workday?",
      "What's your biggest work pet peeve?",
      "If you had to pitch your job to a 10-year-old, how would you describe it?",
      "What's the best career advice you've received?",
      "What's something you're surprisingly good at in a work context?",
      "What would your dream office look like?",
      "What's a work tradition you'd love to start?"
    ],
    2: [
      "What motivates you to do your best work?",
      "What's a project you're proud of?",
      "What's something you wish people knew about your role?",
      "What's a professional risk you've taken?",
      "What's your working style?",
      "What do you value most in a colleague?",
      "What's something you've learned from a coworker?",
      "What's a challenge you're facing right now?",
      "What kind of recognition means the most to you?",
      "What's your biggest professional pet peeve?",
      "What's a mistake you learned the most from?",
      "What makes you feel valued at work?",
      "What's something about your job that surprised you?",
      "What's a strength you bring to the team?",
      "What's the best team you've ever been part of?",
      "What's something you're working to improve professionally?",
      "What kind of feedback helps you grow?",
      "What's your ideal collaboration style?",
      "What makes a good work relationship?",
      "What's something you wish was different about work culture?"
    ],
    3: [
      "What does work-life balance mean to you?",
      "What's the hardest part about your job?",
      "What do you wish you had more time for?",
      "What's a boundary you wish you had set earlier in your career?",
      "What sacrifices have you made for your career?",
      "What keeps you up at night work-wise?",
      "What would you do if money wasn't a factor?",
      "What's the most draining part of your work?",
      "What do you wish someone had told you about working life?",
      "What's something you're still figuring out about your career?",
      "What does success mean to you outside of work?",
      "What's a professional regret you have?",
      "What's the hardest professional decision you've had to make?",
      "What energizes you outside of work?",
      "What's something you do for work that goes against your values?",
      "What would make your job more meaningful?",
      "What's the biggest gap between your work life and personal life?",
      "What's a truth about your career path that's hard to admit?",
      "What do you wish you prioritized more?",
      "What's something you've sacrificed that you regret?"
    ],
    4: [
      "What kind of leader do you want to be?",
      "What's a professional fear you're working through?",
      "What's the biggest lesson you've learned from failure?",
      "What would you do if you knew you couldn't fail?",
      "What's holding you back professionally?",
      "What's a hard truth about your work that you've had to accept?",
      "What do you wish you had advocated for yourself about?",
      "What's your relationship with ambition?",
      "What's something you're proving to yourself?",
      "What does growth look like for you right now?",
      "What professional identity are you growing into?",
      "What's a limiting belief about your career?",
      "What would your ideal next chapter look like?",
      "What's something you need to let go of to move forward?",
      "What does integrity mean to you in your work?",
      "What's the bravest thing you've done professionally?",
      "What do you want your professional legacy to be?",
      "What's a value you refuse to compromise on?",
      "What's the gap between where you are and where you want to be?",
      "What would you tell your younger professional self?"
    ],
    5: [
      "What impact do you want to have through your work?",
      "What does meaningful work mean to you?",
      "What drives you beyond money and recognition?",
      "What change do you want to create in your field?",
      "What's your definition of professional success?",
      "What would make all the hard parts worth it?",
      "What problem are you meant to solve?",
      "What legacy do you want to leave in your career?",
      "What's the truest version of your professional self?",
      "What calling are you answering through your work?",
      "What would you do even if no one paid you?",
      "What's the intersection of your gifts and the world's needs?",
      "What does service mean to you in your work?",
      "What future are you working toward?",
      "What's the difference you hope to make?",
      "What fulfills you professionally beyond achievement?",
      "What would your work look like if you led with your values?",
      "What wisdom do you want to share through your work?",
      "What's the most important thing your work has taught you about yourself?",
      "What does it mean to you to do work that matters?"
    ]
  },

  lovers: {
    1: [
      "What's the first thing you noticed about me?",
      "What's your idea of a perfect date?",
      "What song makes you think of romance?",
      "What's your love language?",
      "What's the most attractive quality in a person?",
      "What's your go-to date night activity?",
      "What's the sweetest thing someone has ever done for you?",
      "What's your favorite thing about falling in love?",
      "What makes you feel butterflies?",
      "What's your idea of romantic?",
      "What's the best compliment you've ever received?",
      "What's your favorite way to show affection?",
      "What makes you laugh the hardest?",
      "What's a relationship green flag for you?",
      "What's your favorite memory of us so far?",
      "What do you find most attractive about me?",
      "What's something that makes you feel special?",
      "What's your favorite form of physical affection?",
      "What makes you feel desired?",
      "What's a small gesture that means a lot to you?"
    ],
    2: [
      "What's something you're hoping for in this relationship?",
      "What makes you feel most loved?",
      "What's a fear you have about relationships?",
      "What's something you've learned from past relationships?",
      "What do you need to feel secure?",
      "What's a way I make you feel seen?",
      "What's your biggest relationship insecurity?",
      "What's something you want to work on together?",
      "What does intimacy mean to you?",
      "What's a need you have that's hard to express?",
      "What makes you feel most connected to someone?",
      "What's a relationship pattern you're trying to break?",
      "What do you appreciate most about how we communicate?",
      "What's something you're afraid to need from me?",
      "What makes you feel safe with someone?",
      "What's a dream you have for us?",
      "What's something you want me to know about loving you?",
      "What's a way you want to grow in this relationship?",
      "What makes you feel most understood?",
      "What's something about relationships that scares you?"
    ],
    3: [
      "What's a part of yourself you're still learning to show me?",
      "What's something you're afraid I might judge?",
      "What do you need when you're at your worst?",
      "What's a wound from a past relationship you're still healing?",
      "What makes you pull away from intimacy?",
      "What's the hardest thing about letting me in?",
      "What do you wish I understood about your past?",
      "What's something you're ashamed of in relationships?",
      "What pattern from your family do you see in us?",
      "What's a way you protect yourself from getting hurt?",
      "What makes you feel most vulnerable with me?",
      "What's something you do when you're scared of being close?",
      "What do you need when you feel insecure?",
      "What's a fear you have about being fully known?",
      "What's something you haven't told me that you want to?",
      "What's the scariest part of loving someone?",
      "What makes you want to run?",
      "What do you need to feel like yourself in this relationship?",
      "What's a way I've hurt you that you haven't told me about?",
      "What's the hardest part about being with me?"
    ],
    4: [
      "What are you most afraid of in this relationship?",
      "What do you need from me that you're afraid to ask for?",
      "What's your deepest fear about us?",
      "What would it look like if you were completely yourself with me?",
      "What's something you're afraid I'll stop loving about you?",
      "What do you wish you could trust about us?",
      "What's the most honest thing you can say about how you feel?",
      "What makes you doubt us?",
      "What do you need to believe about me to feel secure?",
      "What's a truth about yourself you're afraid will push me away?",
      "What would change if you weren't afraid?",
      "What's something you need from this relationship to heal?",
      "What's your biggest relationship wound?",
      "What do you grieve about not having in past relationships?",
      "What would unconditional love from me look like?",
      "What's the bravest thing you could do in this relationship?",
      "What do you need to forgive yourself for?",
      "What's something about love you're still learning?",
      "What does forever mean to you?",
      "What would it take for you to let me all the way in?"
    ],
    5: [
      "What does loving me teach you about yourself?",
      "What's the deepest way I've changed you?",
      "What do you see when you look at our future?",
      "What makes this love different?",
      "What does it mean to you to be chosen by me?",
      "What's the most sacred thing about us?",
      "What truth about us feels too big to say?",
      "What would you want me to know if something happened to you?",
      "What does coming home to me feel like?",
      "What's the greatest gift you've received from loving me?",
      "What does it mean to grow old with someone?",
      "What's the most profound way we understand each other?",
      "What does our love make possible that wasn't before?",
      "What's the deepest promise you want to make to me?",
      "What does my love allow you to be?",
      "What's the most honest thing you can say about us?",
      "What would you want our story to be?",
      "What does devotion mean to you?",
      "What's the truest thing about the way I love you?",
      "What does it mean to be fully known and fully loved?"
    ]
  },

  strangers: {
    1: [
      "What brings you here today?",
      "Where are you from?",
      "What's keeping you busy these days?",
      "What's something good that happened recently?",
      "What's your favorite thing to do on weekends?",
      "Are you a morning person or night owl?",
      "What's the last thing you watched that you really enjoyed?",
      "What kind of music are you into?",
      "Do you have any fun plans coming up?",
      "What's your go-to comfort food?",
      "Are you working on anything exciting?",
      "What's your favorite way to spend a free day?",
      "What's the best meal you've had recently?",
      "Do you have any hobbies?",
      "What's your favorite place you've traveled to?",
      "What's something you're looking forward to?",
      "Are you more of a city person or nature person?",
      "What's your favorite season?",
      "Do you collect anything?",
      "What's a small thing that made you smile today?"
    ],
    2: [
      "What's something you're passionate about?",
      "What's a skill you're proud of?",
      "What's something most people don't know about you?",
      "What's a place that feels like home to you?",
      "What's something you're really good at?",
      "What kind of conversations energize you?",
      "What's something you've always wanted to try?",
      "What makes you feel most like yourself?",
      "What's a value that's important to you?",
      "What's something you believe strongly?",
      "What's a decision you're glad you made?",
      "What draws you to certain people?",
      "What's something you're currently learning?",
      "What matters most to you in life?",
      "What's a quality you admire in others?",
      "What energizes you?",
      "What's something you care deeply about?",
      "What's your relationship with your hometown?",
      "What makes a good conversation for you?",
      "What's something that inspires you?"
    ],
    3: [
      "What's something you're working through right now?",
      "What's a challenge you're facing?",
      "What's something you wish people understood about you?",
      "What makes you feel most alive?",
      "What's something you're questioning lately?",
      "What do you think you're here to do?",
      "What's a lesson you've learned recently?",
      "What are you trying to figure out about yourself?",
      "What's something you've changed your mind about?",
      "What makes you feel fulfilled?",
      "What's a risk you've taken that paid off?",
      "What do you wish you had more of in your life?",
      "What's something you're proud of overcoming?",
      "What keeps you up at night?",
      "What's something you're letting go of?",
      "What makes life meaningful to you?",
      "What's a truth you've had to accept?",
      "What are you most grateful for right now?",
      "What's something you wish you did more often?",
      "What's been on your mind lately?"
    ],
    4: [
      "What's something you've never told anyone?",
      "What are you most afraid of?",
      "What's a part of yourself you're still discovering?",
      "What do you need that you're not getting?",
      "What's a truth about yourself that's hard to admit?",
      "What makes you feel most vulnerable?",
      "What are you running from?",
      "What's something you wish you could change about your life?",
      "What do you wish someone would ask you?",
      "What's the hardest thing you're dealing with?",
      "What are you searching for?",
      "What would you do if you weren't afraid?",
      "What's something you judge yourself for?",
      "What do you wish you could believe about yourself?",
      "What's a wound you're still healing?",
      "What makes you feel most lonely?",
      "What's something you're grieving?",
      "What do you wish you had said to someone?",
      "What's the gap between who you are and who you want to be?",
      "What's the bravest thing you've ever done?"
    ],
    5: [
      "What does it mean to really be seen?",
      "What's the most honest thing you can say about yourself right now?",
      "What do you think happens when we die?",
      "What makes life worth living?",
      "What's your relationship with God or the universe?",
      "What do you think your purpose is?",
      "What truth are you avoiding?",
      "What does love mean to you?",
      "What would you want people to say about you when you're gone?",
      "What's the most important thing you've learned about being human?",
      "What are you most afraid to lose?",
      "What does it mean to live a good life?",
      "What's something you know for certain?",
      "What would you want your last words to be?",
      "What makes you feel most connected to humanity?",
      "What's the deepest truth you know?",
      "What would you do with one more day?",
      "What does it mean to matter?",
      "What's the most profound moment you've ever experienced?",
      "What would you want someone to know if this was your only conversation?"
    ]
  }
};
