-- Peelr September 2026 questions: COWORKERS
-- Theme: New Beginnings, a fresh start. New goals, new habits, the stretch of work this team is stepping into.
-- Depth is capped at professional vulnerability and ambition, kept light and fun overall, never personal-life trauma.
INSERT INTO questions (deck, layer, text_en, text_es) VALUES
-- Layer 1: playful, workplace safe, group energy
('coworkers', 1, 'Who on this team is most likely to actually keep a new habit going past the first week?', '¿Quién de este equipo es más capaz de mantener un hábito nuevo pasada la primera semana?'),
('coworkers', 1, 'What is one new thing you want to try at work this fall?', '¿Qué cosa nueva quieres probar en el trabajo este otoño?'),
('coworkers', 1, 'Who on this team answers emails the fastest, for better or worse?', '¿Quién de este equipo responde correos más rápido, para bien o para mal?'),
('coworkers', 1, 'What is the most useless app notification you get during work hours?', '¿Cuál es la notificación más inútil que recibes en horario de trabajo?'),
('coworkers', 1, 'If this team started one new tradition this fall, what should it be?', 'Si este equipo empezara una tradición nueva este otoño, ¿cuál debería ser?'),
('coworkers', 1, 'What is your honest go-to excuse for being five minutes late?', '¿Cuál es tu excusa de siempre, honestamente, para llegar cinco minutos tarde?'),
('coworkers', 1, 'Who on this team would win a trivia night carrying the whole group?', '¿Quién de este equipo ganaría una noche de trivia cargando a todo el grupo?'),
('coworkers', 1, 'What is a work habit you are trying to build this season?', '¿Qué hábito de trabajo estás tratando de construir esta temporada?'),
('coworkers', 1, 'Who on this team has the strongest opinions about the office coffee?', '¿Quién de este equipo tiene las opiniones más firmes sobre el café de la oficina?'),
('coworkers', 1, 'What is one thing you want to get better at professionally this fall?', '¿En qué quieres mejorar profesionalmente este otoño?'),
('coworkers', 1, 'Who here is most likely to reply all by accident?', '¿Quién de aquí es más capaz de responder a todos por accidente?'),
('coworkers', 1, 'What is the most creative excuse for being unreachable you have ever used?', '¿Cuál es la excusa más creativa que has usado para estar ilocalizable?'),
('coworkers', 1, 'If this team went on one outing this fall, what should it be?', 'Si este equipo hiciera una salida este otoño, ¿cuál debería ser?'),
('coworkers', 1, 'What is a snack you are convinced gets you through the afternoon slump?', '¿Qué snack te tiene convencido de que te salva del bajón de la tarde?'),
('coworkers', 1, 'What are you hoping this fall looks like at work, compared to summer?', '¿Cómo esperas que se vea este otoño en el trabajo, comparado con el verano?'),
('coworkers', 1, 'What is something about this team that took you a while to figure out?', '¿Qué de este equipo tardaste en entender?'),
('coworkers', 1, 'What is a small work win you had recently that nobody made a big deal of?', '¿Qué pequeño logro de trabajo tuviste recientemente que nadie celebró?'),
('coworkers', 1, 'Who on this team has surprised you the most since you started working together?', '¿Quién de este equipo te ha sorprendido más desde que empezaron a trabajar juntos?'),
('coworkers', 1, 'What do you think makes this team actually work well together?', '¿Qué crees que hace que este equipo funcione bien de verdad?'),
('coworkers', 1, 'What do you want this next stretch at work to look like?', '¿Cómo quieres que se vea esta próxima etapa en el trabajo?'),
-- Layer 2: personal but professional
('coworkers', 2, 'Who on this team do you think has grown the most since you started working together?', '¿Quién de este equipo crees que ha crecido más desde que empezaron a trabajar juntos?'),
('coworkers', 2, 'What is a skill outside your job description you wish people here knew you had?', '¿Qué habilidad fuera de tu puesto quisieras que la gente de aquí supiera que tienes?'),
('coworkers', 2, 'What is something you got better at this year that nobody noticed?', '¿En qué mejoraste este año sin que nadie lo notara?'),
('coworkers', 2, 'What is a strength you see in someone on this team that they might not see in themselves?', '¿Qué fortaleza ves en alguien de este equipo que tal vez no ve en sí mismo?'),
('coworkers', 2, 'What is one professional goal you are actually excited about this fall?', '¿Qué meta profesional te emociona de verdad este otoño?'),
('coworkers', 2, 'What do you want to be doing differently by the end of this year, career-wise?', '¿Qué quieres estar haciendo de otra forma para el final de este año, en tu carrera?'),
('coworkers', 2, 'What is a way this team has made your work easier that you have never said out loud?', '¿Cómo te ha facilitado el trabajo este equipo sin que nunca lo hayas dicho?'),
('coworkers', 2, 'What is a project you are quietly proud of that never got much credit?', '¿De qué proyecto estás orgulloso en silencio que nunca recibió mucho reconocimiento?'),
('coworkers', 2, 'What do you actually need from a team to feel like you can do your best work?', '¿Qué necesitas realmente de un equipo para sentir que puedes dar tu mejor trabajo?'),
('coworkers', 2, 'What is something you wanted to say in a meeting recently but did not?', '¿Qué quisiste decir en una reunión recientemente y no dijiste?'),
('coworkers', 2, 'Who on this team gives the most useful feedback?', '¿Quién de este equipo da la retroalimentación más útil?'),
('coworkers', 2, 'What is a goal you are chasing outside of work that this team has never heard about?', '¿Qué meta persigues fuera del trabajo de la que este equipo nunca ha oído hablar?'),
('coworkers', 2, 'What do you wish this team knew about you beyond your job title?', '¿Qué te gustaría que este equipo supiera de ti más allá de tu puesto?'),
('coworkers', 2, 'What do you think this team does better than most teams you have worked on?', '¿Qué crees que este equipo hace mejor que la mayoría de los equipos en los que has trabajado?'),
('coworkers', 2, 'What is a way you have grown as a professional this year?', '¿En qué has crecido como profesional este año?'),
('coworkers', 2, 'What are you hoping to leave behind professionally this season?', '¿Qué esperas dejar atrás profesionalmente esta temporada?'),
('coworkers', 2, 'What is a work skill you are proud you taught yourself?', '¿Qué habilidad de trabajo te enorgullece haber aprendido por tu cuenta?'),
('coworkers', 2, 'What do you think good teamwork actually requires, beyond just being nice?', '¿Qué requiere realmente un buen trabajo en equipo, más allá de ser amable?'),
('coworkers', 2, 'Who on this team made a hard week easier recently, and have you told them?', '¿Quién de este equipo te hizo más fácil una semana difícil recientemente, y se lo has dicho?'),
('coworkers', 2, 'What do you actually hope changes for you here over the next year?', '¿Qué esperas de verdad que cambie para ti aquí en el próximo año?'),
-- Layer 3: professional vulnerability, aspirations, mild insecurity
('coworkers', 3, 'What is a fear you have about where your career is actually heading?', '¿Qué miedo tienes sobre hacia dónde va realmente tu carrera?'),
('coworkers', 3, 'When did you feel most unsure of yourself on this team, even if nobody noticed?', '¿Cuándo te sentiste más inseguro en este equipo, aunque nadie lo notara?'),
('coworkers', 3, 'What is a work skill you are still faking confidence about?', '¿En qué habilidad de trabajo todavía finges seguridad?'),
('coworkers', 3, 'What is something about work that has been quietly weighing on you lately?', '¿Qué del trabajo te ha estado pesando en silencio últimamente?'),
('coworkers', 3, 'What is a moment this team helped you more than they probably realize?', '¿En qué momento este equipo te ayudó más de lo que probablemente se dan cuenta?'),
('coworkers', 3, 'What do you think you owe the people you work closely with, professionally?', '¿Qué crees que le debes profesionalmente a la gente con la que trabajas de cerca?'),
('coworkers', 3, 'What is a version of your career you once imagined that looks different now?', '¿Qué versión de tu carrera imaginaste alguna vez que ahora se ve distinta?'),
('coworkers', 3, 'What is something you needed from a manager once and never got?', '¿Qué necesitaste de un jefe alguna vez y nunca recibiste?'),
('coworkers', 3, 'What is the most nervous you have ever been before a meeting or a presentation?', '¿Cuándo has estado más nervioso antes de una reunión o una presentación?'),
('coworkers', 3, 'When did you last feel genuinely proud to be part of this team?', '¿Cuándo te sentiste realmente orgulloso de ser parte de este equipo por última vez?'),
('coworkers', 3, 'What do you think this team would do if one of you was struggling to keep up?', '¿Qué crees que haría este equipo si a alguno de ustedes le costara mantener el ritmo?'),
('coworkers', 3, 'What is something you are insecure about professionally that you cover well?', '¿Qué inseguridad profesional tienes que disimulas bien?'),
('coworkers', 3, 'What is a professional mistake you are still quietly replaying?', '¿Qué error profesional sigues repasando en silencio?'),
('coworkers', 3, 'What do you believe makes someone good at their job, beyond just results?', '¿Qué crees que hace bueno a alguien en su trabajo, más allá de los resultados?'),
('coworkers', 3, 'What is a way work has changed how you see yourself, for better or worse?', '¿Cómo ha cambiado el trabajo la forma en que te ves a ti mismo, para bien o para mal?'),
('coworkers', 3, 'What is something you wish this team asked you about more?', '¿Sobre qué te gustaría que este equipo te preguntara más?'),
('coworkers', 3, 'What is a fear about being replaceable that you rarely admit?', '¿Qué miedo a ser reemplazable rara vez admites?'),
('coworkers', 3, 'What is something you regret not saying in a work conversation that mattered?', '¿Qué te arrepientes de no haber dicho en una conversación de trabajo que importaba?'),
('coworkers', 3, 'What do you think makes a workplace actually feel safe to be honest in?', '¿Qué crees que hace que un lugar de trabajo se sienta seguro para ser honesto?'),
('coworkers', 3, 'What is the most impressive thing someone on this team has done that they never bragged about?', '¿Cuál es la cosa más impresionante que alguien de este equipo ha hecho sin nunca presumirlo?'),
-- Layer 4: honest, professional, ambition-focused
('coworkers', 4, 'What is a truth about this job you have been avoiding facing?', '¿Qué verdad sobre este trabajo has estado evitando enfrentar?'),
('coworkers', 4, 'What is something about how this team operates that nobody has said out loud?', '¿Qué de cómo funciona este equipo nadie ha dicho en voz alta?'),
('coworkers', 4, 'What do you think you are actually building toward in your career right now?', '¿Hacia qué crees que estás construyendo de verdad en tu carrera ahora mismo?'),
('coworkers', 4, 'What is the most honest answer to how this job is affecting you these days?', '¿Cuál es la respuesta más honesta a cómo te está afectando este trabajo últimamente?'),
('coworkers', 4, 'What is something this team could do better that is hard to bring up?', '¿Qué podría hacer mejor este equipo que es difícil de mencionar?'),
('coworkers', 4, 'What is a version of success you used to want that you no longer do?', '¿Qué versión del éxito querías antes que ya no quieres?'),
('coworkers', 4, 'What is a fear about your career you have never said out loud at work?', '¿Qué miedo sobre tu carrera nunca has dicho en voz alta en el trabajo?'),
('coworkers', 4, 'What is something you wish you could tell this team without it changing how they see you?', '¿Qué quisieras decirle a este equipo sin que cambie cómo te ven?'),
('coworkers', 4, 'What do you think this job is quietly asking you to give up?', '¿Qué crees que este trabajo te está pidiendo que sacrifiques en silencio?'),
('coworkers', 4, 'What is a moment you seriously considered a different path than this one?', '¿En qué momento consideraste seriamente un camino distinto a este?'),
('coworkers', 4, 'What do you think this team needs to hear from each other more often?', '¿Qué crees que este equipo necesita decirse más seguido entre ustedes?'),
('coworkers', 4, 'What is a compromise in your career you made that you are still thinking about?', '¿Qué concesión hiciste en tu carrera que todavía sigues pensando?'),
('coworkers', 4, 'What is the hardest part of showing up here on your worst days?', '¿Qué es lo más difícil de presentarte aquí en tus peores días?'),
('coworkers', 4, 'What is something about working here that you are honestly grateful for and rarely say?', '¿Qué de trabajar aquí agradeces de verdad y rara vez dices?'),
('coworkers', 4, 'What do you want people here to actually understand about how you work?', '¿Qué quieres que la gente de aquí entienda de verdad sobre cómo trabajas?'),
('coworkers', 4, 'What is a way you have grown that this job pushed you into, even if you did not want it to?', '¿En qué has crecido que este trabajo te empujó a hacer, aunque no lo quisieras?'),
('coworkers', 4, 'What is a way this team could support each other better going into a busy season?', '¿Cómo podría este equipo apoyarse mejor de cara a una temporada ocupada?'),
('coworkers', 4, 'What is the most stressed you have ever been right before something turned out fine?', '¿Cuándo has estado más estresado justo antes de que algo saliera bien?'),
('coworkers', 4, 'What is a boundary at work you are still learning how to hold?', '¿Qué límite en el trabajo todavía estás aprendiendo a sostener?'),
('coworkers', 4, 'What is the closest you have come to switching careers entirely?', '¿Cuál ha sido el momento más cercano en que casi cambias de carrera por completo?'),
-- Layer 5: professional meaning, values, ambition
('coworkers', 5, 'What do you want to be able to say this year of work built toward?', '¿Qué quieres poder decir que construyó este año de trabajo?'),
('coworkers', 5, 'Beyond the paycheck, what do you actually want your work to give you?', 'Más allá del sueldo, ¿qué quieres que te dé realmente tu trabajo?'),
('coworkers', 5, 'What did you learn about yourself this year that will outlast this job?', '¿Qué aprendiste de ti este año que va a durar más que este trabajo?'),
('coworkers', 5, 'What do you want the people on this team to remember about working with you?', '¿Qué quieres que la gente de este equipo recuerde de haber trabajado contigo?'),
('coworkers', 5, 'What is a version of your working life you are quietly building toward?', '¿Qué versión de tu vida laboral estás construyendo en silencio?'),
('coworkers', 5, 'What would you do professionally if the money were already handled?', '¿Qué harías profesionalmente si el dinero ya estuviera resuelto?'),
('coworkers', 5, 'What is something this job forced you to learn that turned out to be a gift?', '¿Qué te obligó a aprender este trabajo que resultó ser un regalo?'),
('coworkers', 5, 'What do you think you owe the version of you who was nervous on day one here?', '¿Qué crees que le debes a la versión de ti que estaba nervioso el primer día aquí?'),
('coworkers', 5, 'What is an idea about success at work you no longer believe?', '¿Qué idea sobre el éxito en el trabajo ya no crees?'),
('coworkers', 5, 'How would you actually know if your career had been worth it?', '¿Cómo sabrías de verdad si tu carrera valió la pena?'),
('coworkers', 5, 'What is a career fear you are ready to stop letting run the show?', '¿Qué miedo profesional estás listo para dejar de permitir que dirija todo?'),
('coworkers', 5, 'What do you understand about yourself now, professionally, that you did not a year ago?', '¿Qué entiendes de ti ahora, profesionalmente, que no entendías hace un año?'),
('coworkers', 5, 'What are you becoming professionally that this job alone cannot contain?', '¿En qué te estás convirtiendo profesionalmente que este trabajo por sí solo no puede contener?'),
('coworkers', 5, 'What do you hope this team looks back on this season and remembers?', '¿Qué esperas que este equipo recuerde al mirar atrás esta temporada?'),
('coworkers', 5, 'What is something you used to expect from a job that you no longer do?', '¿Qué solías esperar de un trabajo que ya no esperas?'),
('coworkers', 5, 'What is worth protecting about how you work, no matter where you end up?', '¿Qué de cómo trabajas vale la pena proteger, sin importar dónde termines?'),
('coworkers', 5, 'What would you tell someone starting on day one where you started?', '¿Qué le dirías a alguien que empieza en su primer día donde tú empezaste?'),
('coworkers', 5, 'What do you want to be different about your work life by next fall?', '¿Qué quieres que sea distinto en tu vida laboral para el próximo otoño?'),
('coworkers', 5, 'What is something about building things with this team you will be glad you did?', '¿Qué de construir cosas con este equipo te alegrará haber hecho?'),
('coworkers', 5, 'What is one thing about your work you hope never changes?', '¿Qué es lo único de tu trabajo que esperas que nunca cambie?');
