-- Peelr September 2026 questions: FAMILY
-- Theme: New Beginnings, a fresh start. New routines, new traditions, the season this family is stepping into.
INSERT INTO questions (deck, layer, text_en, text_es) VALUES
-- Layer 1: playful, light, group energy
('family', 1, 'Who in this family is most likely to actually stick to a new habit this fall?', '¿Quién de esta familia es más capaz de cumplir un nuevo hábito este otoño?'),
('family', 1, 'What is one thing you want to start doing together as a family this season?', '¿Qué quieres que esta familia empiece a hacer juntos esta temporada?'),
('family', 1, 'Who in this family gives the most unsolicited advice?', '¿Quién de esta familia da más consejos sin que se los pidan?'),
('family', 1, 'What is a smell that instantly takes you back to being a kid in this house?', '¿Qué olor te devuelve al instante a cuando eras niño en esta casa?'),
('family', 1, 'If this family picked one new tradition to start this fall, what should it be?', 'Si esta familia eligiera una tradición nueva para este otoño, ¿cuál debería ser?'),
('family', 1, 'What is the family car snack that never gets old?', '¿Cuál es el snack de carro familiar que nunca pasa de moda?'),
('family', 1, 'Who in this family takes the longest to get ready to leave the house?', '¿Quién de esta familia tarda más en arreglarse para salir?'),
('family', 1, 'What is something you are weirdly good at that nobody in this family taught you?', '¿En qué eres raramente bueno que nadie de esta familia te enseñó?'),
('family', 1, 'Who in this family would win an argument with absolutely nobody backing them up?', '¿Quién de esta familia ganaría una discusión sin que nadie lo apoyara?'),
('family', 1, 'What is a new routine you are hoping sticks this fall?', '¿Qué rutina nueva esperas que se te quede este otoño?'),
('family', 1, 'Who in this family is the hardest to surprise?', '¿A quién de esta familia es más difícil sorprender?'),
('family', 1, 'What is your go-to comfort food when the weather turns?', '¿Cuál es tu comida reconfortante cuando cambia el clima?'),
('family', 1, 'What is something about this fall you are already looking forward to as a family?', '¿Qué de este otoño ya esperas con ganas como familia?'),
('family', 1, 'What is a family habit you did not appreciate until you were older?', '¿Qué costumbre familiar no apreciaste hasta que creciste?'),
('family', 1, 'What is a small thing that always makes you feel like a kid again?', '¿Qué cosa pequeña siempre te hace sentir niño otra vez?'),
('family', 1, 'What is something this family does that you assumed every family did, until you found out otherwise?', '¿Qué hace esta familia que creías que hacían todas, hasta que descubriste que no?'),
('family', 1, 'What is something you are hoping to leave behind this season?', '¿Qué esperas dejar atrás esta temporada?'),
('family', 1, 'What made you laugh the hardest at a family thing recently?', '¿Qué te hizo reír más fuerte en algo familiar recientemente?'),
('family', 1, 'What do you think makes this family, specifically, work?', '¿Qué crees que hace que esta familia, en particular, funcione?'),
('family', 1, 'What do you want this next season of your life to look like?', '¿Cómo quieres que se vea esta próxima temporada de tu vida?'),
-- Layer 2: personal, warm
('family', 2, 'Who in this family do you think has changed the most in the last few years?', '¿Quién de esta familia crees que ha cambiado más en los últimos años?'),
('family', 2, 'What is a place you wish this family had visited together?', '¿Qué lugar desearías que esta familia hubiera visitado junta?'),
('family', 2, 'What is something about your life right now you have not shared with this family?', '¿Qué de tu vida ahora mismo no has compartido con esta familia?'),
('family', 2, 'What is a way this family shaped how you handle hard things?', '¿Cómo formó esta familia la manera en que enfrentas las cosas difíciles?'),
('family', 2, 'What is something new you want this family to know about you this year?', '¿Qué cosa nueva quieres que esta familia sepa de ti este año?'),
('family', 2, 'What are you hoping is different by the time we are all together again?', '¿Qué esperas que sea diferente para cuando estemos todos juntos otra vez?'),
('family', 2, 'Who in this family do you actually call first with good news?', '¿A quién de esta familia le llamas primero cuando tienes buenas noticias?'),
('family', 2, 'What is something you are proud of that you have never brought up at this table?', '¿De qué estás orgulloso y nunca lo has mencionado en esta mesa?'),
('family', 2, 'What do you actually need from this family to feel supported?', '¿Qué necesitas realmente de esta familia para sentirte apoyado?'),
('family', 2, 'What is something you are choosing to leave behind this season?', '¿Qué estás eligiendo dejar atrás esta temporada?'),
('family', 2, 'What is a piece of family wisdom that turned out to be completely wrong?', '¿Qué sabiduría familiar resultó estar completamente equivocada?'),
('family', 2, 'What is something about you this family has never really asked about?', '¿Qué de ti esta familia nunca ha preguntado realmente?'),
('family', 2, 'Who in this family would you trust with a real secret?', '¿A quién de esta familia le confiarías un secreto de verdad?'),
('family', 2, 'What is a moment one of us surprised you in a good way this year?', '¿En qué momento alguno de nosotros te sorprendió gratamente este año?'),
('family', 2, 'What do you think this family does better than most families?', '¿Qué crees que esta familia hace mejor que la mayoría de las familias?'),
('family', 2, 'What did you learn about yourself this year that surprised you?', '¿Qué aprendiste de ti este año que te sorprendió?'),
('family', 2, 'What is a family tradition you would want to pass down exactly as it is?', '¿Qué tradición familiar querrías transmitir exactamente igual?'),
('family', 2, 'What does feeling like family actually require, beyond blood?', '¿Qué se necesita realmente para sentirse familia, más allá de la sangre?'),
('family', 2, 'What do you want more of from this family as things settle into fall?', '¿De qué quieres más de esta familia ahora que todo entra en el otoño?'),
('family', 2, 'What do you think each of us brings to this family that nobody else could?', '¿Qué crees que cada uno aporta a esta familia que nadie más podría?'),
-- Layer 3: vulnerable, past, fears
('family', 3, 'What is a worry you carry about this family that you rarely say out loud?', '¿Qué preocupación cargas sobre esta familia que rara vez dices en voz alta?'),
('family', 3, 'What is a moment you felt like an outsider in your own family?', '¿En qué momento te sentiste como un extraño en tu propia familia?'),
('family', 3, 'What is the closest you came to a real blowup with someone here that never actually happened?', '¿Cuál fue el momento más cercano a un verdadero conflicto con alguien de aquí que nunca llegó a pasar?'),
('family', 3, 'What is something this family has never seen you struggle with?', '¿Con qué has batallado que esta familia nunca ha visto?'),
('family', 3, 'What is a memory from your childhood that still quietly affects you?', '¿Qué recuerdo de tu infancia todavía te afecta en silencio?'),
('family', 3, 'What do you think this family owes each other, honestly?', '¿Qué crees que se debe esta familia entre sí, honestamente?'),
('family', 3, 'What is a version of yourself you hide from most of this family?', '¿Qué versión de ti escondes de la mayoría de esta familia?'),
('family', 3, 'What is something you needed from a parent or a sibling once and never got?', '¿Qué necesitaste de un padre o un hermano alguna vez y nunca recibiste?'),
('family', 3, 'What is something you got away with as a kid that nobody in this family ever found out about?', '¿Qué hiciste de niño de lo que te saliste con la tuya sin que nadie en esta familia se enterara?'),
('family', 3, 'Who at this table has understood you the most without you having to explain?', '¿Quién de esta mesa te ha entendido más sin que tuvieras que explicar?'),
('family', 3, 'What do you think this family would do if one of us really needed help, no questions asked?', '¿Qué crees que haría esta familia si alguno de nosotros necesitara ayuda de verdad, sin preguntas?'),
('family', 3, 'What is something you are afraid this family will eventually realize about you?', '¿Qué temes que esta familia eventualmente se dé cuenta de ti?'),
('family', 3, 'When did you last cry about something to do with this family?', '¿Cuándo lloraste por última vez por algo relacionado con esta familia?'),
('family', 3, 'What do you believe about family loyalty that not everyone here would agree with?', '¿Qué crees sobre la lealtad familiar con lo que no todos aquí estarían de acuerdo?'),
('family', 3, 'What is a way you have changed that this family has not fully caught up to?', '¿En qué has cambiado que esta familia no ha terminado de notar?'),
('family', 3, 'What is something you wish this family knew about what you are carrying right now?', '¿Qué te gustaría que esta familia supiera de lo que estás cargando ahora mismo?'),
('family', 3, 'What is something you needed as a child that took you years to be able to name?', '¿Qué necesitabas de niño que te tomó años poder nombrar?'),
('family', 3, 'What is something you regret not saying to someone here before it got harder to say?', '¿Qué te arrepientes de no haberle dicho a alguien de aquí antes de que se volviera más difícil decirlo?'),
('family', 3, 'What do you think makes a family actually safe to be honest in?', '¿Qué crees que hace que una familia sea un lugar seguro para ser honesto?'),
('family', 3, 'What is a part of your life right now that feels harder than you let this family see?', '¿Qué parte de tu vida ahora mismo se siente más difícil de lo que le dejas ver a esta familia?'),
-- Layer 4: raw, confessional
('family', 4, 'What is an old hurt between two of us you are ready to put down?', '¿Qué herida vieja entre dos de nosotros estás listo para soltar?'),
('family', 4, 'What is something everyone in this family quietly knows but nobody says?', '¿Qué sabe todo el mundo en esta familia en silencio pero nadie dice?'),
('family', 4, 'What is something someone here did that you have carried without forgiving?', '¿Qué hizo alguien de aquí que has cargado sin perdonar?'),
('family', 4, 'What is an apology this family is still waiting to give or receive?', '¿Qué disculpa sigue esperando esta familia dar o recibir?'),
('family', 4, 'What is a choice you made that this family still does not know about?', '¿Qué decisión tomaste que esta familia todavía no conoce?'),
('family', 4, 'What is a cycle in this family history you are determined to break?', '¿Qué ciclo de la historia de esta familia estás decidido a romper?'),
('family', 4, 'What is a resentment you have never fully put into words?', '¿Qué resentimiento nunca has terminado de poner en palabras?'),
('family', 4, 'What is a time this family was not there for you the way you needed?', '¿Cuándo esta familia no estuvo presente para ti como lo necesitabas?'),
('family', 4, 'What is a secret you have kept to protect someone in this family?', '¿Qué secreto has guardado para proteger a alguien de esta familia?'),
('family', 4, 'What is the hardest thing about the way this family loves each other?', '¿Qué es lo más difícil de la forma en que esta familia se quiere?'),
('family', 4, 'What loss connected to this family have you never fully let yourself feel?', '¿Qué pérdida relacionada con esta familia nunca te has permitido sentir del todo?'),
('family', 4, 'What do you think makes you the hardest one in this family to be close to?', '¿Qué crees que te hace el más difícil de esta familia para acercarse?'),
('family', 4, 'What have you been afraid to say at this table for years?', '¿Qué has tenido miedo de decir en esta mesa durante años?'),
('family', 4, 'What would you say to someone here if you knew it was your last real chance?', '¿Qué le dirías a alguien de aquí si supieras que es tu última oportunidad real?'),
('family', 4, 'What is a hope you had for this family that never came true?', '¿Qué esperanza tenías para esta familia que nunca se cumplió?'),
('family', 4, 'What about your life have you kept hidden because of what this family would say?', '¿Qué de tu vida has mantenido escondido por lo que diría esta familia?'),
('family', 4, 'What is something you wish you had done differently as a parent, a child, or a sibling?', '¿Qué desearías haber hecho diferente como padre, hijo o hermano?'),
('family', 4, 'What are you still angry about here that you pretend is settled?', '¿Sobre qué sigues enojado aquí aunque finges que ya está resuelto?'),
('family', 4, 'If this family stayed exactly like this, could you live with that?', 'Si esta familia se quedara exactamente así, ¿podrías vivir con eso?'),
('family', 4, 'What is the smallest thing that has ever caused the biggest fight in this family?', '¿Cuál es la cosa más pequeña que ha causado la pelea más grande en esta familia?'),
-- Layer 5: soul, meaning, legacy
('family', 5, 'When your life is looked back on, what do you hope this family made possible?', '¿Cuando se mire tu vida en retrospectiva, qué esperas que esta familia haya hecho posible?'),
('family', 5, 'What is something from this family you want to carry forward, and something you want to end?', '¿Qué de esta familia quieres llevar contigo, y qué quieres que termine?'),
('family', 5, 'What is the truest thing you know about the people in this family?', '¿Cuál es la verdad más cierta que sabes sobre la gente de esta familia?'),
('family', 5, 'What do you hope this family remembers about who you really were?', '¿Qué esperas que esta familia recuerde sobre quién fuiste de verdad?'),
('family', 5, 'What do you understand about your parents now that you could not before?', '¿Qué entiendes de tus padres ahora que antes no podías?'),
('family', 5, 'What is a way someone in this family changed the direction of your life?', '¿Cómo cambió alguien de esta familia el rumbo de tu vida?'),
('family', 5, 'What do you picture for this family a generation from now?', '¿Cómo te imaginas a esta familia dentro de una generación?'),
('family', 5, 'What used to hurt about this family that you have quietly let go of?', '¿Qué solía dolerte de esta familia que has soltado en silencio?'),
('family', 5, 'What about this family deserves to be protected no matter what changes around it?', '¿Qué de esta familia merece protegerse sin importar lo que cambie alrededor?'),
('family', 5, 'What do you think you owe the child you once were in this family?', '¿Qué crees que le debes al niño que alguna vez fuiste en esta familia?'),
('family', 5, 'What is a fear you are ready to lay down about this family?', '¿Qué miedo sobre esta familia estás listo para soltar?'),
('family', 5, 'What is a chapter of your life that is quietly beginning as this season starts?', '¿Qué capítulo de tu vida está comenzando en silencio con esta temporada?'),
('family', 5, 'What is something this family taught you that you had to quietly rewrite for yourself?', '¿Qué te enseñó esta familia que tuviste que reescribir en silencio para ti mismo?'),
('family', 5, 'What do you want the next generation of this family to understand about love that took you years to learn?', '¿Qué quieres que la siguiente generación de esta familia entienda sobre el amor que a ti te tomó años aprender?'),
('family', 5, 'What is something about this family that shows up in you no matter where you are?', '¿Qué de esta familia aparece en ti sin importar dónde estés?'),
('family', 5, 'What is something you want to build with this family before it is too late?', '¿Qué quieres construir con esta familia antes de que sea tarde?'),
('family', 5, 'What are you grateful for about being from this family that is hard to explain?', '¿Qué agradeces de ser de esta familia que es difícil de explicar?'),
('family', 5, 'If this family had a motto, what should it actually be?', 'Si esta familia tuviera un lema, ¿cuál debería ser en realidad?'),
('family', 5, 'What is one tradition you hope this family still has in fifty years?', '¿Qué tradición esperas que esta familia todavía tenga dentro de cincuenta años?'),
('family', 5, 'What would you want to have said if you knew this were the only chance?', '¿Qué te gustaría haber dicho si supieras que esta fuera la única oportunidad?');
