-- Peelr September 2026 questions: FRIENDS
-- Theme: New Beginnings, a fresh start. New routines, new goals, the version of you stepping into fall.
INSERT INTO questions (deck, layer, text_en, text_es) VALUES
-- Layer 1: playful, light, group energy
('friends', 1, 'What is the default plan for this group when nobody can decide what to do?', '¿Cuál es el plan de siempre de este grupo cuando nadie se decide?'),
('friends', 1, 'If you started one new hobby this fall, what would actually stick?', 'Si empezaras un pasatiempo nuevo este otoño, ¿cuál se te quedaría de verdad?'),
('friends', 1, 'What is one thing you want to try for the first time this season?', '¿Qué quieres probar por primera vez esta temporada?'),
('friends', 1, 'Who in this group is most likely to actually keep a September resolution?', '¿Quién de este grupo es más capaz de cumplir un propósito de septiembre?'),
('friends', 1, 'What small thing instantly puts you in a good mood?', '¿Qué cosa pequeña te pone de buen humor al instante?'),
('friends', 1, 'What are you most excited to start this month?', '¿Qué es lo que más ganas tienes de empezar este mes?'),
('friends', 1, 'Which of us would survive the longest without a phone?', '¿Quién de nosotros aguantaría más tiempo sin celular?'),
('friends', 1, 'What is a skill you wish you had learned by now?', '¿Qué habilidad te gustaría ya haber aprendido?'),
('friends', 1, 'Who in this group gives the most convincing fake enthusiasm?', '¿Quién de este grupo finge entusiasmo de forma más creíble?'),
('friends', 1, 'What is the most useless talent you are proud of?', '¿Cuál es el talento más inútil del que estás orgulloso?'),
('friends', 1, 'What is a routine you are trying to build this fall?', '¿Qué rutina estás tratando de construir este otoño?'),
('friends', 1, 'If this group had a theme song, what would it be?', 'Si este grupo tuviera una canción propia, ¿cuál sería?'),
('friends', 1, 'What is something small that made you happy this week?', '¿Qué cosa pequeña te hizo feliz esta semana?'),
('friends', 1, 'What are you looking forward to now that summer is over?', '¿Qué esperas con ganas ahora que terminó el verano?'),
('friends', 1, 'What is a memory with this group you did not expect to matter this much?', '¿Qué recuerdo con este grupo te importó más de lo que esperabas?'),
('friends', 1, 'What is something you have gotten better at without even trying?', '¿En qué has mejorado sin siquiera intentarlo?'),
('friends', 1, 'What habit are you trying to leave behind this season?', '¿Qué costumbre estás tratando de dejar atrás esta temporada?'),
('friends', 1, 'What made you laugh the hardest recently?', '¿Qué te hizo reír más fuerte recientemente?'),
('friends', 1, 'What do you think makes this group actually work?', '¿Qué crees que hace que este grupo funcione de verdad?'),
('friends', 1, 'What do you want this next chapter of your life to look like?', '¿Cómo quieres que se vea este próximo capítulo de tu vida?'),
-- Layer 2: personal, warm
('friends', 2, 'What is a place you have never been that you keep saying you will visit?', '¿Qué lugar nunca has visitado aunque siempre dices que irás?'),
('friends', 2, 'What is one thing on your list to finally do this fall?', '¿Qué cosa de tu lista quieres por fin hacer este otoño?'),
('friends', 2, 'What is something about your life right now you have not told this group?', '¿Qué de tu vida ahora mismo no le has contado a este grupo?'),
('friends', 2, 'What is a way this group has shaped who you are?', '¿Cómo ha formado este grupo a la persona que eres?'),
('friends', 2, 'What is a small thing that instantly makes you trust someone?', '¿Qué cosa pequeña hace que confíes en alguien al instante?'),
('friends', 2, 'What are you hoping is different about you by the end of this year?', '¿Qué esperas que sea diferente en ti para el final de este año?'),
('friends', 2, 'Who in this group do you go to for the best advice, and why?', '¿A quién de este grupo acudes por los mejores consejos, y por qué?'),
('friends', 2, 'What is something you are proud of that you rarely bring up?', '¿De qué estás orgulloso que casi nunca mencionas?'),
('friends', 2, 'What do you actually need from a friendship to feel like it is real?', '¿Qué necesitas realmente de una amistad para que se sienta genuina?'),
('friends', 2, 'What is something you are letting go of as this year moves forward?', '¿Qué estás soltando conforme avanza este año?'),
('friends', 2, 'What is a compliment you received that you still think about?', '¿Qué cumplido recibiste que todavía recuerdas?'),
('friends', 2, 'What is something about you this group has never asked about?', '¿Qué de ti este grupo nunca ha preguntado?'),
('friends', 2, 'What is the best advice you have gotten from someone your own age?', '¿Cuál es el mejor consejo que has recibido de alguien de tu edad?'),
('friends', 2, 'What is a risk you are thinking about taking soon?', '¿Qué riesgo estás pensando en tomar pronto?'),
('friends', 2, 'What do you think this group does better than most friend groups?', '¿Qué crees que este grupo hace mejor que la mayoría de los grupos de amigos?'),
('friends', 2, 'What is something you learned about yourself this year that surprised you?', '¿Qué descubriste de ti este año que no esperabas?'),
('friends', 2, 'What is a version of fun you have outgrown?', '¿Qué tipo de diversión ya dejaste atrás?'),
('friends', 2, 'What does being a good friend actually require, in your opinion?', '¿Qué requiere de verdad ser un buen amigo, en tu opinión?'),
('friends', 2, 'What do you want more of as things settle into a new routine?', '¿De qué quieres más ahora que todo entra en una nueva rutina?'),
('friends', 2, 'What do you think each of us brings to this group that nobody else could?', '¿Qué crees que cada uno aporta a este grupo que nadie más podría?'),
-- Layer 3: vulnerable, past, fears
('friends', 3, 'What is a fear you have about losing touch with people you love?', '¿Qué miedo tienes de perder contacto con la gente que quieres?'),
('friends', 3, 'When did you last feel truly lonely, even with people around?', '¿Cuándo te sentiste realmente solo por última vez, incluso rodeado de gente?'),
('friends', 3, 'What is the closest you have come to telling someone off, and did not?', '¿Cuál ha sido el momento más cercano en que casi le dices sus verdades a alguien, y no lo hiciste?'),
('friends', 3, 'What is something this group has never seen you struggle with?', '¿Con qué has batallado que este grupo nunca ha visto?'),
('friends', 3, 'What is a friendship you let fade that you still think about?', '¿Qué amistad dejaste apagar que todavía recuerdas?'),
('friends', 3, 'What do you think you owe the people who have stuck around for you?', '¿Qué crees que le debes a la gente que se ha quedado a tu lado?'),
('friends', 3, 'What is a version of yourself you hide from most people, even some friends?', '¿Qué versión de ti escondes de la mayoría, incluso de algunos amigos?'),
('friends', 3, 'What is something you needed from a friend once and never got?', '¿Qué necesitaste de un amigo alguna vez y nunca recibiste?'),
('friends', 3, 'What is the last thing you searched online at two in the morning that you would not admit to?', '¿Qué fue lo último que buscaste en línea a las dos de la mañana que no admitirías?'),
('friends', 3, 'What is a moment you felt someone finally understood you?', '¿En qué momento sentiste que alguien por fin te entendió?'),
('friends', 3, 'What do you think this group would do if one of us really needed help, no questions asked?', '¿Qué crees que haría este grupo si alguno de nosotros necesitara ayuda de verdad, sin preguntas?'),
('friends', 3, 'What is something you are afraid people will eventually realize about you?', '¿Qué temes que la gente eventualmente se dé cuenta de ti?'),
('friends', 3, 'When did you last cry and not tell anyone why?', '¿Cuándo lloraste por última vez sin decirle a nadie por qué?'),
('friends', 3, 'What is something you believe about loyalty that most people would disagree with?', '¿Qué crees sobre la lealtad con lo que la mayoría de la gente no estaría de acuerdo?'),
('friends', 3, 'What is a way you have changed that not everyone in your life has caught up to?', '¿En qué has cambiado que no todos en tu vida han notado todavía?'),
('friends', 3, 'What is something you wish this group knew about what you are carrying right now?', '¿Qué te gustaría que este grupo supiera de lo que estás cargando ahora mismo?'),
('friends', 3, 'What is a fear you had as a kid that you still quietly carry?', '¿Qué miedo tenías de niño que todavía cargas en silencio?'),
('friends', 3, 'What is something you regret not saying to someone before it got harder to say?', '¿Qué te arrepientes de no haberle dicho a alguien antes de que se volviera más difícil decirlo?'),
('friends', 3, 'What do you think makes someone actually trustworthy, beyond just keeping secrets?', '¿Qué crees que hace a alguien realmente confiable, más allá de guardar secretos?'),
('friends', 3, 'What is a part of your life right now that feels harder than you let on?', '¿Qué parte de tu vida ahora mismo se siente más difícil de lo que dejas ver?'),
-- Layer 4: raw, confessional
('friends', 4, 'What is something you have never told anyone in this group?', '¿Qué nunca le has contado a nadie de este grupo?'),
('friends', 4, 'What is a lie you told a friend to avoid a harder conversation?', '¿Qué mentira le dijiste a un amigo para evitar una conversación más difícil?'),
('friends', 4, 'Who have you drifted from that you still miss more than you admit?', '¿De quién te alejaste y todavía extrañas más de lo que admites?'),
('friends', 4, 'What is something you did to a friend once that you have never apologized for?', '¿Qué le hiciste a un amigo alguna vez por lo que nunca te disculpaste?'),
('friends', 4, 'What is the real reason behind a friendship that ended?', '¿Cuál fue la verdadera razón detrás de una amistad que terminó?'),
('friends', 4, 'What is a boundary you have never actually enforced with someone you love?', '¿Qué límite nunca has hecho valer de verdad con alguien que quieres?'),
('friends', 4, 'What is something you are jealous of in someone close to you?', '¿Qué de alguien cercano a ti te da envidia?'),
('friends', 4, 'What is a version of yourself you buried to keep a friendship?', '¿Qué versión de ti enterraste para conservar una amistad?'),
('friends', 4, 'What is the pettiest reason you have ever stopped talking to someone?', '¿Cuál es la razón más insignificante por la que dejaste de hablarle a alguien?'),
('friends', 4, 'What is a secret you are keeping to protect a friendship?', '¿Qué secreto guardas para proteger una amistad?'),
('friends', 4, 'What is something about this group dynamic that quietly bothers you?', '¿Qué de la dinámica de este grupo te molesta en silencio?'),
('friends', 4, 'What is a way you have let a friend down that they never found out about?', '¿Cómo le has fallado a un amigo sin que se enterara?'),
('friends', 4, 'What do you think people find hardest to love about you?', '¿Qué crees que es lo más difícil de querer en ti para la gente?'),
('friends', 4, 'What is something you have needed to say to someone in this room and never have?', '¿Qué has necesitado decirle a alguien de esta sala y nunca lo has hecho?'),
('friends', 4, 'What is a friendship you are holding onto out of habit more than connection?', '¿Qué amistad conservas más por costumbre que por conexión real?'),
('friends', 4, 'What is a part of yourself you have not shown anyone in years?', '¿Qué parte de ti no le has mostrado a nadie en años?'),
('friends', 4, 'What is the most embarrassing thing you have done for someone you liked?', '¿Qué es lo más vergonzoso que has hecho por alguien que te gustaba?'),
('friends', 4, 'What is something you are ashamed you needed help with?', '¿Con qué te da vergüenza haber necesitado ayuda?'),
('friends', 4, 'What do you think loving someone well actually costs you?', '¿Qué crees que te cuesta de verdad querer bien a alguien?'),
('friends', 4, 'What is a truth about your life right now you have been avoiding saying out loud?', '¿Qué verdad sobre tu vida ahora mismo has evitado decir en voz alta?'),
-- Layer 5: soul, meaning, becoming
('friends', 5, 'What do you want your friendships to have given you by the end of your life?', '¿Qué quieres que te hayan dado tus amistades al final de tu vida?'),
('friends', 5, 'What do you think you are here to learn from the people you love?', '¿Qué crees que estás aquí para aprender de la gente que quieres?'),
('friends', 5, 'What is the truest thing your friendships have taught you about yourself?', '¿Cuál es la verdad más grande que tus amistades te han enseñado sobre ti?'),
('friends', 5, 'What kind of friend do you want to become that you are not yet?', '¿Qué tipo de amigo quieres llegar a ser que todavía no eres?'),
('friends', 5, 'What do you understand about love now that you did not five years ago?', '¿Qué entiendes del amor ahora que no entendías hace cinco años?'),
('friends', 5, 'What do you want to be known for by the people who really know you?', '¿Por qué quieres ser conocido entre la gente que realmente te conoce?'),
('friends', 5, 'What is a belief about friendship you have had to unlearn?', '¿Qué creencia sobre la amistad has tenido que desaprender?'),
('friends', 5, 'What is something your closest friendships have healed in you?', '¿Qué han sanado en ti tus amistades más cercanas?'),
('friends', 5, 'What do you hope this group means to each of us years from now?', '¿Qué esperas que este grupo signifique para cada uno de nosotros dentro de muchos años?'),
('friends', 5, 'What is worth protecting about how you love people, no matter what?', '¿Qué de la forma en que quieres a la gente vale la pena proteger, pase lo que pase?'),
('friends', 5, 'If your life were a story, what would this current chapter be called?', 'Si tu vida fuera una historia, ¿cómo se llamaría este capítulo actual?'),
('friends', 5, 'What have you stopped needing your friendships to prove?', '¿Qué dejaste de necesitar que tus amistades demostraran?'),
('friends', 5, 'What do you owe the friends who believed in you before you believed in yourself?', '¿Qué le debes a los amigos que creyeron en ti antes de que tú creyeras en ti mismo?'),
('friends', 5, 'What is a fear about growing older with the people you love that you are ready to name?', '¿Qué miedo sobre envejecer junto a la gente que quieres estás listo para nombrar?'),
('friends', 5, 'What does a life full of real connection look like to you, specifically?', '¿Cómo se ve, en concreto, una vida llena de conexión real para ti?'),
('friends', 5, 'What did this past year teach you about who actually shows up?', '¿Qué te enseñó este último año sobre quién de verdad está presente?'),
('friends', 5, 'What do you want to build with the people closest to you before life gets busier?', '¿Qué quieres construir con la gente más cercana a ti antes de que la vida se ocupe más?'),
('friends', 5, 'What is one thing you hope never changes about this group, no matter how life pulls us apart?', '¿Qué es lo único que esperas que nunca cambie de este grupo, sin importar cómo nos separe la vida?'),
('friends', 5, 'What is something you are grateful for about your people that is hard to explain?', '¿Qué agradeces de tu gente que es difícil de explicar?'),
('friends', 5, 'What do you want to have given the people who love you, in the end?', '¿Qué quieres haberle dado a la gente que te quiere, al final?');
