-- Peelr September 2026 questions: LOVERS
-- Theme: New Beginnings, a fresh start. New rituals, new chapters, what this couple is stepping into.
INSERT INTO questions (deck, layer, text_en, text_es) VALUES
-- Layer 1: playful, light, romantic curiosity
('lovers', 1, 'What is one new thing you want us to try together this fall?', '¿Qué cosa nueva quieres que probemos juntos este otoño?'),
('lovers', 1, 'What is the first thing you noticed about me when we met?', '¿Qué fue lo primero que notaste de mí cuando nos conocimos?'),
('lovers', 1, 'What is a small thing I do that you did not expect to fall for?', '¿Qué cosa pequeña hago que no esperabas que te enamorara?'),
('lovers', 1, 'What is a new tradition you want us to start this season?', '¿Qué tradición nueva quieres que empecemos esta temporada?'),
('lovers', 1, 'What is your favorite version of a lazy day with me?', '¿Cuál es tu versión favorita de un día tranquilo conmigo?'),
('lovers', 1, 'What is something about me you still find funny every time?', '¿Qué de mí todavía te parece gracioso cada vez?'),
('lovers', 1, 'If we had one perfect weekend right now, what would it look like?', 'Si tuviéramos un fin de semana perfecto ahora mismo, ¿cómo sería?'),
('lovers', 1, 'What is a habit of mine that secretly makes you smile?', '¿Qué costumbre mía te hace sonreír en secreto?'),
('lovers', 1, 'What is something new you want us to learn together this fall?', '¿Qué quieres que aprendamos juntos este otoño?'),
('lovers', 1, 'What is the most us thing we do that nobody else would understand?', '¿Cuál es la cosa más nuestra que hacemos que nadie más entendería?'),
('lovers', 1, 'What is a compliment you have never actually said to me out loud?', '¿Qué cumplido nunca me has dicho en voz alta?'),
('lovers', 1, 'What is your favorite way I show you I am thinking about you?', '¿Cuál es tu forma favorita en que te demuestro que pienso en ti?'),
('lovers', 1, 'What is something about our story so far that still makes you smile?', '¿Qué de nuestra historia hasta ahora todavía te hace sonreír?'),
('lovers', 1, 'What is one thing you want more of between us this season?', '¿De qué quieres más entre nosotros esta temporada?'),
('lovers', 1, 'What is a moment recently that reminded you why you chose me?', '¿Qué momento reciente te recordó por qué me elegiste?'),
('lovers', 1, 'What is something small I did that meant more than I probably realized?', '¿Qué cosa pequeña hice que significó más de lo que probablemente me di cuenta?'),
('lovers', 1, 'What are you looking forward to about us this fall?', '¿Qué esperas con ganas de nosotros este otoño?'),
('lovers', 1, 'What is a way I have surprised you lately?', '¿Cómo te he sorprendido últimamente?'),
('lovers', 1, 'What do you think makes us actually work as a couple?', '¿Qué crees que hace que funcionemos de verdad como pareja?'),
('lovers', 1, 'What do you want this next season of us to look like?', '¿Cómo quieres que se vea esta próxima temporada de nosotros?'),
-- Layer 2: personal, warm
('lovers', 2, 'What is a place you want us to go that we have never been?', '¿A qué lugar quieres que vayamos que nunca hemos visitado?'),
('lovers', 2, 'What is one thing on your list for us to finally do this fall?', '¿Qué cosa de tu lista quieres que por fin hagamos este otoño?'),
('lovers', 2, 'What is something about your life right now you have not fully told me?', '¿Qué de tu vida ahora mismo no me has contado del todo?'),
('lovers', 2, 'What is a way I have changed how you see love?', '¿Cómo he cambiado la forma en que ves el amor?'),
('lovers', 2, 'What is a small gesture that instantly makes you feel loved?', '¿Qué gesto pequeño te hace sentir querido al instante?'),
('lovers', 2, 'What are you hoping is different about us by the end of this year?', '¿Qué esperas que sea diferente entre nosotros para el final de este año?'),
('lovers', 2, 'What is something you admire about me that you rarely say?', '¿Qué admiras de mí que rara vez dices?'),
('lovers', 2, 'What is something you are proud of that you have not brought up with me?', '¿De qué estás orgulloso y no lo has mencionado conmigo?'),
('lovers', 2, 'What do you actually need from me to feel secure?', '¿Qué necesitas realmente de mí para sentirte seguro?'),
('lovers', 2, 'What is something you are choosing to leave behind this season, for us?', '¿Qué estás eligiendo dejar atrás esta temporada, por nosotros?'),
('lovers', 2, 'What is a memory of us you replay when you miss me?', '¿Qué recuerdo nuestro repites cuando me extrañas?'),
('lovers', 2, 'What is something about you I have never really asked about?', '¿Qué de ti nunca te he preguntado de verdad?'),
('lovers', 2, 'What is the best advice about love you have ever gotten?', '¿Cuál es el mejor consejo sobre el amor que has recibido?'),
('lovers', 2, 'What is a risk in this relationship you are thinking about taking?', '¿Qué riesgo en esta relación estás pensando en tomar?'),
('lovers', 2, 'What do you think we do better than most couples?', '¿Qué crees que hacemos mejor que la mayoría de las parejas?'),
('lovers', 2, 'What did you learn about yourself this year that changed how you love?', '¿Qué aprendiste de ti este año que cambió cómo amas?'),
('lovers', 2, 'What is a version of romance you have outgrown?', '¿Qué tipo de romance ya dejaste atrás?'),
('lovers', 2, 'What does being a good partner actually require, in your opinion?', '¿Qué requiere de verdad ser una buena pareja, en tu opinión?'),
('lovers', 2, 'What do you want more of from me as things settle into fall?', '¿De qué quieres más de mí ahora que todo entra en el otoño?'),
('lovers', 2, 'What do you think each of us brings to this relationship that the other could not?', '¿Qué crees que cada uno aporta a esta relación que el otro no podría?'),
-- Layer 3: vulnerable, past, fears
('lovers', 3, 'What is a fear you have about us as time goes on?', '¿Qué miedo tienes sobre nosotros con el paso del tiempo?'),
('lovers', 3, 'When did you feel most alone in this relationship, even next to me?', '¿Cuándo te sentiste más solo en esta relación, incluso a mi lado?'),
('lovers', 3, 'What is the closest you came to saying something honest to me and did not?', '¿Cuál fue el momento más cercano en que casi me dices algo honesto y no lo hiciste?'),
('lovers', 3, 'What is something about you I have never seen you struggle with?', '¿Con qué has batallado que yo nunca he visto?'),
('lovers', 3, 'What is a past relationship pattern you worry you are repeating with me?', '¿Qué patrón de una relación pasada te preocupa estar repitiendo conmigo?'),
('lovers', 3, 'What do you think you owe me after everything we have been through?', '¿Qué crees que me debes después de todo lo que hemos pasado?'),
('lovers', 3, 'What is a version of yourself you hide from me sometimes?', '¿Qué versión de ti a veces me escondes?'),
('lovers', 3, 'What is something you needed from me once and never got?', '¿Qué necesitaste de mí alguna vez y nunca recibiste?'),
('lovers', 3, 'What is a fear about love you had before us that still lingers?', '¿Qué miedo sobre el amor tenías antes de nosotros que todavía persiste?'),
('lovers', 3, 'What is a moment you felt truly understood by me?', '¿En qué momento sentiste que realmente te entendí?'),
('lovers', 3, 'What do you think I would do if you really needed me, no questions asked?', '¿Qué crees que haría yo si de verdad me necesitaras, sin preguntas?'),
('lovers', 3, 'What is something you are afraid I will eventually realize about you?', '¿Qué temes que eventualmente me dé cuenta de ti?'),
('lovers', 3, 'When was the last time this relationship brought you to tears, and why?', '¿Cuándo fue la última vez que esta relación te hizo llorar, y por qué?'),
('lovers', 3, 'What do you believe about commitment that not everyone would agree with?', '¿Qué crees sobre el compromiso con lo que no todos estarían de acuerdo?'),
('lovers', 3, 'What is a way you have changed that I have not fully caught up to?', '¿En qué has cambiado que yo no he terminado de notar?'),
('lovers', 3, 'What is something you wish I knew about what you are carrying right now?', '¿Qué te gustaría que yo supiera de lo que estás cargando ahora mismo?'),
('lovers', 3, 'What did you need in your last relationship that nobody gave you?', '¿Qué necesitabas en tu última relación que nadie te dio?'),
('lovers', 3, 'What is something you regret not saying to me before it got harder to say?', '¿Qué te arrepientes de no haberme dicho antes de que se volviera más difícil decirlo?'),
('lovers', 3, 'What do you think makes a relationship actually safe to be honest in?', '¿Qué crees que hace que una relación sea un lugar seguro para ser honesto?'),
('lovers', 3, 'What is a part of your life right now that feels harder than you let me see?', '¿Qué parte de tu vida ahora mismo se siente más difícil de lo que me dejas ver?'),
-- Layer 4: raw, confessional
('lovers', 4, 'What is something you have never told me?', '¿Qué nunca me has contado?'),
('lovers', 4, 'What is a lie you told me to avoid a harder conversation?', '¿Qué mentira me dijiste para evitar una conversación más difícil?'),
('lovers', 4, 'What is a way you have doubted us that you never said out loud?', '¿Cómo has dudado de nosotros sin decirlo nunca en voz alta?'),
('lovers', 4, 'What is something you did that you have never apologized for?', '¿Qué hiciste por lo que nunca te disculpaste?'),
('lovers', 4, 'What is the real reason behind a fight we have never fully resolved?', '¿Cuál es la verdadera razón detrás de una pelea que nunca resolvimos del todo?'),
('lovers', 4, 'What is a boundary you have never actually enforced with me?', '¿Qué límite nunca has hecho valer de verdad conmigo?'),
('lovers', 4, 'What is something you are jealous of in me?', '¿Qué de mí te da envidia?'),
('lovers', 4, 'What is a version of yourself you buried to keep this relationship?', '¿Qué versión de ti enterraste para conservar esta relación?'),
('lovers', 4, 'What is the pettiest reason you have ever been upset with me?', '¿Cuál es la razón más insignificante por la que te has molestado conmigo?'),
('lovers', 4, 'What is a secret you are keeping to protect us?', '¿Qué secreto guardas para protegernos?'),
('lovers', 4, 'What is something about how we love each other that quietly bothers you?', '¿Qué de cómo nos queremos te molesta en silencio?'),
('lovers', 4, 'What is a way you have let me down that I never found out about?', '¿Cómo me has fallado sin que me haya enterado?'),
('lovers', 4, 'What do you think you are like to love, honestly?', '¿Cómo crees que eres de querer, honestamente?'),
('lovers', 4, 'What is something you have needed to say to me and never have?', '¿Qué has necesitado decirme y nunca lo has hecho?'),
('lovers', 4, 'What is a part of this relationship you are holding onto out of habit more than connection?', '¿Qué parte de esta relación conservas más por costumbre que por conexión real?'),
('lovers', 4, 'What is a part of yourself you have not shown me yet?', '¿Qué parte de ti todavía no me has mostrado?'),
('lovers', 4, 'What is the most embarrassing thing you have done to get my attention?', '¿Qué es lo más vergonzoso que has hecho para llamar mi atención?'),
('lovers', 4, 'What is something you are ashamed you needed from me?', '¿Qué te da vergüenza haber necesitado de mí?'),
('lovers', 4, 'What do you think loving me well actually costs you?', '¿Qué crees que te cuesta de verdad quererme bien?'),
('lovers', 4, 'What is a truth about us right now you have been avoiding saying out loud?', '¿Qué verdad sobre nosotros ahora mismo has evitado decir en voz alta?'),
-- Layer 5: soul, meaning, becoming
('lovers', 5, 'What do you want this relationship to have given you by the end of your life?', '¿Qué quieres que te haya dado esta relación al final de tu vida?'),
('lovers', 5, 'What do you think you are here to learn from loving me?', '¿Qué crees que estás aquí para aprender de amarme?'),
('lovers', 5, 'What is the truest thing loving me has taught you about yourself?', '¿Cuál es la verdad más grande que amarme te ha enseñado sobre ti?'),
('lovers', 5, 'What kind of partner do you want to become that you are not yet?', '¿Qué tipo de pareja quieres llegar a ser que todavía no eres?'),
('lovers', 5, 'What do you understand about love now that you did not before us?', '¿Qué entiendes del amor ahora que no entendías antes de nosotros?'),
('lovers', 5, 'What do you want to be known for by the person who knows you best?', '¿Por qué quieres ser conocido por la persona que mejor te conoce?'),
('lovers', 5, 'What is a belief about love you have had to unlearn?', '¿Qué creencia sobre el amor has tenido que desaprender?'),
('lovers', 5, 'What is something us being together has healed in you?', '¿Qué ha sanado en ti el estar juntos?'),
('lovers', 5, 'What do you hope this relationship means to us years from now?', '¿Qué esperas que signifique esta relación para nosotros dentro de muchos años?'),
('lovers', 5, 'What is worth protecting about how we love each other, no matter what?', '¿Qué de cómo nos queremos vale la pena proteger, pase lo que pase?'),
('lovers', 5, 'If our story were a book, what would this current chapter be called?', 'Si nuestra historia fuera un libro, ¿cómo se llamaría este capítulo actual?'),
('lovers', 5, 'What have you stopped needing this relationship to prove?', '¿Qué dejaste de necesitar que esta relación demostrara?'),
('lovers', 5, 'What do you owe the version of yourself who first believed in us?', '¿Qué le debes a la versión de ti que primero creyó en nosotros?'),
('lovers', 5, 'What is a fear about growing older with me that you are ready to name?', '¿Qué miedo sobre envejecer conmigo estás listo para nombrar?'),
('lovers', 5, 'What does a life of real love look like to you, specifically?', '¿Cómo se ve, en concreto, una vida de amor real para ti?'),
('lovers', 5, 'What did this past year teach you about who actually shows up for you?', '¿Qué te enseñó este último año sobre quién de verdad está presente para ti?'),
('lovers', 5, 'What do you want to build with me before life gets busier?', '¿Qué quieres construir conmigo antes de que la vida se ocupe más?'),
('lovers', 5, 'What is one thing you hope never changes about how we are together?', '¿Qué es lo único que esperas que nunca cambie de cómo somos juntos?'),
('lovers', 5, 'What is something you are grateful for about me that is hard to explain?', '¿Qué agradeces de mí que es difícil de explicar?'),
('lovers', 5, 'What do you want to have given me, in the end?', '¿Qué quieres haberme dado, al final?');
