-- Peelr September 2026 questions: STRANGERS
-- Theme: New Beginnings, a fresh start. Meeting someone new right as a new season starts.
-- Depth is capped at curious getting-to-know-you: never assumes a stranger has earned raw trauma disclosure.
INSERT INTO questions (deck, layer, text_en, text_es) VALUES
-- Layer 1: playful, first impressions, curious
('strangers', 1, 'What is the first thing you noticed about me?', '¿Qué fue lo primero que notaste de mí?'),
('strangers', 1, 'If we had met at the start of this year instead of now, what do you think would be different?', 'Si nos hubiéramos conocido al principio de este año en vez de ahora, ¿qué crees que sería diferente?'),
('strangers', 1, 'Based on nothing at all, what do you assume my week looks like?', 'Sin saber nada de mí, ¿cómo asumes que es mi semana?'),
('strangers', 1, 'Out of everyone here tonight, who do you think has the best story nobody has asked about yet?', 'De todos los que están aquí esta noche, ¿quién crees que tiene la mejor historia que nadie ha preguntado todavía?'),
('strangers', 1, 'If you had to guess one thing about me just by looking at me, what would you say?', 'Si tuvieras que adivinar algo de mí solo con mirarme, ¿qué dirías?'),
('strangers', 1, 'What do you assume I am like when I am comfortable around people?', '¿Cómo asumes que soy cuando me siento cómodo con la gente?'),
('strangers', 1, 'What is something new you are starting this fall that you would tell a total stranger?', '¿Qué cosa nueva estás empezando este otoño que le contarías a un completo desconocido?'),
('strangers', 1, 'If everyone here had to guess who is the most spontaneous, who would win?', 'Si todos aquí tuvieran que adivinar quién es el más espontáneo, ¿quién ganaría?'),
('strangers', 1, 'What do you think my go-to order at a coffee shop is?', '¿Cuál crees que es mi pedido de siempre en una cafetería?'),
('strangers', 1, 'Based on my energy, do you think I am an early riser or a night person?', 'Por mi energía, ¿crees que soy madrugador o noctámbulo?'),
('strangers', 1, 'What is something you did recently that you would do again tonight?', '¿Qué hiciste recientemente que volverías a hacer esta noche?'),
('strangers', 1, 'Who here would you guess is the best at keeping a secret?', '¿Quién de aquí crees que es mejor guardando un secreto?'),
('strangers', 1, 'What is the boldest thing you have done on a whim this year?', '¿Qué es lo más atrevido que has hecho por impulso este año?'),
('strangers', 1, 'What would you assume my ideal weekend looks like?', '¿Cómo asumes que sería mi fin de semana ideal?'),
('strangers', 1, 'What is one thing you are hoping changes for you this fall?', '¿Qué es lo único que esperas que cambie para ti este otoño?'),
('strangers', 1, 'If this whole room had to vote on who seems the most interesting, who would you guess wins?', 'Si toda esta sala tuviera que votar por quién parece el más interesante, ¿quién crees que ganaría?'),
('strangers', 1, 'What do you think is the first thing people usually get wrong about you?', '¿Cuál crees que es lo primero que la gente suele malinterpretar de ti?'),
('strangers', 1, 'What is something you are genuinely excited about right now?', '¿Qué te emociona de verdad ahora mismo?'),
('strangers', 1, 'What are you hoping this next season of your life looks like?', '¿Cómo esperas que se vea esta próxima temporada de tu vida?'),
('strangers', 1, 'What is one thing you think matters more than people give it credit for?', '¿Qué crees que importa más de lo que la gente reconoce?'),
-- Layer 2: curious, getting to know, warm
('strangers', 2, 'What is something about you that never comes up in a first conversation?', '¿Qué de ti nunca sale en una primera conversación?'),
('strangers', 2, 'What is something you are starting fresh on this fall?', '¿Qué estás empezando de cero este otoño?'),
('strangers', 2, 'What is a way you are different now than you were a year ago?', '¿En qué eres diferente ahora de quien eras hace un año?'),
('strangers', 2, 'What do you hope has changed about your life a year from tonight?', '¿Qué esperas que haya cambiado de tu vida dentro de un año a partir de esta noche?'),
('strangers', 2, 'What is the best decision you made recently?', '¿Cuál fue la mejor decisión que tomaste recientemente?'),
('strangers', 2, 'What do you want more of once things settle down?', '¿De qué quieres más cuando todo baje el ritmo?'),
('strangers', 2, 'What is a small risk you took recently, big or small?', '¿Qué riesgo tomaste recientemente, grande o pequeño?'),
('strangers', 2, 'When did you feel most like yourself recently?', '¿Cuándo te sentiste más tú mismo recientemente?'),
('strangers', 2, 'What is an accomplishment you never mention unless someone asks?', '¿Qué logro nunca mencionas a menos que alguien pregunte?'),
('strangers', 2, 'What is something you learned about yourself while doing something alone recently?', '¿Qué aprendiste de ti mismo haciendo algo en soledad recientemente?'),
('strangers', 2, 'What is the most common wrong guess people make about you at first?', '¿Cuál es la suposición equivocada más común que la gente hace de ti al principio?'),
('strangers', 2, 'What is an invitation you keep meaning to accept and have not?', '¿Qué invitación sigues pensando en aceptar y todavía no lo haces?'),
('strangers', 2, 'What are you hoping this fall brings you?', '¿Qué esperas que te traiga este otoño?'),
('strangers', 2, 'Of everyone you have met this year, who left the biggest impression on you?', 'De toda la gente que has conocido este año, ¿quién te dejó la impresión más grande?'),
('strangers', 2, 'What is something that used to matter to you that does not anymore?', '¿Qué solía importarte que ya no te importa?'),
('strangers', 2, 'Who are you actively trying to become this year?', '¿En quién estás intentando convertirte activamente este año?'),
('strangers', 2, 'What is a place that always sticks with you long after you leave it?', '¿Qué lugar se te queda grabado mucho después de haberlo dejado?'),
('strangers', 2, 'What have you not gotten around to that you keep meaning to?', '¿Qué no has alcanzado a hacer aunque siempre piensas hacerlo?'),
('strangers', 2, 'What is something you think people undervalue in a new connection?', '¿Qué crees que la gente subestima en una conexión nueva?'),
('strangers', 2, 'What do you think makes a room full of strangers actually turn into something real?', '¿Qué crees que hace que una sala llena de desconocidos se convierta en algo real?'),
-- Layer 3: curious perspective, beliefs, values
('strangers', 3, 'What did this year teach you about being on your own?', '¿Qué te enseñó este año sobre estar en soledad?'),
('strangers', 3, 'Who is someone you think about more than you would expect to?', '¿En quién piensas más de lo que esperarías?'),
('strangers', 3, 'What is something you were hoping for this year that has not come yet?', '¿Qué esperabas de este año que todavía no ha llegado?'),
('strangers', 3, 'What is a version of yourself you have been trying to leave behind?', '¿Qué versión de ti has estado intentando dejar atrás?'),
('strangers', 3, 'When did you last feel truly seen by someone, and what was that like?', '¿Cuándo te sentiste realmente visto por alguien por última vez, y cómo se sintió?'),
('strangers', 3, 'What do you think people get wrong about being honest with someone new?', '¿Qué crees que la gente malinterpreta sobre ser honesto con alguien nuevo?'),
('strangers', 3, 'Who is someone you stopped talking to that you sometimes wonder about?', '¿A quién dejaste de hablarle y a veces te preguntas cómo está?'),
('strangers', 3, 'What do you do when you feel like life is moving faster than you can keep up with?', '¿Qué haces cuando sientes que la vida avanza más rápido de lo que puedes seguirle el paso?'),
('strangers', 3, 'What do you think it actually takes to trust someone quickly?', '¿Qué crees que se necesita de verdad para confiar rápido en alguien?'),
('strangers', 3, 'What is something you want from a connection that you rarely say out loud?', '¿Qué quieres de una conexión que rara vez dices en voz alta?'),
('strangers', 3, 'What do you think it takes for a room of strangers to actually open up to each other?', '¿Qué crees que se necesita para que una sala de desconocidos de verdad se abra entre sí?'),
('strangers', 3, 'What is a belief you hold now that you did not a few years ago?', '¿Qué creencia tienes ahora que no tenías hace unos años?'),
('strangers', 3, 'What do you think makes someone worth getting to know?', '¿Qué crees que hace que valga la pena conocer a alguien?'),
('strangers', 3, 'What is something you want badly enough that you rarely say it out loud?', '¿Qué quieres tanto que rara vez lo dices en voz alta?'),
('strangers', 3, 'What is a part of yourself you are still trying to figure out?', '¿Qué parte de ti todavía intentas entender?'),
('strangers', 3, 'What is something you quietly need but have stopped expecting from people?', '¿Qué necesitas en silencio pero ya dejaste de esperar de la gente?'),
('strangers', 3, 'What would you want to know about someone in the first five minutes that most people never ask?', '¿Qué querrías saber de alguien en los primeros cinco minutos que la mayoría nunca pregunta?'),
('strangers', 3, 'What do you think honesty actually costs, in a good way?', '¿Qué crees que cuesta de verdad ser honesto, en el buen sentido?'),
('strangers', 3, 'Of everyone here, who do you think is the most different from their first impression?', 'De todos los que están aquí, ¿quién crees que es más distinto a su primera impresión?'),
('strangers', 3, 'What is something you are proud of that took you years to be able to say out loud?', '¿De qué estás orgulloso que te tomó años poder decir en voz alta?'),
-- Layer 4: honest self-assessment, aspiration
('strangers', 4, 'What is something you are proud of that most people would not guess about you?', '¿De qué estás orgulloso que la mayoría no adivinaría de ti?'),
('strangers', 4, 'What is a belief about yourself you are still working on believing?', '¿Qué creencia sobre ti mismo todavía estás trabajando en creerte?'),
('strangers', 4, 'What do you think you owe yourself that you keep putting off?', '¿Qué crees que te debes a ti mismo y sigues posponiendo?'),
('strangers', 4, 'What is the most honest answer to how this year has actually gone for you?', '¿Cuál es la respuesta más honesta a cómo te ha ido de verdad este año?'),
('strangers', 4, 'What is something you want to change about your life that you have not started yet?', '¿Qué quieres cambiar de tu vida que todavía no has empezado?'),
('strangers', 4, 'What do you think you are actually chasing right now, underneath everything else?', '¿Qué crees que estás persiguiendo de verdad ahora mismo, debajo de todo lo demás?'),
('strangers', 4, 'What is something you used to think you needed that you no longer do?', '¿Qué creías que necesitabas antes que ya no crees necesitar?'),
('strangers', 4, 'What is something you have gotten better at admitting to yourself?', '¿Qué te ha costado menos admitirte a ti mismo con el tiempo?'),
('strangers', 4, 'What do you think makes someone genuinely trustworthy, as far as you have seen?', '¿Qué crees que hace a alguien realmente confiable, por lo que has visto?'),
('strangers', 4, 'What is a fear about your future you rarely say out loud?', '¿Qué miedo sobre tu futuro rara vez dices en voz alta?'),
('strangers', 4, 'What is something you wish more people asked you about?', '¿Sobre qué desearías que más gente te preguntara?'),
('strangers', 4, 'What do you think this room would say about you after tonight, honestly?', '¿Qué crees que diría esta sala de ti después de esta noche, honestamente?'),
('strangers', 4, 'What do you think you need to stop tolerating in your life?', '¿Qué crees que necesitas dejar de tolerar en tu vida?'),
('strangers', 4, 'What is a moment you seriously considered a different path than the one you are on?', '¿En qué momento consideraste seriamente un camino distinto al que llevas?'),
('strangers', 4, 'What is something about your life right now you would only admit to someone new?', '¿Qué de tu vida ahora mismo solo admitirías ante alguien nuevo?'),
('strangers', 4, 'What is a compromise you made that you are still thinking about?', '¿Qué concesión hiciste que todavía sigues pensando?'),
('strangers', 4, 'What is the hardest part of showing up as yourself these days?', '¿Qué es lo más difícil de mostrarte tal como eres estos días?'),
('strangers', 4, 'What do you think you deserve that you rarely ask for?', '¿Qué crees que mereces y rara vez pides?'),
('strangers', 4, 'What is the most honest thing you have said to a total stranger?', '¿Cuál es la cosa más honesta que le has dicho a un completo desconocido?'),
('strangers', 4, 'What is a question you wish people asked you more often?', '¿Qué pregunta desearías que la gente te hiciera más seguido?'),
-- Layer 5: soul, meaning, becoming
('strangers', 5, 'What do you want this year to have meant when you look back on it?', '¿Qué quieres que haya significado este año cuando mires atrás?'),
('strangers', 5, 'What is something you know about yourself now that you could not have said a year ago?', '¿Qué sabes de ti ahora que no podrías haber dicho hace un año?'),
('strangers', 5, 'What is a change in you that has not caught up to how people still see you?', '¿Qué cambio en ti todavía no alcanza cómo la gente sigue viéndote?'),
('strangers', 5, 'What do you think you are here for, even if it sounds strange to say out loud?', '¿Para qué crees que estás aquí, aunque suene extraño decirlo en voz alta?'),
('strangers', 5, 'What is a belief you have earned entirely on your own?', '¿Qué creencia te has ganado completamente por tu cuenta?'),
('strangers', 5, 'If you only had one sentence to be understood, what would you want it to say?', 'Si solo tuvieras una frase para que te entendieran, ¿qué querrías que dijera?'),
('strangers', 5, 'What is a part of being human you have stopped fighting?', '¿Con qué parte de ser humano dejaste de luchar?'),
('strangers', 5, 'What would it actually look like for you to have lived well?', '¿Cómo se vería en realidad para ti haber vivido bien?'),
('strangers', 5, 'What is a question about your own life you still cannot answer?', '¿Qué pregunta sobre tu propia vida todavía no puedes responder?'),
('strangers', 5, 'What is something you used to look for in other people that you now give yourself?', '¿Qué solías buscar en otras personas que ahora te das a ti mismo?'),
('strangers', 5, 'What do you think you owe the version of yourself from a year ago?', '¿Qué crees que le debes a la versión de ti de hace un año?'),
('strangers', 5, 'What is something you had to live through to actually understand?', '¿Qué tuviste que vivir para realmente entenderlo?'),
('strangers', 5, 'What is the most generous thing you have ever done without telling anyone?', '¿Qué es lo más generoso que has hecho sin decírselo a nadie?'),
('strangers', 5, 'What would you tell someone standing where you were at your lowest, without explaining the whole story?', '¿Qué le dirías a alguien parado donde tú estuviste en tu peor momento, sin explicar toda la historia?'),
('strangers', 5, 'If this whole room is a chapter, what do you think it is called?', 'Si toda esta sala fuera un capítulo, ¿cómo crees que se llamaría?'),
('strangers', 5, 'What is something about your life you would keep even if it made things harder?', '¿Qué de tu vida conservarías aunque te complicara las cosas?'),
('strangers', 5, 'What is something good in your life you struggle to put into words?', '¿Qué cosa buena de tu vida te cuesta poner en palabras?'),
('strangers', 5, 'What is something about who you are that you want to protect as life changes?', '¿Qué de quién eres quieres proteger a medida que la vida cambia?'),
('strangers', 5, 'What is one thing you hope people remember about meeting you?', '¿Qué es lo único que esperas que la gente recuerde de haberte conocido?'),
('strangers', 5, 'What do you want to be different about you by next fall?', '¿Qué quieres que sea distinto en ti para el próximo otoño?');
