-- Peelr August 2026 questions: COWORKERS
-- Theme: End of Summer, before it's over. Summer is ending and we are still stuck here together.
INSERT INTO questions (deck, layer, text_en, text_es) VALUES
-- Layer 1: playful, workplace safe
('coworkers', 1, 'What is the best out of office message you have ever seen or written?', '¿Cuál es el mejor mensaje de ausencia que has visto o escrito?'),
('coworkers', 1, 'Who here took the best vacation this summer, and who is most bitter about it?', '¿Quién aquí tuvo las mejores vacaciones este verano, y a quién le dio más envidia?'),
('coworkers', 1, 'What did you actually do on your summer break that you never told anyone here?', '¿Qué hiciste de verdad en tus vacaciones de verano que nunca le contaste a nadie aquí?'),
('coworkers', 1, 'If this team got one more summer Friday, how are we spending it?', 'Si este equipo tuviera un viernes de verano más, ¿cómo lo pasamos?'),
('coworkers', 1, 'What is the most useless meeting you sat through this summer?', '¿Cuál fue la reunión más inútil que aguantaste este verano?'),
('coworkers', 1, 'Who on this team disappears fastest at five in the summer?', '¿Quién de este equipo desaparece más rápido a las cinco en verano?'),
('coworkers', 1, 'What is your honest rating of this summer at work out of ten?', '¿Qué nota honesta del uno al diez le pones a este verano en el trabajo?'),
('coworkers', 1, 'What is something you pretended to be busy with this August?', '¿Con qué fingiste estar ocupado este agosto?'),
('coworkers', 1, 'If our team went on a trip together, who is planning it and who is complaining?', 'Si nuestro equipo se fuera de viaje, ¿quién lo planea y quién se queja?'),
('coworkers', 1, 'What is the summer office snack that got everyone through?', '¿Cuál fue el snack de oficina que salvó a todos este verano?'),
('coworkers', 1, 'Who here is most likely to answer email from the beach?', '¿Quién aquí es más capaz de responder correos desde la playa?'),
('coworkers', 1, 'What is a work habit you picked up this summer that you are keeping?', '¿Qué costumbre de trabajo agarraste este verano que vas a conservar?'),
('coworkers', 1, 'If you could delete one recurring meeting before the fall, which one?', 'Si pudieras borrar una reunión recurrente antes del otoño, ¿cuál sería?'),
('coworkers', 1, 'What is the funniest thing that happened at work this summer?', '¿Qué fue lo más gracioso que pasó en el trabajo este verano?'),
('coworkers', 1, 'Who had the best desk setup or the best view this summer?', '¿Quién tuvo el mejor escritorio o la mejor vista este verano?'),
('coworkers', 1, 'What is something about this place in summer that you will actually miss?', '¿Qué de este lugar en verano vas a extrañar de verdad?'),
('coworkers', 1, 'What is the pettiest work thing that annoyed you these past few months?', '¿Cuál fue la tontería de trabajo más pequeña que te molestó estos meses?'),
('coworkers', 1, 'If you had one more week off right now, what are you doing with it?', 'Si tuvieras una semana libre más ahora mismo, ¿qué harías con ella?'),
('coworkers', 1, 'Who here is secretly counting down to the holidays already?', '¿Quién aquí ya está contando en secreto los días para las fiestas?'),
('coworkers', 1, 'What is one work thing you want to finish before summer officially ends?', '¿Qué cosa del trabajo quieres terminar antes de que el verano acabe oficialmente?'),
-- Layer 2: personal but professional
('coworkers', 2, 'What is something you got better at this summer that nobody noticed?', '¿En qué mejoraste este verano sin que nadie lo notara?'),
('coworkers', 2, 'What is a strength you see in me that I might not see in myself?', '¿Qué fortaleza ves en mí que yo tal vez no veo?'),
('coworkers', 2, 'What about your summer outside of work would surprise this team?', '¿Qué de tu verano fuera del trabajo sorprendería a este equipo?'),
('coworkers', 2, 'What is a project from these past months you are quietly proud of?', '¿De qué proyecto de estos meses estás orgulloso en silencio?'),
('coworkers', 2, 'What do you want to be doing differently by the end of this year?', '¿Qué quieres estar haciendo de otra forma para el final de este año?'),
('coworkers', 2, 'What is something you wanted to say in a meeting this summer but did not?', '¿Qué quisiste decir en una reunión este verano y no dijiste?'),
('coworkers', 2, 'What is a way this team helped you this summer that we probably do not realize?', '¿Cómo te ayudó este equipo este verano sin que probablemente nos diéramos cuenta?'),
('coworkers', 2, 'What is something you are working toward that has nothing to do with this job?', '¿Hacia qué estás trabajando que no tiene nada que ver con este empleo?'),
('coworkers', 2, 'When did you feel most useful here these past few months?', '¿Cuándo te sentiste más útil aquí en estos últimos meses?'),
('coworkers', 2, 'What do you wish people here knew about you beyond your job title?', '¿Qué te gustaría que la gente de aquí supiera de ti más allá de tu puesto?'),
('coworkers', 2, 'What is a way you have changed as a professional this year?', '¿En qué cambiaste como profesional este año?'),
('coworkers', 2, 'What are you dreading about the fall push?', '¿Qué te preocupa del empujón que viene en el otoño?'),
('coworkers', 2, 'What is a piece of feedback you got this summer that stuck with you?', '¿Qué comentario recibiste este verano que se te quedó grabado?'),
('coworkers', 2, 'What do you need from this team going into the busy season?', '¿Qué necesitas de este equipo de cara a la temporada ocupada?'),
('coworkers', 2, 'If you could only keep one part of your job, what would it be?', 'Si solo pudieras conservar una parte de tu trabajo, ¿cuál sería?'),
('coworkers', 2, 'What is a boundary you set at work this summer that helped?', '¿Qué límite pusiste en el trabajo este verano que te ayudó?'),
('coworkers', 2, 'What do you want out of the next twelve months here, honestly?', '¿Qué quieres de los próximos doce meses aquí, honestamente?'),
('coworkers', 2, 'What did you learn about how you work best this summer?', '¿Qué aprendiste este verano sobre cómo trabajas mejor?'),
('coworkers', 2, 'Who here made your summer at work easier, and have you told them?', '¿Quién aquí te hizo el verano de trabajo más fácil, y se lo has dicho?'),
('coworkers', 2, 'What is a win from these past months you never got credit for?', '¿Qué logro de estos meses nunca te reconocieron?'),
-- Layer 3: vulnerable
('coworkers', 3, 'What about work this summer wore you down more than you let on?', '¿Qué del trabajo este verano te desgastó más de lo que dejaste ver?'),
('coworkers', 3, 'When did you feel invisible here these past few months?', '¿Cuándo te sentiste invisible aquí en estos últimos meses?'),
('coworkers', 3, 'What is a fear you have about where your career is heading?', '¿Qué miedo tienes sobre hacia dónde va tu carrera?'),
('coworkers', 3, 'What have you been struggling with that you kept out of work entirely?', '¿Con qué has estado batallando que mantuviste completamente fuera del trabajo?'),
('coworkers', 3, 'What is a moment this summer you seriously thought about leaving?', '¿En qué momento de este verano pensaste seriamente en irte?'),
('coworkers', 3, 'What do you think this job is costing you?', '¿Qué crees que te está costando este trabajo?'),
('coworkers', 3, 'What is something you needed from a manager this year and never got?', '¿Qué necesitaste de un jefe este año y nunca recibiste?'),
('coworkers', 3, 'When did you last feel genuinely respected here?', '¿Cuándo te sentiste realmente respetado aquí por última vez?'),
('coworkers', 3, 'What is a version of your career you gave up on?', '¿Qué versión de tu carrera abandonaste?'),
('coworkers', 3, 'What are you insecure about at work that you cover well?', '¿Qué inseguridad tienes en el trabajo que disimulas bien?'),
('coworkers', 3, 'What is a mistake from this summer you are still replaying?', '¿Qué error de este verano sigues repasando en tu cabeza?'),
('coworkers', 3, 'What is a part of yourself you keep completely out of this building?', '¿Qué parte de ti mantienes totalmente fuera de este edificio?'),
('coworkers', 3, 'What is something about this team that quietly frustrates you?', '¿Qué de este equipo te frustra en silencio?'),
('coworkers', 3, 'When did you feel most alone in your work this summer?', '¿Cuándo te sentiste más solo en tu trabajo este verano?'),
('coworkers', 3, 'What do you want to be recognized for that you have never asked for?', '¿Por qué quieres que te reconozcan sin haberlo pedido nunca?'),
('coworkers', 3, 'What is a way work has changed you that you are not sure you like?', '¿En qué te ha cambiado el trabajo de una forma que no estás seguro de que te guste?'),
('coworkers', 3, 'What are you afraid people here assume about you?', '¿Qué temes que la gente de aquí asuma sobre ti?'),
('coworkers', 3, 'What have you been going through without telling anyone here?', '¿Qué has estado atravesando sin contárselo a nadie aquí?'),
('coworkers', 3, 'What is a comparison you make between yourself and someone here that hurts?', '¿Qué comparación haces entre tú y alguien de aquí que te duele?'),
('coworkers', 3, 'What did you tell yourself this summer to get through the hard weeks?', '¿Qué te dijiste a ti mismo este verano para superar las semanas difíciles?'),
-- Layer 4: raw, confessional
('coworkers', 4, 'What is something about your work life you would never admit to anyone here?', '¿Qué de tu vida laboral nunca admitirías ante nadie aquí?'),
('coworkers', 4, 'What is a truth about this job you have been avoiding facing all summer?', '¿Qué verdad sobre este trabajo has evitado enfrentar todo el verano?'),
('coworkers', 4, 'Who here have you judged unfairly this year?', '¿A quién de aquí has juzgado injustamente este año?'),
('coworkers', 4, 'What is a mistake you made this year that nobody ever found out about?', '¿Qué error cometiste este año del que nadie se enteró?'),
('coworkers', 4, 'What do you resent about how things run here that you have never said?', '¿Qué te molesta de cómo funcionan las cosas aquí que nunca has dicho?'),
('coworkers', 4, 'What is a way you have not shown up for this team lately?', '¿De qué manera no has estado presente para este equipo últimamente?'),
('coworkers', 4, 'What is the loneliest part of your work life?', '¿Cuál es la parte más solitaria de tu vida laboral?'),
('coworkers', 4, 'What have you pretended to care about all summer?', '¿Qué has fingido que te importa todo el verano?'),
('coworkers', 4, 'What is a way this job has made you someone you did not want to be?', '¿Cómo te ha convertido este trabajo en alguien que no querías ser?'),
('coworkers', 4, 'What are you actually planning for the fall that nobody here knows about?', '¿Qué estás planeando de verdad para el otoño que nadie aquí sabe?'),
('coworkers', 4, 'When did you take credit or let credit slide in a way you should not have?', '¿Cuándo te llevaste un crédito o dejaste pasar uno de forma que no debiste?'),
('coworkers', 4, 'What about your life outside work are you hiding from this room?', '¿Qué de tu vida fuera del trabajo le escondes a esta sala?'),
('coworkers', 4, 'What is a way you have let yourself down professionally this year?', '¿Cómo te has fallado a ti mismo profesionalmente este año?'),
('coworkers', 4, 'What is the hardest thing you have gone through while still showing up here?', '¿Qué es lo más duro que has atravesado mientras seguías apareciendo aquí?'),
('coworkers', 4, 'What have you wanted to say to someone here and never will?', '¿Qué has querido decirle a alguien de aquí y nunca dirás?'),
('coworkers', 4, 'What is a way you have been unfair to someone on this team this year?', '¿En qué has sido injusto con alguien de este equipo este año?'),
('coworkers', 4, 'What are you most afraid of being found out for at work?', '¿Qué es lo que más temes que descubran de ti en el trabajo?'),
('coworkers', 4, 'What is a compromise you made this year that you are not proud of?', '¿Qué concesión hiciste este año que no te enorgullece?'),
('coworkers', 4, 'What are you still angry about here that you act fine about?', '¿Sobre qué sigues enojado aquí aunque actúas como si nada?'),
('coworkers', 4, 'If nothing about this job changed by next summer, could you live with that?', 'Si nada de este trabajo cambiara para el próximo verano, ¿podrías vivir con eso?'),
-- Layer 5: soul, meaning
('coworkers', 5, 'What do you want this year of your working life to have added up to?', '¿A qué quieres que sume este año de tu vida laboral?'),
('coworkers', 5, 'What do you want your work to mean beyond a paycheck?', '¿Qué quieres que signifique tu trabajo más allá del sueldo?'),
('coworkers', 5, 'What did you learn about yourself this summer that will outlast this job?', '¿Qué aprendiste de ti este verano que va a durar más que este trabajo?'),
('coworkers', 5, 'What do you want people here to remember about working with you?', '¿Qué quieres que la gente de aquí recuerde de haber trabajado contigo?'),
('coworkers', 5, 'What is a version of your life you are quietly building toward?', '¿Qué versión de tu vida estás construyendo en silencio?'),
('coworkers', 5, 'What would you do if the money were already handled?', '¿Qué harías si el dinero ya estuviera resuelto?'),
('coworkers', 5, 'What has this job taught you that you are actually grateful for?', '¿Qué te ha enseñado este trabajo que de verdad agradeces?'),
('coworkers', 5, 'What do you owe the version of yourself who took this job?', '¿Qué le debes a la versión de ti que aceptó este trabajo?'),
('coworkers', 5, 'What is a belief about work you have had to let go of?', '¿Qué creencia sobre el trabajo has tenido que soltar?'),
('coworkers', 5, 'What does a career well spent look like to you, specifically?', '¿Cómo se ve, en concreto, una carrera bien vivida para ti?'),
('coworkers', 5, 'What is a fear about your future you are ready to stop letting decide things?', '¿Qué miedo sobre tu futuro estás listo para dejar de permitir que decida por ti?'),
('coworkers', 5, 'What do you understand about yourself now that you did not in January?', '¿Qué entiendes de ti ahora que no entendías en enero?'),
('coworkers', 5, 'What are you becoming that this job cannot contain?', '¿En qué te estás convirtiendo que este trabajo no puede contener?'),
('coworkers', 5, 'What is a question about your path you are living inside of right now?', '¿En qué pregunta sobre tu camino estás viviendo ahora mismo?'),
('coworkers', 5, 'What have you stopped needing this job to give you?', '¿Qué dejaste de necesitar que este trabajo te diera?'),
('coworkers', 5, 'What is worth protecting about who you are, no matter where you end up working?', '¿Qué vale la pena proteger de quien eres, sin importar dónde termines trabajando?'),
('coworkers', 5, 'What would you tell someone starting where you started?', '¿Qué le dirías a alguien que empieza donde tú empezaste?'),
('coworkers', 5, 'What do you want to be different about your work life by next summer?', '¿Qué quieres que sea distinto en tu vida laboral para el próximo verano?'),
('coworkers', 5, 'What is something in your career you are ready to leave behind with this season?', '¿Qué de tu carrera estás listo para dejar atrás con esta temporada?'),
('coworkers', 5, 'What about this stretch of your working life will you be glad you lived through?', '¿Qué de esta etapa de tu vida laboral te alegrará haber vivido?');
