-- Peelr August 2026 questions: FAMILY
-- Theme: End of Summer, before it's over. The end of summer visit, the long drive home, before everyone goes back to their lives.
INSERT INTO questions (deck, layer, text_en, text_es) VALUES
-- Layer 1: playful, light, warm
('family', 1, 'What is the best thing that happened at a family gathering this summer?', '¿Qué fue lo mejor que pasó en una reunión familiar este verano?'),
('family', 1, 'Who in this family is the worst passenger on a long drive?', '¿Quién de esta familia es el peor copiloto en un viaje largo?'),
('family', 1, 'What is the family summer tradition you would never let go of?', '¿Qué tradición familiar de verano nunca dejarías morir?'),
('family', 1, 'What do you always forget to pack, and who always saves you?', '¿Qué se te olvida empacar siempre, y quién siempre te salva?'),
('family', 1, 'Who took the most photos this summer and who refused every single one?', '¿Quién tomó más fotos este verano y quién se negó a todas?'),
('family', 1, 'What is a summer meal from this family you would eat right now?', '¿Qué comida de verano de esta familia te comerías ahora mismo?'),
('family', 1, 'If we planned one last trip before everyone goes back, who is in charge?', 'Si planeáramos un último viaje antes de que todos regresen, ¿quién manda?'),
('family', 1, 'What is the funniest argument this family had this summer?', '¿Cuál fue la discusión más graciosa de esta familia este verano?'),
('family', 1, 'Who in this family aged best this year, and who is going to disagree?', '¿Quién de esta familia se ve mejor este año, y quién va a discutirlo?'),
('family', 1, 'What is a story from this summer that is going to get retold every year?', '¿Qué historia de este verano se va a contar todos los años?'),
('family', 1, 'What song always plays in this family car, and who controls it?', '¿Qué canción suena siempre en el carro de esta familia, y quién la controla?'),
('family', 1, 'Who is most likely to fall asleep first on the drive home?', '¿Quién se duerme primero en el camino de vuelta a casa?'),
('family', 1, 'What is something you did this summer that you have not told the family about?', '¿Qué hiciste este verano que no le has contado a la familia?'),
('family', 1, 'If this summer got one family photo, who is standing where?', 'Si este verano tuviera una sola foto familiar, ¿quién se para dónde?'),
('family', 1, 'What is the pettiest thing that annoyed you at a family event this summer?', '¿Cuál fue la tontería más pequeña que te molestó en un evento familiar este verano?'),
('family', 1, 'Who in this family gives the best advice and who gives the worst?', '¿Quién de esta familia da los mejores consejos y quién los peores?'),
('family', 1, 'What is something about being home this summer that you actually loved?', '¿Qué de estar en casa este verano te encantó de verdad?'),
('family', 1, 'What is a summer memory from when you were a kid that came back to you this year?', '¿Qué recuerdo de verano de tu infancia te volvió este año?'),
('family', 1, 'Who is the hardest to reach on the phone once everyone goes back?', '¿A quién es más difícil localizar por teléfono cuando todos regresan?'),
('family', 1, 'What is one thing you want us to do together before summer is over?', '¿Qué es lo único que quieres que hagamos juntos antes de que acabe el verano?'),
-- Layer 2: personal, warm
('family', 2, 'What did being together this summer give you that you needed?', '¿Qué te dio estar juntos este verano que necesitabas?'),
('family', 2, 'What is something about your life right now that you have not shared with this family?', '¿Qué de tu vida ahora mismo no has compartido con esta familia?'),
('family', 2, 'What do you want more of from us before everyone goes back?', '¿Qué quieres más de nosotros antes de que todos regresen?'),
('family', 2, 'What is a way you have changed this year that you hope we noticed?', '¿En qué cambiaste este año que esperas que hayamos notado?'),
('family', 2, 'What are you dreading about everyone going back to their own lives?', '¿Qué te pesa de que cada quien vuelva a su propia vida?'),
('family', 2, 'What are you proud of that you have never brought up at this table?', '¿De qué estás orgulloso y nunca lo has mencionado en esta mesa?'),
('family', 2, 'What is a moment from this summer with us that you will keep?', '¿Qué momento de este verano con nosotros vas a guardar?'),
('family', 2, 'What do you need from this family that you have never asked for?', '¿Qué necesitas de esta familia que nunca has pedido?'),
('family', 2, 'What is something you wish we did more of when we are together?', '¿Qué desearías que hiciéramos más cuando estamos juntos?'),
('family', 2, 'When did you feel most at home this summer?', '¿Cuándo te sentiste más en casa este verano?'),
('family', 2, 'What is something about this family you hope never changes?', '¿Qué de esta familia esperas que nunca cambie?'),
('family', 2, 'What is a way one of us surprised you this summer?', '¿Cómo te sorprendió alguno de nosotros este verano?'),
('family', 2, 'What is something you have wanted to tell us all summer?', '¿Qué has querido decirnos durante todo el verano?'),
('family', 2, 'What are you carrying into fall that you would rather set down here?', '¿Qué llevas al otoño que preferirías soltar aquí?'),
('family', 2, 'What do you appreciate about this family that you rarely say out loud?', '¿Qué valoras de esta familia que casi nunca dices en voz alta?'),
('family', 2, 'What did you learn about yourself while being home this summer?', '¿Qué aprendiste de ti mientras estabas en casa este verano?'),
('family', 2, 'What is a way you want to be different by the next time we are all together?', '¿En qué quieres ser diferente para la próxima vez que estemos todos juntos?'),
('family', 2, 'What is something you would want us to ask you about more often?', '¿Sobre qué te gustaría que te preguntáramos más seguido?'),
('family', 2, 'Who in this family do you not thank enough?', '¿A quién de esta familia no le agradeces lo suficiente?'),
('family', 2, 'What is your honest answer to how this year has actually been for you?', '¿Cuál es tu respuesta honesta sobre cómo te ha ido de verdad este año?'),
-- Layer 3: vulnerable, past, fears
('family', 3, 'What is something you needed from this family this summer and did not ask for?', '¿Qué necesitaste de esta familia este verano y no pediste?'),
('family', 3, 'When did you feel most alone in this family, even surrounded by us?', '¿Cuándo te sentiste más solo en esta familia, incluso rodeado de nosotros?'),
('family', 3, 'What is a fear you have about this family as we all get older?', '¿Qué miedo tienes sobre esta familia a medida que todos envejecemos?'),
('family', 3, 'What have you been going through that you kept from us on purpose?', '¿Qué has estado atravesando que nos ocultaste a propósito?'),
('family', 3, 'What is a memory from your childhood summers that still affects you?', '¿Qué recuerdo de los veranos de tu infancia todavía te afecta?'),
('family', 3, 'What do you worry about when you think about the years ahead for us?', '¿Qué te preocupa cuando piensas en los años que nos quedan por delante?'),
('family', 3, 'What is a part of yourself you have never fully shown this family?', '¿Qué parte de ti nunca le has mostrado del todo a esta familia?'),
('family', 3, 'What is something you wish this family knew how to talk about?', '¿De qué desearías que esta familia supiera hablar?'),
('family', 3, 'When did you last feel truly seen by someone at this table?', '¿Cuándo te sentiste realmente visto por alguien de esta mesa por última vez?'),
('family', 3, 'What is something you have never told your parents or your children?', '¿Qué nunca les has dicho a tus padres o a tus hijos?'),
('family', 3, 'What is a way this family shaped how you love people?', '¿Cómo formó esta familia la manera en que amas a la gente?'),
('family', 3, 'What are you afraid of losing before you are ready?', '¿Qué temes perder antes de estar preparado?'),
('family', 3, 'What is something about being home that is harder than it looks?', '¿Qué de estar en casa es más difícil de lo que parece?'),
('family', 3, 'What did you need at ten years old that nobody in this family gave you?', '¿Qué necesitabas a los diez años que nadie en esta familia te dio?'),
('family', 3, 'What is a distance between two of us that you feel and never name?', '¿Qué distancia entre dos de nosotros sientes y nunca nombras?'),
('family', 3, 'What have you forgiven this family for without ever saying so?', '¿Qué le has perdonado a esta familia sin decirlo nunca?'),
('family', 3, 'When did you last cry about something to do with us?', '¿Cuándo lloraste por última vez por algo relacionado con nosotros?'),
('family', 3, 'What is a way you are still trying to earn something from this family?', '¿Cómo sigues tratando de ganarte algo de esta familia?'),
('family', 3, 'What is something you want to say before another year goes by?', '¿Qué quieres decir antes de que pase otro año?'),
('family', 3, 'What is a goodbye at the end of a summer that you never got over?', '¿Qué despedida al final de un verano nunca superaste?'),
-- Layer 4: raw, confessional
('family', 4, 'What is an old hurt between us you are ready to put down before everyone leaves?', '¿Qué herida vieja entre nosotros estás listo para soltar antes de que todos se vayan?'),
('family', 4, 'What is something you have never forgiven someone here for?', '¿Qué es lo que nunca le has perdonado a alguien de aquí?'),
('family', 4, 'What is an apology you are still waiting to give or receive before everyone goes back?', '¿Qué disculpa sigues esperando dar o recibir antes de que todos regresen?'),
('family', 4, 'What is a truth about this family that we all avoid saying out loud?', '¿Qué verdad sobre esta familia evitamos todos decir en voz alta?'),
('family', 4, 'What is something you did that this family never found out about?', '¿Qué hiciste que esta familia nunca supo?'),
('family', 4, 'What is a way you have failed someone in this room?', '¿Cómo le has fallado a alguien en esta sala?'),
('family', 4, 'What is a pattern in this family you are trying to stop with you?', '¿Qué patrón de esta familia intentas que termine contigo?'),
('family', 4, 'What is something you resent that you have carried for years?', '¿Qué resentimiento has cargado durante años?'),
('family', 4, 'When did you feel abandoned by the people who were supposed to be there?', '¿Cuándo te sentiste abandonado por las personas que debían estar ahí?'),
('family', 4, 'What is a secret you have kept to protect someone here?', '¿Qué secreto has guardado para proteger a alguien de aquí?'),
('family', 4, 'What is the hardest thing about the way we love each other?', '¿Qué es lo más difícil de la forma en que nos queremos?'),
('family', 4, 'What have you needed to grieve about this family and never let yourself?', '¿Qué has necesitado llorar sobre esta familia y nunca te permitiste?'),
('family', 4, 'What is a way you have been the hardest person in this family to love?', '¿Cómo has sido la persona más difícil de querer en esta familia?'),
('family', 4, 'What have you been afraid to say at this table all summer?', '¿Qué has tenido miedo de decir en esta mesa todo el verano?'),
('family', 4, 'What would you say to someone here if you knew it was the last chance?', '¿Qué le dirías a alguien de aquí si supieras que es la última oportunidad?'),
('family', 4, 'What is a way this family disappointed you that you have never named?', '¿Cómo te decepcionó esta familia de una forma que nunca nombraste?'),
('family', 4, 'What about your life have you kept hidden because of what we would say?', '¿Qué de tu vida has mantenido escondido por lo que diríamos?'),
('family', 4, 'What is a regret you have about how you have shown up as a parent, a child, or a sibling?', '¿Qué te arrepientes de cómo has estado presente como padre, hijo o hermano?'),
('family', 4, 'What are you still angry about that you pretend is settled?', '¿Sobre qué sigues enojado aunque finges que ya está resuelto?'),
('family', 4, 'If we are exactly like this next summer, could you live with that?', 'Si el próximo verano fuéramos exactamente así, ¿podrías vivir con eso?'),
-- Layer 5: soul, meaning, legacy
('family', 5, 'What do you want this family to have meant when your life is looked back on?', '¿Qué quieres que haya significado esta familia cuando se mire tu vida en retrospectiva?'),
('family', 5, 'What do you hope gets passed down from this family, and what do you hope stops?', '¿Qué esperas que se herede de esta familia, y qué esperas que se detenga?'),
('family', 5, 'What did this summer together teach you about what matters?', '¿Qué te enseñó este verano juntos sobre lo que importa?'),
('family', 5, 'What is the truest thing you know about the people in this room?', '¿Cuál es la verdad más cierta que sabes sobre la gente de esta sala?'),
('family', 5, 'What do you want us to say about you when we tell your story?', '¿Qué quieres que digamos de ti cuando contemos tu historia?'),
('family', 5, 'What do you understand about your parents now that you could not have before?', '¿Qué entiendes de tus padres ahora que antes no podías?'),
('family', 5, 'What is a way one of us changed the direction of your life?', '¿Cómo cambió alguno de nosotros el rumbo de tu vida?'),
('family', 5, 'What do you hope this family looks like in twenty years?', '¿Cómo esperas que sea esta familia en veinte años?'),
('family', 5, 'What have you made peace with about this family that used to break your heart?', '¿Con qué de esta familia hiciste las paces que antes te rompía el corazón?'),
('family', 5, 'What is something worth protecting about us no matter what comes?', '¿Qué de nosotros vale la pena proteger sin importar lo que venga?'),
('family', 5, 'What do you owe the version of yourself who grew up in this family?', '¿Qué le debes a la versión de ti que creció en esta familia?'),
('family', 5, 'What is a fear you are ready to lay down before the year ends?', '¿Qué miedo estás listo para soltar antes de que acabe el año?'),
('family', 5, 'What is a chapter of your life that is quietly ending as this summer does?', '¿Qué capítulo de tu vida se cierra en silencio mientras acaba este verano?'),
('family', 5, 'What have these weeks together given you that you did not know you needed?', '¿Qué te dieron estas semanas juntos que no sabías que necesitabas?'),
('family', 5, 'What is a lesson from this family you have had to unlearn?', '¿Qué lección de esta familia has tenido que desaprender?'),
('family', 5, 'What do you want the youngest person here to know about love?', '¿Qué quieres que la persona más joven de aquí sepa sobre el amor?'),
('family', 5, 'What part of this family do you carry with you wherever you go?', '¿Qué parte de esta familia llevas contigo a donde vayas?'),
('family', 5, 'What is something you want to build with us before it is too late?', '¿Qué quieres construir con nosotros antes de que sea tarde?'),
('family', 5, 'What are you grateful for about being from this family in a way that is hard to explain?', '¿Qué agradeces de ser de esta familia de una forma difícil de explicar?'),
('family', 5, 'What would you want to have said if this were the last summer we all had?', '¿Qué te gustaría haber dicho si este fuera el último verano que tuviéramos todos?');
