-- Peelr August 2026 questions: FRIENDS
-- Theme: End of Summer, before it's over. The last trip, the group chat, one more night out before everyone scatters.
INSERT INTO questions (deck, layer, text_en, text_es) VALUES
-- Layer 1: playful, light, group energy
('friends', 1, 'What is the best night this group had all summer?', '¿Cuál fue la mejor noche que tuvo este grupo en todo el verano?'),
('friends', 1, 'If we planned one last trip before the season ends, who is organizing it and who is showing up late?', 'Si planeáramos un último viaje antes de que acabe la temporada, ¿quién lo organiza y quién llega tarde?'),
('friends', 1, 'What is the most unhinged thing that happened in the group chat this summer?', '¿Qué fue lo más descabellado que pasó en el chat del grupo este verano?'),
('friends', 1, 'Who here had the best summer, and who is going to argue about it?', '¿Quién aquí tuvo el mejor verano, y quién va a discutirlo?'),
('friends', 1, 'If our summer got one group photo on a billboard, which one are we using?', 'Si nuestro verano tuviera una foto de grupo en un cartel gigante, ¿cuál usaríamos?'),
('friends', 1, 'What is a summer plan we talked about constantly and never actually did?', '¿Qué plan de verano mencionamos mil veces y nunca hicimos?'),
('friends', 1, 'Who in this group is most likely to disappear once everyone gets busy again?', '¿Quién de este grupo va a desaparecer apenas todos se ocupen otra vez?'),
('friends', 1, 'What is the funniest thing that happened to you this summer?', '¿Qué fue lo más gracioso que te pasó este verano?'),
('friends', 1, 'If we had one more night out, where are we going and who is driving?', 'Si tuviéramos una salida más, ¿a dónde vamos y quién maneja?'),
('friends', 1, 'What song is always going to sound like this summer to all of us?', '¿Qué canción va a sonar siempre como este verano para todos nosotros?'),
('friends', 1, 'Who made the most questionable decision this summer, and are we allowed to bring it up?', '¿Quién tomó la decisión más cuestionable este verano, y podemos mencionarla?'),
('friends', 1, 'What is something you did this summer that you would never post?', '¿Qué hiciste este verano que nunca publicarías?'),
('friends', 1, 'If this summer had an award show for this group, what award is each of us winning?', 'Si este verano tuviera una premiación para este grupo, ¿qué premio gana cada uno?'),
('friends', 1, 'What is the pettiest thing you were annoyed about this summer?', '¿Cuál fue la tontería más pequeña que te molestó este verano?'),
('friends', 1, 'Who in this group gives the worst summer advice?', '¿Quién de este grupo da los peores consejos de verano?'),
('friends', 1, 'What is the best thing you ate this summer and where was it?', '¿Qué es lo mejor que comiste este verano y dónde fue?'),
('friends', 1, 'If we could redo one day from this summer, which day are we picking?', 'Si pudiéramos repetir un día de este verano, ¿cuál elegimos?'),
('friends', 1, 'What is a running joke from this summer that needs to survive into fall?', '¿Qué chiste interno de este verano tiene que sobrevivir hasta el otoño?'),
('friends', 1, 'Who took the most photos this summer and who is never in any of them?', '¿Quién tomó más fotos este verano y quién no sale en ninguna?'),
('friends', 1, 'What is one thing you want us all to do together before summer is over?', '¿Qué es lo único que quieres que hagamos todos juntos antes de que acabe el verano?'),
-- Layer 2: personal, warm
('friends', 2, 'What did this summer give you that you needed more than you realized?', '¿Qué te dio este verano que necesitabas más de lo que creías?'),
('friends', 2, 'What have you been going through that you kept out of the group chat?', '¿Qué has estado pasando que dejaste fuera del chat del grupo?'),
('friends', 2, 'Who in this group made your summer better, and do they know it?', '¿Quién de este grupo mejoró tu verano, y lo sabe?'),
('friends', 2, 'What is a way you have changed since June that you are happy about?', '¿En qué cambiaste desde junio que te gusta?'),
('friends', 2, 'What are you dreading about everything going back to normal?', '¿Qué te da pereza de que todo vuelva a la normalidad?'),
('friends', 2, 'What is something you wish we did more of this summer?', '¿Qué te hubiera gustado que hiciéramos más este verano?'),
('friends', 2, 'What is a moment from these months you know you will keep?', '¿Qué momento de estos meses sabes que vas a guardar?'),
('friends', 2, 'What do you need from us once everyone scatters again?', '¿Qué necesitas de nosotros cuando todos se dispersen otra vez?'),
('friends', 2, 'What is something you have been quietly proud of this summer?', '¿De qué has estado orgulloso en silencio este verano?'),
('friends', 2, 'When did you feel most like yourself these past few months?', '¿Cuándo te sentiste más tú mismo estos últimos meses?'),
('friends', 2, 'What is something about this friend group you do not want to lose?', '¿Qué de este grupo de amigos no quieres perder?'),
('friends', 2, 'What did you learn about what you need from your friends this summer?', '¿Qué aprendiste este verano sobre lo que necesitas de tus amigos?'),
('friends', 2, 'What is a plan for the rest of the year you are actually excited about?', '¿Qué plan para el resto del año te emociona de verdad?'),
('friends', 2, 'What is something you meant to tell one of us all summer?', '¿Qué quisiste decirle a alguien de nosotros durante todo el verano?'),
('friends', 2, 'Who in this group do you not thank enough?', '¿A quién de este grupo no le agradeces lo suficiente?'),
('friends', 2, 'What is something you said no to this summer that you were proud of?', '¿A qué le dijiste que no este verano y te sentiste orgulloso?'),
('friends', 2, 'What is a way this group showed up for you that you never named?', '¿Cómo estuvo este grupo para ti de una forma que nunca mencionaste?'),
('friends', 2, 'What are you carrying into fall that you would rather leave in August?', '¿Qué llevas al otoño que preferirías dejar en agosto?'),
('friends', 2, 'What is something you want to try before this year ends?', '¿Qué quieres intentar antes de que termine este año?'),
('friends', 2, 'What is your honest answer to how this summer actually went for you?', '¿Cuál es tu respuesta honesta sobre cómo te fue de verdad este verano?'),
-- Layer 3: vulnerable, past, fears
('friends', 3, 'What happened this summer that you made sound smaller than it actually was?', '¿Qué pasó este verano que hiciste sonar más pequeño de lo que fue?'),
('friends', 3, 'When did you feel left out of this group this summer?', '¿Cuándo te sentiste excluido de este grupo este verano?'),
('friends', 3, 'What is a fear about the next year that sits with you at night?', '¿Qué miedo sobre el próximo año se queda contigo de noche?'),
('friends', 3, 'What is something you needed from us this summer and did not ask for?', '¿Qué necesitaste de nosotros este verano y no pediste?'),
('friends', 3, 'What is the loneliest you felt these past few months?', '¿Cuál fue tu mayor soledad en estos últimos meses?'),
('friends', 3, 'What is a friendship that ended this year that you are still processing?', '¿Qué amistad terminó este año que todavía estás procesando?'),
('friends', 3, 'What have you been pretending to be fine about?', '¿Sobre qué has estado fingiendo que estás bien?'),
('friends', 3, 'When did you last feel genuinely understood by someone here?', '¿Cuándo te sentiste realmente entendido por alguien de aquí por última vez?'),
('friends', 3, 'What is a part of yourself you hide even from us?', '¿Qué parte de ti escondes incluso de nosotros?'),
('friends', 3, 'What were you hoping would happen this summer that did not?', '¿Qué esperabas que pasara este verano y no pasó?'),
('friends', 3, 'What is a way you have been struggling that nobody would recognize as struggling?', '¿De qué manera la has pasado mal sin que nadie lo reconozca como pasarla mal?'),
('friends', 3, 'What is something about your life right now that scares you?', '¿Qué de tu vida ahora mismo te da miedo?'),
('friends', 3, 'What is a version of yourself from this summer you are not proud of?', '¿Qué versión de ti de este verano no te enorgullece?'),
('friends', 3, 'When did you last cry, and did anyone know?', '¿Cuándo lloraste por última vez, y lo supo alguien?'),
('friends', 3, 'What is something you have never told this group?', '¿Qué nunca le has contado a este grupo?'),
('friends', 3, 'What is a fear you have about being truly known by us?', '¿Qué miedo tienes de que te conozcamos de verdad?'),
('friends', 3, 'What is something in this group you are jealous of?', '¿Qué de este grupo te da envidia?'),
('friends', 3, 'What did you need to hear this summer that nobody said?', '¿Qué necesitabas escuchar este verano que nadie dijo?'),
('friends', 3, 'What is something from your past that got louder for you this summer?', '¿Qué de tu pasado se hizo más fuerte para ti este verano?'),
('friends', 3, 'What are you afraid we would think differently of you for?', '¿Por qué temes que te veamos distinto?'),
-- Layer 4: raw, confessional
('friends', 4, 'What is something you did this summer that you have never confessed to anyone here?', '¿Qué hiciste este verano que nunca le has confesado a nadie aquí?'),
('friends', 4, 'Who in this group have you been quietly resentful of all summer?', '¿Con quién de este grupo has guardado resentimiento en silencio todo el verano?'),
('friends', 4, 'What is a truth about this friendship you have been avoiding saying all summer?', '¿Qué verdad sobre esta amistad has evitado decir todo el verano?'),
('friends', 4, 'What do you owe someone here an apology for before everyone scatters?', '¿Por qué le debes una disculpa a alguien de aquí antes de que todos se dispersen?'),
('friends', 4, 'What is the ugliest thought you have had this summer about someone you love?', '¿Cuál es el pensamiento más feo que tuviste este verano sobre alguien que quieres?'),
('friends', 4, 'What is a lie you told this group this summer?', '¿Qué mentira le dijiste a este grupo este verano?'),
('friends', 4, 'What are you ashamed of from these past few months?', '¿De qué te avergüenzas de estos últimos meses?'),
('friends', 4, 'Who did you let down this summer and never made it right with?', '¿A quién le fallaste este verano sin arreglarlo nunca?'),
('friends', 4, 'What have you needed to grieve this year and never let yourself?', '¿Qué has necesitado llorar este año y nunca te permitiste?'),
('friends', 4, 'What is a way you have not been a good friend lately?', '¿En qué no has sido un buen amigo últimamente?'),
('friends', 4, 'What is a regret from this summer that still gets to you?', '¿Qué arrepentimiento de este verano todavía te afecta?'),
('friends', 4, 'What are you still angry about that you claim to be over?', '¿Sobre qué sigues enojado aunque dices que ya lo superaste?'),
('friends', 4, 'How have you compared your life to ours in a way that did not go well?', '¿Cómo comparaste tu vida con la nuestra de una forma que no salió bien?'),
('friends', 4, 'What is a night from this summer you would take back?', '¿Qué noche de este verano te llevarías de vuelta?'),
('friends', 4, 'What are you afraid you will never fix about yourself?', '¿Qué temes no poder arreglar nunca de ti mismo?'),
('friends', 4, 'What have you been hiding from us all summer because you did not want the reaction?', '¿Qué nos has escondido todo el verano porque no querías la reacción?'),
('friends', 4, 'What is the hardest thing you have survived that we do not know about?', '¿Qué es lo más duro que has sobrevivido y no sabemos?'),
('friends', 4, 'What have you wanted to say to one of us all summer but held back?', '¿Qué has querido decirle a alguno de nosotros todo el verano pero te callaste?'),
('friends', 4, 'What is a promise you broke this summer that still bothers you?', '¿Qué promesa rompiste este verano que todavía te incomoda?'),
('friends', 4, 'What part of your life do you least want us to look at closely?', '¿Qué parte de tu vida es la que menos quieres que miremos de cerca?'),
-- Layer 5: soul, meaning, becoming
('friends', 5, 'What do you want this summer to have meant when you look back on it in ten years?', '¿Qué quieres que haya significado este verano cuando lo mires en diez años?'),
('friends', 5, 'What is the truest thing you know about who you are becoming?', '¿Cuál es la verdad más cierta sobre en quién te estás convirtiendo?'),
('friends', 5, 'What do you hope is different about all of us by next summer?', '¿Qué esperas que sea distinto en todos nosotros para el próximo verano?'),
('friends', 5, 'What is something you are today because of the people in this room?', '¿Qué eres hoy gracias a la gente de esta sala?'),
('friends', 5, 'What did you outgrow this summer that you have not announced to anyone?', '¿Qué dejaste atrás este verano sin anunciárselo a nadie?'),
('friends', 5, 'What is the closest thing you have to a personal philosophy right now?', '¿Qué es lo más cercano que tienes a una filosofía personal ahora mismo?'),
('friends', 5, 'What is something this group gave you that you could not have gotten anywhere else?', '¿Qué te dio este grupo que no habrías conseguido en ningún otro lado?'),
('friends', 5, 'What kind of friend do you want to be by the time we are all old?', '¿Qué clase de amigo quieres ser cuando todos seamos viejos?'),
('friends', 5, 'What is worth protecting about this group no matter what changes?', '¿Qué vale la pena proteger de este grupo sin importar lo que cambie?'),
('friends', 5, 'What is a promise you would make to this group before everyone scatters?', '¿Qué promesa le harías a este grupo antes de que todos se dispersen?'),
('friends', 5, 'What do you think brought us together, if you really think about it?', '¿Qué crees que nos unió, si lo piensas de verdad?'),
('friends', 5, 'What do you want said about you by the people who know you best?', '¿Qué quieres que digan de ti las personas que mejor te conocen?'),
('friends', 5, 'What is something you have made peace with that used to break you?', '¿Con qué hiciste las paces que antes te destrozaba?'),
('friends', 5, 'What is something you have survived that made you better at being a friend?', '¿Qué has sobrevivido que te hizo mejor amigo?'),
('friends', 5, 'What is the hardest lesson this year taught you that you are glad you learned?', '¿Cuál fue la lección más dura de este año que te alegra haber aprendido?'),
('friends', 5, 'What would you tell one of us if this were the last summer we all had together?', '¿Qué le dirías a uno de nosotros si este fuera el último verano que pasamos juntos?'),
('friends', 5, 'What do you hope we are still doing together twenty years from now?', '¿Qué esperas que sigamos haciendo juntos dentro de veinte años?'),
('friends', 5, 'What is something you believe about people that this group proved to you?', '¿Qué crees sobre la gente que este grupo te demostró?'),
('friends', 5, 'What is a way you want to be braver before the year is out?', '¿Cómo quieres ser más valiente antes de que acabe el año?'),
('friends', 5, 'What would be lost in the world if this group had never happened?', '¿Qué se habría perdido el mundo si este grupo nunca hubiera existido?');
