-- Peelr August 2026 questions: LOVERS
-- Theme: End of Summer, before it's over. Flirty, a little urgent, the 2am questions.
INSERT INTO questions (deck, layer, text_en, text_es) VALUES
-- Layer 1: playful, flirty, light
('lovers', 1, 'What is the one summer night with me you would live again exactly as it happened?', '¿Cuál es la noche de verano conmigo que volverías a vivir exactamente igual?'),
('lovers', 1, 'If we had one more perfect summer day together, what are we doing from morning to midnight?', 'Si tuviéramos un día perfecto más de verano juntos, ¿qué hacemos desde la mañana hasta la medianoche?'),
('lovers', 1, 'When did I look best to you this summer?', '¿Cuándo te gusté más este verano?'),
('lovers', 1, 'What is your favorite photo of us from this summer and why that one?', '¿Cuál es tu foto favorita de nosotros este verano y por qué esa?'),
('lovers', 1, 'If summer ended tomorrow, what is the first thing you would want to do with me tonight?', 'Si el verano terminara mañana, ¿qué es lo primero que querrías hacer conmigo esta noche?'),
('lovers', 1, 'What song from this summer is going to sound like me for the rest of your life?', '¿Qué canción de este verano va a sonar como yo por el resto de tu vida?'),
('lovers', 1, 'Where did you want to kiss me this summer and did not?', '¿Dónde quisiste besarme este verano y no lo hiciste?'),
('lovers', 1, 'What is something small I did this summer that you have not stopped thinking about?', '¿Qué cosa pequeña hice este verano en la que no has dejado de pensar?'),
('lovers', 1, 'If we could disappear for one last weekend before fall, where are we going?', 'Si pudiéramos desaparecer un último fin de semana antes del otoño, ¿a dónde vamos?'),
('lovers', 1, 'What is your favorite thing about how I look right now, tonight?', '¿Qué es lo que más te gusta de cómo me veo ahora mismo, esta noche?'),
('lovers', 1, 'What summer plan did we never get around to that you still want?', '¿Qué plan de verano nunca cumplimos que todavía quieres?'),
('lovers', 1, 'If you had to describe our summer in one word, what is it?', 'Si tuvieras que describir nuestro verano en una palabra, ¿cuál es?'),
('lovers', 1, 'What is something you want to try with me before the weather turns?', '¿Qué quieres probar conmigo antes de que cambie el clima?'),
('lovers', 1, 'What was the best kiss of this summer and where were we?', '¿Cuál fue el mejor beso de este verano y dónde estábamos?'),
('lovers', 1, 'What is something I wear that you hope I keep wearing into fall?', '¿Qué me pongo que esperas que siga usando en el otoño?'),
('lovers', 1, 'If tonight was the last warm night of the year, how are we spending it?', 'Si esta fuera la última noche cálida del año, ¿cómo la pasamos?'),
('lovers', 1, 'What is the flirtiest thing you wanted to text me this summer but never sent?', '¿Cuál es el mensaje más coqueto que quisiste enviarme este verano y nunca mandaste?'),
('lovers', 1, 'What made you look at me this summer like it was the first time again?', '¿Qué hizo que me miraras este verano como si fuera la primera vez otra vez?'),
('lovers', 1, 'What is one summer memory of us you would put on a loop?', '¿Qué recuerdo nuestro de este verano pondrías en repetición?'),
('lovers', 1, 'What do you want more of from me before summer is over?', '¿Qué quieres más de mí antes de que termine el verano?'),
-- Layer 2: personal, warm, getting real
('lovers', 2, 'What did this summer show you about us that you did not know in June?', '¿Qué te mostró este verano sobre nosotros que no sabías en junio?'),
('lovers', 2, 'What is something you needed from me this summer that you never asked for?', '¿Qué necesitaste de mí este verano que nunca pediste?'),
('lovers', 2, 'When did you feel closest to me these past few months?', '¿Cuándo te sentiste más cerca de mí estos últimos meses?'),
('lovers', 2, 'What is a way I changed this summer that you noticed before I did?', '¿En qué cambié este verano que notaste antes que yo?'),
('lovers', 2, 'What about our life together do you not want to lose when things get busy again?', '¿Qué de nuestra vida juntos no quieres perder cuando todo se ponga ocupado otra vez?'),
('lovers', 2, 'What did you enjoy about me this summer that surprised you?', '¿Qué disfrutaste de mí este verano que te sorprendió?'),
('lovers', 2, 'What is a moment this summer you wish had lasted longer?', '¿Qué momento de este verano deseas que hubiera durado más?'),
('lovers', 2, 'What are you hoping we carry into fall from these months?', '¿Qué esperas que llevemos al otoño de estos meses?'),
('lovers', 2, 'What is something you have been meaning to tell me all summer?', '¿Qué has querido decirme todo el verano?'),
('lovers', 2, 'When did I make you feel most wanted this summer?', '¿Cuándo sentiste que más te deseaba este verano?'),
('lovers', 2, 'What is a habit we fell into this summer that you love?', '¿Qué costumbre agarramos este verano que te encanta?'),
('lovers', 2, 'What did you learn about what you need in a relationship these past few months?', '¿Qué aprendiste sobre lo que necesitas en una relación estos últimos meses?'),
('lovers', 2, 'What is something you have quietly admired about me lately?', '¿Qué has admirado de mí en silencio últimamente?'),
('lovers', 2, 'What part of this summer are you already nostalgic for?', '¿De qué parte de este verano ya sientes nostalgia?'),
('lovers', 2, 'What is a way we could be better to each other before the year turns?', '¿Cómo podríamos ser mejores el uno con el otro antes de que termine el año?'),
('lovers', 2, 'What did you not get enough of from me this summer?', '¿De qué no tuviste suficiente de mí este verano?'),
('lovers', 2, 'What is something you were afraid to bring up while things felt good?', '¿Qué tuviste miedo de mencionar mientras todo se sentía bien?'),
('lovers', 2, 'When did you feel most like a team with me this summer?', '¿Cuándo sentiste que éramos más equipo este verano?'),
('lovers', 2, 'What is a version of us from this summer you want to keep?', '¿Qué versión de nosotros de este verano quieres conservar?'),
('lovers', 2, 'What are you looking forward to about the two of us in the colder months?', '¿Qué esperas de los dos en los meses fríos?'),
-- Layer 3: vulnerable, past, fears
('lovers', 3, 'What is a fear about us that got quieter this summer, and one that got louder?', '¿Qué miedo sobre nosotros se calmó este verano, y cuál creció?'),
('lovers', 3, 'What is something from a past summer that still shapes how you love me?', '¿Qué de un verano pasado todavía influye en cómo me amas?'),
('lovers', 3, 'When did you feel alone with me this summer even while we were together?', '¿Cuándo te sentiste en soledad conmigo este verano aunque estuviéramos juntos?'),
('lovers', 3, 'What have you been carrying these past months that you did not want to put on me?', '¿Qué has estado cargando estos meses que no quisiste ponerme encima?'),
('lovers', 3, 'What is a doubt about us you have not said out loud?', '¿Qué duda sobre nosotros no has dicho en voz alta?'),
('lovers', 3, 'What is a summer in your past you are still trying to get over?', '¿Qué verano de tu pasado todavía intentas superar?'),
('lovers', 3, 'When were you most insecure about me this summer?', '¿Cuándo sentiste más inseguridad por mí este verano?'),
('lovers', 3, 'What is something you needed to hear from me these months and never did?', '¿Qué necesitabas escuchar de mí estos meses y nunca escuchaste?'),
('lovers', 3, 'What is a part of you this summer made harder to hide?', '¿Qué parte de ti se hizo más difícil de esconder este verano?'),
('lovers', 3, 'What are you afraid changes about us when the season does?', '¿Qué te da miedo que cambie entre nosotros cuando cambie la estación?'),
('lovers', 3, 'What is something you noticed about me this summer that worried you?', '¿Qué notaste de mí este verano que te preocupó?'),
('lovers', 3, 'What is a way you held back from me these last few months?', '¿Cómo te contuviste conmigo estos últimos meses?'),
('lovers', 3, 'What is the loneliest you have felt this year, and was I there?', '¿Cuál ha sido tu mayor soledad este año, y estuve yo ahí?'),
('lovers', 3, 'What is something you have forgiven me for this summer without telling me?', '¿Qué me has perdonado este verano sin decírmelo?'),
('lovers', 3, 'What do you need me to understand about how you have been lately?', '¿Qué necesitas que yo entienda sobre cómo has estado últimamente?'),
('lovers', 3, 'What is a conversation we keep almost having?', '¿Qué conversación seguimos casi teniendo?'),
('lovers', 3, 'When this summer did you wonder if we want the same things?', '¿Cuándo este verano te preguntaste si queríamos lo mismo?'),
('lovers', 3, 'What is something about your past you want to tell me before this year ends?', '¿Qué de tu pasado quieres contarme antes de que termine el año?'),
('lovers', 3, 'What is a promise to yourself you broke for me this summer?', '¿Qué promesa que te hiciste rompiste por mí este verano?'),
('lovers', 3, 'What are you scared to want from me?', '¿Qué te da miedo querer de mí?'),
-- Layer 4: raw, confessional
('lovers', 4, 'What is something you did or felt this summer that you have not confessed to me?', '¿Qué hiciste o sentiste este verano que no me has confesado?'),
('lovers', 4, 'When this summer did you think about leaving, even for a second?', '¿Cuándo este verano pensaste en irte, aunque fuera por un segundo?'),
('lovers', 4, 'What is the hardest truth about us you have been avoiding saying before summer ends?', '¿Cuál es la verdad más dura sobre nosotros que has evitado decir antes de que acabe el verano?'),
('lovers', 4, 'What is something you resented me for all summer and never named?', '¿Qué me reprochaste todo el verano y nunca nombraste?'),
('lovers', 4, 'Who or what did you think about this summer that you should not have?', '¿En quién o en qué pensaste este verano que no deberías?'),
('lovers', 4, 'What is a lie you told me these past few months, even a small one?', '¿Qué mentira me dijiste estos últimos meses, aunque fuera pequeña?'),
('lovers', 4, 'What have you needed to grieve about us this year and never let yourself?', '¿Qué has necesitado llorar sobre nosotros este año y nunca te permitiste?'),
('lovers', 4, 'What is the ugliest thought you have had about me this summer?', '¿Cuál es el pensamiento más feo que has tenido sobre mí este verano?'),
('lovers', 4, 'What still bothers you from this summer even though you told me you were over it?', '¿Qué te sigue molestando de este verano aunque me dijiste que ya lo habías superado?'),
('lovers', 4, 'When did I hurt you this summer in a way I never found out about?', '¿Cuándo te lastimé este verano sin que yo me enterara?'),
('lovers', 4, 'What is a part of yourself you gave up for this relationship this year?', '¿Qué parte de ti entregaste por esta relación este año?'),
('lovers', 4, 'What have you been hoping would change about me before this year is out?', '¿Qué has esperado que cambie de mí antes de que termine este año?'),
('lovers', 4, 'What is the loneliest thing about loving me?', '¿Qué es lo más solitario de amarme?'),
('lovers', 4, 'What did you compare us to this summer where we did not come out well?', '¿Con qué comparaste lo nuestro este verano y no salimos bien parados?'),
('lovers', 4, 'What is a boundary of yours I crossed this summer that you let slide?', '¿Qué límite tuyo crucé este verano y dejaste pasar?'),
('lovers', 4, 'What have you been pretending is fine all summer that is not?', '¿Qué has fingido todo el verano que está bien cuando no lo está?'),
('lovers', 4, 'What do you want from me that you are afraid to ask for because of what my answer might be?', '¿Qué quieres de mí que te da miedo pedir por lo que pueda responder?'),
('lovers', 4, 'What is a way you punished me quietly this summer instead of telling me?', '¿Cómo me castigaste en silencio este verano en vez de decírmelo?'),
('lovers', 4, 'What is a truth about your feelings for me that scares you?', '¿Qué verdad sobre lo que sientes por mí te asusta?'),
('lovers', 4, 'If nothing changed between us by next summer, could you live with that?', 'Si nada cambiara entre nosotros para el próximo verano, ¿podrías vivir con eso?'),
-- Layer 5: soul, meaning, becoming
('lovers', 5, 'What did loving me this summer teach you about who you are becoming?', '¿Qué te enseñó amarme este verano sobre quién estás llegando a ser?'),
('lovers', 5, 'What is the truest thing about us that this summer proved?', '¿Cuál es la verdad más cierta sobre nosotros que probó este verano?'),
('lovers', 5, 'What do you want our next summer to look like, and what has to change first?', '¿Cómo quieres que sea nuestro próximo verano, y qué tiene que cambiar primero?'),
('lovers', 5, 'What part of me do you hope you never stop reaching for?', '¿Qué parte de mí esperas nunca dejar de buscar?'),
('lovers', 5, 'What about this love do you know you will remember when you are old?', '¿Qué de este amor sabes que vas a recordar cuando seas mayor?'),
('lovers', 5, 'What is the version of us you are quietly building toward?', '¿Cuál es la versión de nosotros que estás construyendo en silencio?'),
('lovers', 5, 'What has this relationship asked of you this year that made you better?', '¿Qué te ha pedido esta relación este año que te hizo mejor?'),
('lovers', 5, 'What do you hope I understand about how you love, even if I never say it back the same way?', '¿Qué esperas que yo entienda sobre cómo amas, aunque nunca te lo devuelva igual?'),
('lovers', 5, 'What would you want the people who watched us this year to say about us?', '¿Qué te gustaría que dijeran de nosotros las personas que nos vieron este año?'),
('lovers', 5, 'What is a way I have changed the direction of your life?', '¿Cómo he cambiado el rumbo de tu vida?'),
('lovers', 5, 'What do you think the two of us are for?', '¿Para qué crees que existimos los dos?'),
('lovers', 5, 'What would you want me to know if this were our last summer?', '¿Qué querrías que yo supiera si este fuera nuestro último verano?'),
('lovers', 5, 'What have you stopped needing from me because you finally gave it to yourself?', '¿Qué has dejado de necesitar de mí porque por fin te lo diste tú?'),
('lovers', 5, 'What about us is worth protecting no matter what the next year brings?', '¿Qué de lo nuestro vale la pena proteger sin importar lo que traiga el próximo año?'),
('lovers', 5, 'What fear do you want to leave behind in this summer so we can go further?', '¿Qué miedo quieres dejar atrás en este verano para que lleguemos más lejos?'),
('lovers', 5, 'What do you hope our love looks like when neither of us is who we are now?', '¿Cómo esperas que sea nuestro amor cuando ninguno de los dos sea quien es ahora?'),
('lovers', 5, 'What is the most honest thing you can say about what I mean to you?', '¿Qué es lo más honesto que puedes decir sobre lo que significo para ti?'),
('lovers', 5, 'What have these months given you that you did not know you were missing?', '¿Qué te han dado estos meses que no sabías que te faltaba?'),
('lovers', 5, 'What is a promise you want to make before the season turns?', '¿Qué promesa quieres hacer antes de que cambie la estación?'),
('lovers', 5, 'When you picture the rest of your life, what does it feel like with me in it?', 'Cuando imaginas el resto de tu vida, ¿cómo se siente conmigo en ella?');
