-- Peelr August 2026 questions: STRANGERS
-- Theme: End of Summer, before it's over. Summer is not over yet: meeting someone, situationships, end of summer flings.
INSERT INTO questions (deck, layer, text_en, text_es) VALUES
-- Layer 1: playful, first impressions, flirty
('strangers', 1, 'What is the first thing you noticed about me tonight?', '¿Qué fue lo primero que notaste de mí esta noche?'),
('strangers', 1, 'If we had met at the start of this summer instead of now, what do you think would have happened?', 'Si nos hubiéramos conocido al principio de este verano en vez de ahora, ¿qué crees que habría pasado?'),
('strangers', 1, 'Based on nothing at all, what do you assume my summer looked like?', 'Sin saber nada de mí, ¿cómo asumes que fue mi verano?'),
('strangers', 1, 'What was the best night you had this summer, and would you have invited me?', '¿Cuál fue la mejor noche que tuviste este verano, y me habrías invitado?'),
('strangers', 1, 'If you had to guess my type just by looking at me, what would you say?', 'Si tuvieras que adivinar qué tipo de persona me gusta solo con mirarme, ¿qué dirías?'),
('strangers', 1, 'What do you assume I am like on a first date?', '¿Cómo asumes que soy en una primera cita?'),
('strangers', 1, 'Where were you the last time you had a genuinely perfect summer night?', '¿Dónde estabas la última vez que tuviste una noche de verano realmente perfecta?'),
('strangers', 1, 'If we ran into each other one more time before summer ends, where would it be?', 'Si nos encontráramos una vez más antes de que termine el verano, ¿dónde sería?'),
('strangers', 1, 'What do you think my summer soundtrack sounded like?', '¿Cómo crees que sonó la banda sonora de mi verano?'),
('strangers', 1, 'Based on my energy, do you think I am the one who texts first or the one who waits?', 'Por mi energía, ¿crees que soy quien escribe primero o quien espera?'),
('strangers', 1, 'What is something you did this summer that you would do again tonight?', '¿Qué hiciste este verano que volverías a hacer esta noche?'),
('strangers', 1, 'If you had to guess, what am I looking for right now?', 'Si tuvieras que adivinar, ¿qué estoy buscando ahora mismo?'),
('strangers', 1, 'What is the most spontaneous thing you did this summer?', '¿Qué es lo más espontáneo que hiciste este verano?'),
('strangers', 1, 'What would you assume my ideal end of summer weekend looks like?', '¿Cómo asumes que sería mi fin de semana ideal para cerrar el verano?'),
('strangers', 1, 'Do you think we would have been friends or trouble if we had met in June?', '¿Crees que habríamos sido amigos o problemas si nos hubiéramos conocido en junio?'),
('strangers', 1, 'What do you assume is my worst habit in a situationship?', '¿Cuál asumes que es mi peor costumbre en una relación sin nombre?'),
('strangers', 1, 'What is a summer fling you have had that was worth it?', '¿Qué romance de verano tuviste que valió la pena?'),
('strangers', 1, 'If tonight turned into something, what is your guess at how it starts?', 'Si esta noche se convirtiera en algo, ¿cómo adivinas que empieza?'),
('strangers', 1, 'Based on first impressions, do you think I fall fast or slow?', 'Por la primera impresión, ¿crees que me enamoro rápido o lento?'),
('strangers', 1, 'What is one thing you still want to do before summer ends?', '¿Qué es lo único que todavía quieres hacer antes de que termine el verano?'),
-- Layer 2: personal, warm, getting to know
('strangers', 2, 'What did this summer give you that you were not expecting?', '¿Qué te dio este verano que no esperabas?'),
('strangers', 2, 'What is something about you that people usually take a while to find out?', '¿Qué de ti tarda la gente en descubrir normalmente?'),
('strangers', 2, 'What are you leaving behind when this summer ends?', '¿Qué vas a dejar atrás cuando termine este verano?'),
('strangers', 2, 'What is a way you are different now than you were in June?', '¿En qué eres diferente ahora de quien eras en junio?'),
('strangers', 2, 'What do you want to be true about your life by this time next year?', '¿Qué quieres que sea verdad de tu vida para esta misma época el año que viene?'),
('strangers', 2, 'What is the best decision you made this summer?', '¿Cuál fue la mejor decisión que tomaste este verano?'),
('strangers', 2, 'What do you want more of once things slow down?', '¿De qué quieres más cuando todo baje el ritmo?'),
('strangers', 2, 'What have you been chasing that you are ready to stop chasing?', '¿Qué has estado persiguiendo que ya quieres dejar de perseguir?'),
('strangers', 2, 'What is a risk you took this summer, big or small?', '¿Qué riesgo tomaste este verano, grande o pequeño?'),
('strangers', 2, 'When did you feel most alive these past few months?', '¿Cuándo te sentiste más vivo estos últimos meses?'),
('strangers', 2, 'What is something you are proud of that you would never bring up on your own?', '¿De qué estás orgulloso que nunca mencionarías por tu cuenta?'),
('strangers', 2, 'What is something you learned about yourself while alone this summer?', '¿Qué aprendiste de ti mismo en soledad este verano?'),
('strangers', 2, 'What do people misread about you when they first meet you?', '¿Qué malinterpreta la gente de ti cuando te conoce?'),
('strangers', 2, 'What have you wanted to say yes to but keep hesitating on?', '¿A qué has querido decir que sí pero sigues dudando?'),
('strangers', 2, 'What are you hoping fall brings you?', '¿Qué esperas que te traiga el otoño?'),
('strangers', 2, 'What is a connection you made this summer that mattered more than you expected?', '¿Qué conexión hiciste este verano que importó más de lo que esperabas?'),
('strangers', 2, 'What is something you have outgrown in the last few months?', '¿Qué has dejado atrás en los últimos meses?'),
('strangers', 2, 'What is the version of yourself you are trying to be right now?', '¿Qué versión de ti mismo estás intentando ser ahora mismo?'),
('strangers', 2, 'What is a place from this summer you will think about all winter?', '¿Qué lugar de este verano vas a recordar todo el invierno?'),
('strangers', 2, 'What have you not gotten around to that time is running out on?', '¿Qué no has alcanzado a hacer y se te está acabando el tiempo?'),
-- Layer 3: vulnerable, past, fears
('strangers', 3, 'What did this summer teach you about being lonely?', '¿Qué te enseñó este verano sobre la soledad?'),
('strangers', 3, 'Who did you think about all summer that you have not spoken to?', '¿En quién pensaste todo el verano sin hablarle?'),
('strangers', 3, 'What is a fear you have about what happens after this season?', '¿Qué miedo tienes sobre lo que pasa cuando acabe esta temporada?'),
('strangers', 3, 'What were you hoping for this summer that never came?', '¿Qué esperabas de este verano que nunca llegó?'),
('strangers', 3, 'What is a version of yourself you were trying to leave behind this year?', '¿Qué versión de ti intentabas dejar atrás este año?'),
('strangers', 3, 'When did you last feel truly wanted, and what did that feel like?', '¿Cuándo te sentiste realmente deseado por última vez, y cómo se sintió?'),
('strangers', 3, 'What have you been avoiding that you know is waiting for you in the fall?', '¿Qué has estado evitando que sabes que te espera en el otoño?'),
('strangers', 3, 'What is a connection you let go of that you still wonder about?', '¿Qué conexión soltaste sobre la que todavía te preguntas?'),
('strangers', 3, 'What do you do with the feeling that time is moving faster than you are?', '¿Qué haces con la sensación de que el tiempo va más rápido que tú?'),
('strangers', 3, 'What have you been telling yourself so that being alone feels okay?', '¿Qué te has estado diciendo para que estar solo se sienta bien?'),
('strangers', 3, 'What is a summer from your past you have never fully gotten over?', '¿Qué verano de tu pasado nunca superaste del todo?'),
('strangers', 3, 'What is something you want from someone that you have never actually said out loud?', '¿Qué quieres de alguien que nunca has dicho en voz alta?'),
('strangers', 3, 'When did you last let someone see you at your worst?', '¿Cuándo fue la última vez que dejaste que alguien te viera en tu peor momento?'),
('strangers', 3, 'What is a way you keep people at a distance without meaning to?', '¿Cómo mantienes a la gente a distancia sin querer?'),
('strangers', 3, 'What is something you have been afraid to hope for?', '¿Qué has tenido miedo de esperar?'),
('strangers', 3, 'What is a night this summer you wish had gone differently?', '¿Qué noche de este verano deseas que hubiera salido diferente?'),
('strangers', 3, 'What is a part of yourself you are still trying to make peace with?', '¿Con qué parte de ti todavía intentas hacer las paces?'),
('strangers', 3, 'What do you need that you have stopped asking for?', '¿Qué necesitas que ya dejaste de pedir?'),
('strangers', 3, 'What would you say to someone tonight if there were no consequences?', '¿Qué le dirías a alguien esta noche si no hubiera consecuencias?'),
('strangers', 3, 'What is the last thing that made you cry?', '¿Qué fue lo último que te hizo llorar?'),
-- Layer 4: raw, confessional
('strangers', 4, 'What is something from this summer you are not proud of?', '¿Qué de este verano no te enorgullece?'),
('strangers', 4, 'Who did you hurt this summer, even if they never found out?', '¿A quién lastimaste este verano, aunque nunca se enteró?'),
('strangers', 4, 'What is a lie you told yourself all summer to keep going?', '¿Qué mentira te dijiste todo el verano para seguir adelante?'),
('strangers', 4, 'What is something you have never said out loud to anyone, not once?', '¿Qué nunca le has dicho a nadie en voz alta, ni una sola vez?'),
('strangers', 4, 'What is the loneliest you have ever been in a room full of people?', '¿Cuál ha sido tu mayor soledad en una sala llena de gente?'),
('strangers', 4, 'What is a regret from these past three months you cannot shake?', '¿Qué arrepentimiento de estos tres meses no se te quita?'),
('strangers', 4, 'What did you want this summer badly enough that it scared you?', '¿Qué quisiste tanto este verano que te dio miedo?'),
('strangers', 4, 'Who did you settle for this summer while knowing it at the time?', '¿Con quién te conformaste este verano sabiéndolo en ese momento?'),
('strangers', 4, 'What is the ugliest truth about how you handle being left?', '¿Cuál es la verdad más fea sobre cómo manejas que te dejen?'),
('strangers', 4, 'What are you ashamed of that had nothing to do with your choices?', '¿De qué te avergüenzas que no tuvo nada que ver con tus decisiones?'),
('strangers', 4, 'What is a message from this summer you never sent that you still have written somewhere?', '¿Qué mensaje de este verano nunca enviaste y todavía tienes escrito en algún lado?'),
('strangers', 4, 'What is a way you used someone this summer without meaning to?', '¿Cómo usaste a alguien este verano sin querer?'),
('strangers', 4, 'What have you needed to grieve but never let yourself?', '¿Qué has necesitado llorar pero nunca te permitiste?'),
('strangers', 4, 'What is a night from these past months you would take back if you could?', '¿Qué noche de estos últimos meses te llevarías de vuelta si pudieras?'),
('strangers', 4, 'What do you do when nobody is checking on you?', '¿Qué haces cuando nadie está pendiente de ti?'),
('strangers', 4, 'What is a truth about your life right now you would not admit to your friends?', '¿Qué verdad sobre tu vida ahora mismo no admitirías ante tus amigos?'),
('strangers', 4, 'What are you still angry about that you pretend not to be?', '¿Sobre qué sigues molesto aunque finges que no?'),
('strangers', 4, 'When did you last feel invisible to someone who mattered?', '¿Cuándo te sentiste invisible por última vez para alguien que te importaba?'),
('strangers', 4, 'What is the hardest thing you have survived that people would never guess?', '¿Qué es lo más duro que has sobrevivido que la gente jamás adivinaría?'),
('strangers', 4, 'What are you afraid you will still be doing by next summer?', '¿Qué temes seguir haciendo para el próximo verano?'),
-- Layer 5: soul, meaning, becoming
('strangers', 5, 'What do you want this summer to have meant when you look back on it?', '¿Qué quieres que haya significado este verano cuando mires atrás?'),
('strangers', 5, 'What is the truest thing you know about yourself right now?', '¿Cuál es la verdad más cierta que sabes sobre ti ahora mismo?'),
('strangers', 5, 'What are you becoming that nobody around you has noticed yet?', '¿En qué te estás convirtiendo que nadie a tu alrededor ha notado todavía?'),
('strangers', 5, 'What do you think you are here for, even if it sounds ridiculous to say out loud?', '¿Para qué crees que estás aquí, aunque suene ridículo decirlo en voz alta?'),
('strangers', 5, 'What is a belief you hold that you did not get from anyone else?', '¿Qué creencia tuya no heredaste de nadie más?'),
('strangers', 5, 'What would you want a stranger to understand about you in one sentence?', '¿Qué querrías que un desconocido entendiera de ti en una sola frase?'),
('strangers', 5, 'What have you finally made peace with about being human?', '¿Con qué parte de ser humano por fin hiciste las paces?'),
('strangers', 5, 'What does a life well spent look like to you, specifically?', '¿Cómo se ve, en concreto, una vida bien vivida para ti?'),
('strangers', 5, 'What is a question you are living inside of right now without an answer?', '¿En qué pregunta estás viviendo ahora mismo sin tener respuesta?'),
('strangers', 5, 'What have you stopped needing other people to give you?', '¿Qué dejaste de necesitar que otros te dieran?'),
('strangers', 5, 'What do you owe the version of yourself who got you through this year?', '¿Qué le debes a la versión de ti que te trajo hasta aquí este año?'),
('strangers', 5, 'What is something you understand now that nobody could have told you?', '¿Qué entiendes ahora que nadie te podría haber explicado?'),
('strangers', 5, 'What is the kindest thing you have done that nobody ever saw?', '¿Qué es lo más generoso que has hecho sin que nadie lo viera?'),
('strangers', 5, 'What would you tell someone standing where you were at your lowest?', '¿Qué le dirías a alguien parado donde tú estuviste en tu peor momento?'),
('strangers', 5, 'If this season is a chapter, what is it called and what comes next?', 'Si esta temporada fuera un capítulo, ¿cómo se llama y qué viene después?'),
('strangers', 5, 'What is something about your life you would not trade even though it costs you?', '¿Qué de tu vida no cambiarías aunque te cueste?'),
('strangers', 5, 'What are you grateful for in a way that is hard to explain?', '¿Por qué estás agradecido de una forma difícil de explicar?'),
('strangers', 5, 'What part of yourself do you hope you never lose?', '¿Qué parte de ti esperas no perder nunca?'),
('strangers', 5, 'What is a fear you are ready to stop letting run your life before this year is out?', '¿Qué miedo estás listo para dejar de permitir que dirija tu vida antes de que acabe este año?'),
('strangers', 5, 'What do you want to be different about you by the time next summer comes?', '¿Qué quieres que sea distinto en ti para cuando llegue el próximo verano?');
