-- Peelr October 2026 questions: COWORKERS
-- Theme: Fall: cozy, reflective, a little spooky.
INSERT INTO questions (deck, layer, text_en, text_es) VALUES
-- Layer 1: playful, light, team energy
('coworkers', 1, 'Who on this team is most likely to order a pumpkin spice anything the first day it comes back?', '¿Quién de este equipo es más capaz de pedir algo con especias de calabaza el primer día que regresa?'),
('coworkers', 1, 'Who on this team would win an office Halloween costume contest without even trying?', '¿Quién de este equipo ganaría un concurso de disfraces de Halloween en la oficina sin siquiera intentarlo?'),
('coworkers', 1, 'If this team went as a group costume this year, what should it be?', 'Si este equipo se disfrazara en grupo este año, ¿de qué debería ser?'),
('coworkers', 1, 'Who on this team turns into a completely different person during the Q4 crunch?', '¿Quién de este equipo se convierte en otra persona durante la presión del cuarto trimestre?'),
('coworkers', 1, 'Who on this team would be the first to run screaming out of a haunted house?', '¿Quién de este equipo sería la primera persona en salir gritando de una casa embrujada?'),
('coworkers', 1, 'What is your ideal cozy fall weekend, start to finish?', '¿Cómo sería tu fin de semana de otoño ideal, de principio a fin?'),
('coworkers', 1, 'What is the scariest movie you have ever actually finished?', '¿Cuál es la película más aterradora que de verdad has terminado de ver?'),
('coworkers', 1, 'What is the most frightening thing you have ever found in your inbox on a Monday morning?', '¿Qué es lo más espantoso que has encontrado en tu bandeja de entrada un lunes por la mañana?'),
('coworkers', 1, 'What is a fall food or drink you will defend to anyone?', '¿Qué comida o bebida de otoño defenderías ante cualquiera?'),
('coworkers', 1, 'What is a work superstition you secretly follow?', '¿Qué superstición laboral sigues en secreto?'),
('coworkers', 1, 'Looking back at this year, what is a work moment that still makes you laugh?', 'Mirando atrás este año, ¿qué momento del trabajo todavía te hace reír?'),
('coworkers', 1, 'Who on this team always makes a bad day a little better?', '¿Quién de este equipo siempre hace que un mal día sea un poco mejor?'),
('coworkers', 1, 'What part of your workday do you actually look forward to?', '¿Qué parte de tu día de trabajo de verdad esperas con ganas?'),
('coworkers', 1, 'What did you want to be when you grew up, and how close are you?', '¿Qué querías ser de grande, y qué tan cerca estás?'),
('coworkers', 1, 'What was your very first job, and what did it teach you?', '¿Cuál fue tu primer trabajo, y qué te enseñó?'),
('coworkers', 1, 'What is a small win from this month that nobody noticed?', '¿Qué pequeño logro de este mes pasó desapercibido?'),
('coworkers', 1, 'What is a skill you picked up this year that surprised you?', '¿Qué habilidad adquiriste este año que te sorprendió?'),
('coworkers', 1, 'What is one thing this team does that you would never want to change?', '¿Qué hace este equipo que nunca querrías cambiar?'),
('coworkers', 1, 'What makes someone at work earn your complete trust?', '¿Qué hace que alguien del trabajo se gane tu confianza total?'),
('coworkers', 1, 'What is a work habit of someone on this team that everyone should steal?', '¿Qué hábito de trabajo de alguien de este equipo deberíamos copiar todo el mundo?'),
-- Layer 2: personal, warm
('coworkers', 2, 'Who on this team would you want next to you in a haunted house, and why?', '¿A quién de este equipo querrías a tu lado en una casa embrujada, y por qué?'),
('coworkers', 2, 'If this team were a horror movie, what would the title be?', 'Si este equipo fuera una película de terror, ¿cómo se llamaría?'),
('coworkers', 2, 'Who on this team should be in charge of planning the end of year party?', '¿Quién de este equipo debería encargarse de planear la fiesta de fin de año?'),
('coworkers', 2, 'What does your cozy season look like when you are not at work?', '¿Cómo es tu temporada acogedora cuando no estás trabajando?'),
('coworkers', 2, 'What is a fall tradition from your childhood that you still keep?', '¿Qué tradición de otoño de tu infancia todavía mantienes?'),
('coworkers', 2, 'As the year winds down, what is a project from this year you are quietly proud of?', 'Ahora que el año va terminando, ¿qué proyecto de este año te da un orgullo silencioso?'),
('coworkers', 2, 'What is a goal you set in January that you still want to finish before December?', '¿Qué meta que te pusiste en enero todavía quieres cumplir antes de diciembre?'),
('coworkers', 2, 'What helps you get through a busy Q4 without losing yourself?', '¿Qué te ayuda a pasar un cuarto trimestre intenso sin perderte?'),
('coworkers', 2, 'Who on this team taught you something without even realizing it?', '¿Quién de este equipo te enseñó algo sin darse cuenta?'),
('coworkers', 2, 'What is something you do outside of work that would surprise people on this team?', '¿Qué haces fuera del trabajo que sorprendería a la gente de este equipo?'),
('coworkers', 2, 'What is the best piece of career advice you have ever ignored?', '¿Cuál es el mejor consejo profesional que has ignorado?'),
('coworkers', 2, 'What kind of work makes you lose track of time?', '¿Qué tipo de trabajo te hace perder la noción del tiempo?'),
('coworkers', 2, 'What is something you are better at now than when you started here?', '¿En qué has mejorado desde que empezaste aquí?'),
('coworkers', 2, 'What job would you try for one year if money did not matter?', '¿Qué trabajo probarías por un año si el dinero no importara?'),
('coworkers', 2, 'Who on this team do you go to when you need an honest second opinion?', '¿A quién de este equipo acudes cuando necesitas una segunda opinión honesta?'),
('coworkers', 2, 'What makes a team feel like a real team to you?', '¿Qué hace que un equipo se sienta como un equipo de verdad para ti?'),
('coworkers', 2, 'What does a good day at work look like for you?', '¿Cómo se ve un buen día de trabajo para ti?'),
('coworkers', 2, 'What is one thing you would want a new hire to know about this team?', '¿Qué querrías que una persona recién contratada supiera de este equipo?'),
('coworkers', 2, 'What is a quality you admire in someone on this team?', '¿Qué cualidad admiras en alguien de este equipo?'),
('coworkers', 2, 'What is something you changed your mind about at work this year?', '¿Sobre qué cambiaste de opinión en el trabajo este año?'),
-- Layer 3: professional vulnerability, still light
('coworkers', 3, 'What is a part of your job you secretly love that nobody would guess?', '¿Qué parte de tu trabajo te encanta en secreto y nadie se imaginaría?'),
('coworkers', 3, 'What is a professional fear you have that might surprise people here?', '¿Qué miedo profesional tienes que podría sorprender a la gente aquí?'),
('coworkers', 3, 'Looking back, what was the scariest moment of your career so far?', 'Mirando atrás, ¿cuál ha sido el momento más aterrador de tu carrera hasta ahora?'),
('coworkers', 3, 'What is a work risk you were scared to take but are glad you did?', '¿Qué riesgo laboral te dio miedo tomar pero te alegra haber tomado?'),
('coworkers', 3, 'Who on this team has pushed you to grow more than they know?', '¿Quién de este equipo te ha impulsado a crecer más de lo que imagina?'),
('coworkers', 3, 'What is a strength this team has that we do not talk about enough?', '¿Qué fortaleza tiene este equipo de la que no hablamos lo suficiente?'),
('coworkers', 3, 'What is a piece of feedback that stung at first but ended up helping you?', '¿Qué comentario te dolió al principio pero terminó ayudándote?'),
('coworkers', 3, 'What is something you wish you were braver about at work?', '¿En qué te gustaría tener más valentía en el trabajo?'),
('coworkers', 3, 'What part of your job do you think people here misunderstand?', '¿Qué parte de tu trabajo crees que la gente aquí no entiende bien?'),
('coworkers', 3, 'If this team could fix one thing about how we work together, what should it be?', 'Si este equipo pudiera arreglar una cosa de cómo trabajamos juntos, ¿cuál debería ser?'),
('coworkers', 3, 'What does respect look like on this team at its best?', '¿Cómo se ve el respeto en este equipo en su mejor momento?'),
('coworkers', 3, 'Who on this team do you wish you knew better?', '¿A quién de este equipo te gustaría conocer mejor?'),
('coworkers', 3, 'What is a moment on this team that made you feel like you belonged?', '¿Qué momento en este equipo te hizo sentir que pertenecías?'),
('coworkers', 3, 'What is a career path you almost took instead of this one?', '¿Qué camino profesional casi tomaste en lugar de este?'),
('coworkers', 3, 'What kind of recognition actually means something to you?', '¿Qué tipo de reconocimiento de verdad significa algo para ti?'),
('coworkers', 3, 'What is a rule you follow at work that nobody ever told you?', '¿Qué regla sigues en el trabajo que nadie te dijo?'),
('coworkers', 3, 'Who on this team would you trust to give you a brutally honest opinion?', '¿A quién de este equipo le confiarías una opinión brutalmente honesta?'),
('coworkers', 3, 'As this year closes out, what do you want to do differently in your work next year?', 'Ahora que se acerca el cierre del año, ¿qué quieres hacer diferente en tu trabajo el próximo año?'),
('coworkers', 3, 'What does balance between work and life honestly look like for you right now?', '¿Cómo se ve, honestamente, el equilibrio entre trabajo y vida para ti ahora mismo?'),
('coworkers', 3, 'What part of your job drains you, and what part refuels you?', '¿Qué parte de tu trabajo te agota, y qué parte te recarga?'),
-- Layer 4: ambition and unspoken feelings about work
('coworkers', 4, 'What is a career dream you have been too scared to say out loud?', '¿Qué sueño profesional te ha dado miedo decir en voz alta?'),
('coworkers', 4, 'What keeps you up at night about your career, and what would quiet it?', '¿Qué te quita el sueño de tu carrera, y qué lo calmaría?'),
('coworkers', 4, 'What professional risk would you take if you knew you could not fail?', '¿Qué riesgo profesional tomarías si supieras que no puedes fallar?'),
('coworkers', 4, 'Who on this team do you think will go the furthest, and why?', '¿Quién de este equipo crees que llegará más lejos, y por qué?'),
('coworkers', 4, 'What is something this team does that you have never thanked anyone for?', '¿Qué hace este equipo que nunca le has agradecido a nadie?'),
('coworkers', 4, 'What would make you stay at a job even if it paid less?', '¿Qué te haría quedarte en un trabajo aunque pagara menos?'),
('coworkers', 4, 'What do you want to be known for at work?', '¿Por qué cosa quieres que te conozcan en el trabajo?'),
('coworkers', 4, 'When did you feel underestimated at work, and what did you do about it?', '¿Cuándo sentiste que te subestimaron en el trabajo, y qué hiciste al respecto?'),
('coworkers', 4, 'What part of your work fills you with pride even though nobody here has seen it?', '¿Qué parte de tu trabajo te llena de orgullo aunque nadie aquí la haya visto?'),
('coworkers', 4, 'If this team had one shared goal beyond the work itself, what should it be?', 'Si este equipo tuviera una meta compartida más allá del trabajo en sí, ¿cuál debería ser?'),
('coworkers', 4, 'Who on this team has quietly made your job easier?', '¿Quién de este equipo te ha facilitado el trabajo sin hacer ruido?'),
('coworkers', 4, 'What moment from this team do you think we will still be talking about in ten years?', '¿Qué momento de este equipo crees que seguiremos recordando dentro de diez años?'),
('coworkers', 4, 'What is a question you wish someone on this team would ask you?', '¿Qué pregunta te gustaría que alguien de este equipo te hiciera?'),
('coworkers', 4, 'What does success look like to you when no one is watching?', '¿Cómo se ve el éxito para ti cuando nadie está mirando?'),
('coworkers', 4, 'What is a compromise you would never make for a job?', '¿Qué concesión nunca harías por un trabajo?'),
('coworkers', 4, 'What is something you want to get better at before this year is over?', '¿En qué quieres mejorar antes de que termine este año?'),
('coworkers', 4, 'What kind of leader do you hope you never become?', '¿Qué tipo de líder esperas nunca llegar a ser?'),
('coworkers', 4, 'What did a mistake at work teach you that a win never could?', '¿Qué te enseñó un error en el trabajo que un logro nunca podría enseñarte?'),
('coworkers', 4, 'What is one thing you think this team should celebrate more?', '¿Qué crees que este equipo debería celebrar más?'),
('coworkers', 4, 'Who on this team would you want in your corner for the biggest challenge of your career?', '¿A quién de este equipo querrías de tu lado en el mayor reto de tu carrera?'),
-- Layer 5: what work means, who you are becoming
('coworkers', 5, 'Fall is when trees let go of what they no longer need, so what is it time for you to let go of in your career?', 'En otoño los árboles sueltan lo que ya no necesitan, ¿qué te toca soltar a ti en tu carrera?'),
('coworkers', 5, 'What do you want your work to mean to you ten years from now?', '¿Qué quieres que signifique tu trabajo para ti dentro de diez años?'),
('coworkers', 5, 'What has this team taught you about the kind of person you want to be?', '¿Qué te ha enseñado este equipo sobre la clase de persona que quieres ser?'),
('coworkers', 5, 'What do you hope people on this team remember about working with you?', '¿Qué esperas que la gente de este equipo recuerde de trabajar contigo?'),
('coworkers', 5, 'What value do you hope this team never loses?', '¿Qué valor esperas que este equipo nunca pierda?'),
('coworkers', 5, 'What would make you look back on this chapter of your career and call it a good one?', '¿Qué haría que mires atrás a esta etapa de tu carrera y digas que fue buena?'),
('coworkers', 5, 'Is a great career built more on talent or on character?', '¿Una gran carrera se construye más con talento o con carácter?'),
('coworkers', 5, 'What is the most meaningful thing someone from work has ever done for you?', '¿Qué es lo más significativo que alguien del trabajo ha hecho por ti?'),
('coworkers', 5, 'If this team wrote one rule for how we treat each other, what should it say?', 'Si este equipo escribiera una regla sobre cómo tratarnos, ¿qué debería decir?'),
('coworkers', 5, 'When this season of your career is over, what do you hope people say you made better?', 'Cuando termine esta etapa de tu carrera, ¿qué esperas que digan que mejoraste?'),
('coworkers', 5, 'Who on this team do you think has the most untapped potential?', '¿Quién de este equipo crees que tiene más potencial sin descubrir?'),
('coworkers', 5, 'How do you hope to guide someone in their career someday?', '¿Cómo esperas guiar a alguien en su carrera algún día?'),
('coworkers', 5, 'Where do you think this team will be in five years?', '¿Dónde crees que estará este equipo en cinco años?'),
('coworkers', 5, 'What is a lesson from work that changed how you live outside of it?', '¿Qué lección del trabajo cambió tu forma de vivir fuera de él?'),
('coworkers', 5, 'What should people get from their work besides a paycheck?', '¿Qué debería obtener la gente de su trabajo además de un sueldo?'),
('coworkers', 5, 'What part of who you are do you hope never gets lost behind a job title?', '¿Qué parte de quien eres esperas que nunca se pierda detrás de un puesto?'),
('coworkers', 5, 'What would you want this team to say about you at your farewell party?', '¿Qué te gustaría que este equipo dijera de ti en tu fiesta de despedida?'),
('coworkers', 5, 'What is the bravest professional choice you hope to make someday?', '¿Cuál es la decisión profesional más valiente que esperas tomar algún día?'),
('coworkers', 5, 'What makes working on this team feel worth it on the hardest days?', '¿Qué hace que trabajar en este equipo valga la pena en los días más difíciles?'),
('coworkers', 5, 'What do you hope to build in your career that outlasts your time in it?', '¿Qué esperas construir en tu carrera que dure más allá de tu paso por ella?');
