-- Peelr October 2026 questions: FAMILY
-- Theme: Fall: cozy, reflective, a little spooky.
INSERT INTO questions (deck, layer, text_en, text_es) VALUES
-- Layer 1: playful, light, group energy
('family', 1, 'Who in this family would win a leaf pile jumping contest?', '¿Quién de esta familia ganaría un concurso de saltar en montones de hojas?'),
('family', 1, 'What is the one dish that has to be on the table at a fall family dinner?', '¿Cuál es el platillo que no puede faltar en la mesa de una cena familiar de otoño?'),
('family', 1, 'Who here takes cozy season the most seriously?', '¿Quién aquí se toma más en serio la temporada acogedora?'),
('family', 1, 'If this family opened a pumpkin patch, who would run what?', 'Si esta familia abriera un huerto de calabazas, ¿quién se encargaría de qué?'),
('family', 1, 'What is the best thing you ever got while trick-or-treating?', '¿Qué es lo mejor que te dieron alguna vez al pedir dulces en Halloween?'),
('family', 1, 'Who in this family makes the biggest fuss when the first cold morning hits?', '¿Quién de esta familia hace más drama con la primera mañana fría?'),
('family', 1, 'What fall flavor do you think is completely overrated?', '¿Qué sabor de otoño crees que está totalmente sobrevalorado?'),
('family', 1, 'Which family recipe would you rescue first if the kitchen were on fire?', '¿Qué receta familiar rescatarías primero si la cocina se estuviera incendiando?'),
('family', 1, 'Who here would survive the longest in a scary movie, and who would not make it past the opening scene?', '¿Quién aquí sobreviviría más tiempo en una película de miedo, y quién no pasaría de la primera escena?'),
('family', 1, 'What is your ideal lazy fall Sunday from start to finish?', '¿Cómo sería tu domingo de otoño ideal de principio a fin?'),
('family', 1, 'What is a fall memory with this family that you keep coming back to?', '¿Qué recuerdo de otoño con esta familia vuelve a tu mente una y otra vez?'),
('family', 1, 'Who in this family taught you a recipe or kitchen trick you still use?', '¿Quién de esta familia te enseñó una receta o un truco de cocina que todavía usas?'),
('family', 1, 'What is something small that makes you feel at home no matter where you are?', '¿Qué cosa pequeña te hace sentir en casa sin importar dónde estés?'),
('family', 1, 'What is a family gathering you remember better than almost any other, and why that one?', '¿Qué reunión familiar recuerdas mejor que casi cualquier otra, y por qué esa?'),
('family', 1, 'What is it about this time of year that changes your mood?', '¿Qué tiene esta época del año que cambia tu estado de ánimo?'),
('family', 1, 'How has this family changed since last fall?', '¿En qué ha cambiado esta familia desde el otoño pasado?'),
('family', 1, 'What are you hoping to slow down and enjoy more before the year ends?', '¿Qué esperas disfrutar con más calma antes de que termine el año?'),
('family', 1, 'What makes a family dinner feel special, beyond what is on the plate?', '¿Qué hace especial una cena familiar, más allá de lo que hay en el plato?'),
('family', 1, 'Who here is best at making everyone feel included at a big gathering?', '¿Quién aquí sabe mejor hacer que todo el mundo se sienta parte de una gran reunión?'),
('family', 1, 'What are you thankful for this year that you have not said out loud yet?', '¿Por qué cosa sientes gratitud este año que todavía no has dicho en voz alta?'),
-- Layer 2: personal, warm
('family', 2, 'Who in this family would you trust to carve the turkey, and who should never touch the knife?', '¿A quién de esta familia le confiarías cortar el pavo, y quién nunca debería tocar el cuchillo?'),
('family', 2, 'What family recipe do you hope someone teaches you before it is too late?', '¿Qué receta familiar esperas que alguien te enseñe antes de que sea demasiado tarde?'),
('family', 2, 'If this family spent a weekend in a cabin in the woods, who would be the first to hear something outside?', 'Si esta familia pasara un fin de semana en una cabaña en el bosque, ¿quién sería la primera persona en oír algo afuera?'),
('family', 2, 'What story from an old family gathering always comes up when everyone is together?', '¿Qué historia de una vieja reunión familiar siempre sale cuando la familia se reúne?'),
('family', 2, 'What costume did you wear that says a lot about who you were at that age?', '¿Qué disfraz usaste que dice mucho de quien eras a esa edad?'),
('family', 2, 'Who in this family has changed their mind about something big in the last year?', '¿Quién de esta familia ha cambiado de opinión sobre algo importante en el último año?'),
('family', 2, 'What season of your life would you compare to fall, when everything around you was changing?', '¿Qué etapa de tu vida compararías con el otoño, cuando todo cambiaba a tu alrededor?'),
('family', 2, 'What do you feel it is time to let go of, the way the trees let go of their leaves?', '¿Qué sientes que ya es hora de soltar, como los árboles sueltan sus hojas?'),
('family', 2, 'When was the last time you felt really cared for by someone in this room?', '¿Cuándo fue la última vez que sentiste mucho cariño de alguien en este cuarto?'),
('family', 2, 'What do you wish you had asked a grandparent while you had the chance?', '¿Qué desearías haberle preguntado a un abuelo o abuela cuando tuviste la oportunidad?'),
('family', 2, 'What part of your everyday life does nobody in this family really know about?', '¿Qué parte de tu vida diaria nadie de esta familia conoce de verdad?'),
('family', 2, 'What have you been carrying this year that has been heavier than you let on?', '¿Qué has cargado este año que te ha pesado más de lo que has dejado ver?'),
('family', 2, 'Who here can you be completely yourself around, and why?', '¿Con quién de aquí puedes ser tú de verdad, y por qué?'),
('family', 2, 'What is a change in your life this year you are quietly proud of?', '¿Qué cambio de este año en tu vida te da un orgullo silencioso?'),
('family', 2, 'What is a family moment you did not appreciate until much later?', '¿Qué momento familiar no valoraste hasta mucho después?'),
('family', 2, 'What does it really mean to show up for family?', '¿Qué significa de verdad estar presente para la familia?'),
('family', 2, 'What is something this family does well that you want to protect?', '¿Qué hace bien esta familia que quieres proteger?'),
('family', 2, 'Why do you think gathering around food matters so much to people?', '¿Por qué crees que reunirse alrededor de la comida importa tanto?'),
('family', 2, 'What does gratitude look like when nobody is watching?', '¿Cómo se ve la gratitud cuando nadie está mirando?'),
('family', 2, 'If this family could add one new value to how we live, what would it be?', 'Si esta familia pudiera sumar un valor nuevo a su forma de vivir, ¿cuál sería?'),
-- Layer 3: vulnerable, past and fears
('family', 3, 'Who in this family do you think understands you least, and what would you want them to get?', '¿Quién de esta familia crees que te entiende menos, y qué te gustaría que comprendiera?'),
('family', 3, 'What are you curious about from the lives your parents had before you?', '¿Qué te da curiosidad de la vida que tenían tus padres antes de ti?'),
('family', 3, 'Who here would you call first in a real emergency, and do they know that?', '¿A quién de aquí llamarías primero en una emergencia real, y esa persona lo sabe?'),
('family', 3, 'What is a loss this family went through that you never really got to talk about?', '¿Qué pérdida vivió esta familia de la que nunca pudiste hablar de verdad?'),
('family', 3, 'What is a fear about the future you have not shared with anyone here?', '¿Qué miedo sobre el futuro no has compartido con nadie aquí?'),
('family', 3, 'When have you felt like the outsider in this family?', '¿Cuándo te has sentido fuera de lugar en esta familia?'),
('family', 3, 'What holiday was harder for you than anyone realized?', '¿Qué día festivo fue más difícil para ti de lo que nadie notó?'),
('family', 3, 'What past version of yourself have you had to forgive?', '¿Qué versión de ti del pasado has tenido que perdonar?'),
('family', 3, 'What did you learn about conflict from watching this family?', '¿Qué aprendiste sobre los conflictos viendo a esta familia?'),
('family', 3, 'When did someone here surprise you by showing up right when you needed it?', '¿En qué momento alguien de aquí te sorprendió apareciendo justo cuando más lo necesitabas?'),
('family', 3, 'What is a dream you gave up on that you still think about sometimes?', '¿Qué sueño abandonaste en el que todavía piensas a veces?'),
('family', 3, 'What hard thing you went through growing up shaped you more than people know?', '¿Qué cosa difícil viviste al crecer que te marcó más de lo que la gente sabe?'),
('family', 3, 'When do you feel the most pressure in this family?', '¿Cuándo sientes más presión dentro de esta familia?'),
('family', 3, 'How should this family take care of each other as the years go by?', '¿Cómo debería cuidarse esta familia a medida que pasan los años?'),
('family', 3, 'What is the difference between being family and actually being close?', '¿Cuál es la diferencia entre ser familia y tener de verdad una relación cercana?'),
('family', 3, 'What does it mean to you to be there for someone without trying to fix anything?', '¿Qué significa para ti acompañar a alguien sin intentar arreglar nada?'),
('family', 3, 'What should this family talk about more openly?', '¿De qué debería hablar esta familia con más apertura?'),
('family', 3, 'What family tradition is worth keeping even when it gets hard to pull off?', '¿Qué tradición familiar vale la pena mantener aunque cueste sacarla adelante?'),
('family', 3, 'What do you think every person in this family deserves to hear more often?', '¿Qué crees que cada persona de esta familia merece escuchar más seguido?'),
('family', 3, 'What have you learned about patience from someone here?', '¿Qué has aprendido sobre la paciencia de alguien de aquí?'),
-- Layer 4: raw, confessions and regrets
('family', 4, 'What secret did you keep from this family for years that you can laugh about now?', '¿Qué secreto le guardaste a esta familia durante años del que ahora puedes reírte?'),
('family', 4, 'Who here do you think has been hiding how they really feel about something?', '¿Quién aquí crees que ha estado escondiendo lo que de verdad siente sobre algo?'),
('family', 4, 'What do you wish you had done differently when someone in this family needed you?', '¿Qué desearías haber hecho distinto cuando alguien de esta familia te necesitó?'),
('family', 4, 'What goodbye did you never get to say properly?', '¿Qué despedida nunca pudiste hacer como se debía?'),
('family', 4, 'What resentment have you been holding onto that you are ready to set down?', '¿Qué resentimiento has guardado que ya quieres dejar ir?'),
('family', 4, 'What is the hardest thing you have ever had to hide from this family?', '¿Qué es lo más difícil que has tenido que ocultarle a esta familia?'),
('family', 4, 'When did you feel like you let this family down?', '¿Cuándo sentiste que le fallaste a esta familia?'),
('family', 4, 'What part of your story are you afraid this family would judge?', '¿Qué parte de tu historia temes que esta familia juzgue?'),
('family', 4, 'What promise did you make to someone here that you did not keep?', '¿Qué promesa le hiciste a alguien aquí que no cumpliste?'),
('family', 4, 'What was the loneliest stretch of your life, and did anyone here notice?', '¿Cuál ha sido la etapa de más soledad que has vivido, y alguien aquí lo notó?'),
('family', 4, 'What loss are you still grieving even though nobody talks about it anymore?', '¿Por qué pérdida sigues en duelo aunque ya nadie hable de ella?'),
('family', 4, 'What does it take for you to truly trust someone again after they hurt you?', '¿Qué necesitas para volver a confiar de verdad en alguien que te lastimó?'),
('family', 4, 'What family wound do you think we could still heal together?', '¿Qué herida familiar crees que todavía podríamos sanar en familia?'),
('family', 4, 'Is it ever okay to keep a secret from family, and when?', '¿Alguna vez está bien guardarle un secreto a la familia, y cuándo?'),
('family', 4, 'What is the bravest thing a person can say to their family?', '¿Qué es lo más valiente que una persona le puede decir a su familia?'),
('family', 4, 'What should this family stop pretending is fine?', '¿Qué debería dejar de fingir esta familia que está bien?'),
('family', 4, 'Where is the line between being honest and hurting someone here?', '¿Dónde está la línea entre la honestidad y lastimar a alguien de aquí?'),
('family', 4, 'What would it look like for this family to fight fair?', '¿Cómo se vería que esta familia discutiera de forma justa?'),
('family', 4, 'What do you need from this family right now that you are finally willing to ask for?', '¿Qué necesitas ahora de esta familia que por fin te animas a pedir?'),
('family', 4, 'Who here do you think deserves an apology from all of us?', '¿Quién aquí crees que merece una disculpa de parte de toda la familia?'),
-- Layer 5: soul, meaning and legacy
('family', 5, 'If you could sit down with this family exactly ten years from now, what do you hope we would be talking about?', 'Si pudieras sentarte con esta familia dentro de diez años exactos, ¿de qué esperas que estuviéramos hablando?'),
('family', 5, 'What season of life do you feel you are in right now, and what is it teaching you?', '¿En qué estación de la vida sientes que estás ahora, y qué te está enseñando?'),
('family', 5, 'What did this family give you that you are still unwrapping?', '¿Qué te dio esta familia que todavía sigues descubriendo?'),
('family', 5, 'When you picture your happiest self, who from this room is there with you?', 'Cuando imaginas tu versión más feliz, ¿quién de este cuarto te acompaña?'),
('family', 5, 'What part of growing older are you making peace with?', '¿Con qué parte de envejecer estás haciendo las paces?'),
('family', 5, 'What is the most important thing you have learned from watching the oldest person in this family?', '¿Qué es lo más importante que has aprendido observando a la persona de más edad de esta familia?'),
('family', 5, 'What do you think you were meant to bring to this family?', '¿Qué crees que viniste a aportar a esta familia?'),
('family', 5, 'Looking back, what part of your life are you most grateful for?', 'Al mirar atrás, ¿por qué parte de tu vida sientes más gratitud?'),
('family', 5, 'What quiet moment with someone here meant more than they know?', '¿Qué momento tranquilo con alguien de aquí significó más de lo que esa persona imagina?'),
('family', 5, 'What do you want the next generation of this family to understand about where they come from?', '¿Qué quieres que la próxima generación de esta familia entienda sobre sus raíces?'),
('family', 5, 'What makes a home still feel like home after the people in it change?', '¿Qué hace que un hogar siga sintiéndose como hogar cuando la gente en él cambia?'),
('family', 5, 'What does it mean to leave the people you love better than you found them?', '¿Qué significa dejar a las personas que amas mejor de como las encontraste?'),
('family', 5, 'What is worth harvesting from this past year before it ends?', '¿Qué vale la pena cosechar de este último año antes de que termine?'),
('family', 5, 'What do you believe is the real point of a family?', '¿Cuál crees que es el verdadero propósito de una familia?'),
('family', 5, 'What do you hope people feel at this family table long after we are gone?', '¿Qué esperas que sienta la gente en la mesa de esta familia mucho después de que ya no estemos?'),
('family', 5, 'How do you want to be cared for when you are very old?', '¿Cómo quieres que te cuiden cuando tengas muchos años?'),
('family', 5, 'What does a good life look like to you now, compared to when you were younger?', '¿Cómo se ve una buena vida para ti ahora, comparada con cuando tenías menos edad?'),
('family', 5, 'What should every person in this family know they can always count on?', '¿Con qué debería saber cada persona de esta familia que siempre puede contar?'),
('family', 5, 'If this family kept a recipe book that held more than recipes, what would you want written on the first page?', 'Si esta familia tuviera un libro de recetas que guardara más que recetas, ¿qué querrías escrito en la primera página?'),
('family', 5, 'What is the one thing you hope this family never forgets about you?', '¿Qué es lo único que esperas que esta familia nunca olvide de ti?');
