-- Peelr October 2026 questions: FRIENDS
-- Theme: Fall: cozy, reflective, a little spooky.
INSERT INTO questions (deck, layer, text_en, text_es) VALUES
-- Layer 1: playful, light, group energy
('friends', 1, 'Who in this group would be first in line for anything pumpkin spice?', '¿Quién de este grupo sería la primera persona en la fila para cualquier cosa con sabor a calabaza especiada?'),
('friends', 1, 'What is your ideal cozy fall night, from start to finish?', '¿Cómo sería tu noche de otoño acogedora ideal, de principio a fin?'),
('friends', 1, 'Who here would carve the best pumpkin, and who would just eat the seeds?', '¿Quién aquí tallaría la mejor calabaza, y quién nada más se comería las semillas?'),
('friends', 1, 'What is a fall smell that instantly puts you in a better mood?', '¿Qué olor de otoño te mejora el ánimo al instante?'),
('friends', 1, 'If this group threw a fall bonfire, what job would each of us end up with?', 'Si este grupo hiciera una fogata de otoño, ¿qué tarea terminaría haciendo cada quien?'),
('friends', 1, 'What Halloween costume from your past deserves a comeback?', '¿Qué disfraz de Halloween de tu pasado merece volver?'),
('friends', 1, 'Who in this group would scream the loudest in a corn maze at night?', '¿Quién de este grupo gritaría más fuerte en un laberinto de maíz de noche?'),
('friends', 1, 'What is the coziest piece of clothing you own, and what is the story behind it?', '¿Cuál es la prenda más acogedora que tienes, y cuál es su historia?'),
('friends', 1, 'What scary movie would you happily watch every October forever?', '¿Qué película de terror verías con gusto cada octubre para siempre?'),
('friends', 1, 'Who in this group would go apple picking and come home with way too many apples?', '¿Quién de este grupo iría a recoger manzanas y volvería con demasiadas?'),
('friends', 1, 'What is a fall tradition you would start with this group if you could?', '¿Qué tradición de otoño empezarías con este grupo si pudieras?'),
('friends', 1, 'Which season matches your personality best, and why?', '¿Qué estación del año se parece más a tu personalidad, y por qué?'),
('friends', 1, 'What is a superstition you follow even though you know it makes no sense?', '¿Qué superstición sigues aunque sabes que no tiene sentido?'),
('friends', 1, 'Who here gives off the strongest autumn energy?', '¿Quién aquí transmite más energía de otoño?'),
('friends', 1, 'What is something you look forward to every year without fail?', '¿Qué esperas con ganas cada año sin falta?'),
('friends', 1, 'What is a season of your life you would happily live again?', '¿Qué etapa de tu vida volverías a vivir con gusto?'),
('friends', 1, 'What is something you feel like letting go of, the way trees drop their leaves?', '¿Qué tienes ganas de dejar ir, como los árboles sueltan sus hojas?'),
('friends', 1, 'What makes you feel at home in this group?', '¿Qué te hace sentir en casa en este grupo?'),
('friends', 1, 'What do you think is the most underrated quality in a friend?', '¿Cuál crees que es la cualidad más subestimada en una amistad?'),
('friends', 1, 'What is something you are grateful for this year that you did not see coming?', '¿Qué agradeces este año que no veías venir?'),
-- Layer 2: personal, warm
('friends', 2, 'What fall memory from growing up do you think about every year?', '¿Qué recuerdo de otoño de tu infancia te viene a la mente cada año?'),
('friends', 2, 'Who in this group would you trust to tell the scariest story around a bonfire?', '¿A quién de este grupo le confiarías la historia más aterradora alrededor de una fogata?'),
('friends', 2, 'What is a fear you had growing up that you have totally outgrown?', '¿Qué miedo tenías en tu infancia que ya superaste por completo?'),
('friends', 2, 'What is the best thing about this time of year that most people overlook?', '¿Qué es lo mejor de esta época del año que la mayoría pasa por alto?'),
('friends', 2, 'What does a perfect slow Sunday look like for you right now?', '¿Cómo es un domingo tranquilo perfecto para ti ahora mismo?'),
('friends', 2, 'Who here is most like a warm drink on a cold day?', '¿Quién aquí es como una bebida caliente en un día frío?'),
('friends', 2, 'What has this year given you so far, good or bad?', '¿Qué te ha dejado este año hasta ahora, bueno o malo?'),
('friends', 2, 'What is a side of you that only shows up once you are comfortable with people?', '¿Qué lado tuyo aparece únicamente cuando ya estás en confianza con la gente?'),
('friends', 2, 'What is something this group does that you would miss if it stopped?', '¿Qué hace este grupo que extrañarías si dejara de hacerlo?'),
('friends', 2, 'What is a change you made this year that you feel good about?', '¿Qué cambio hiciste este año que te deja satisfacción?'),
('friends', 2, 'Who in this group has a side most people never get to see?', '¿Quién de este grupo tiene un lado que la mayoría nunca llega a ver?'),
('friends', 2, 'What is the creepiest place you have ever been?', '¿Cuál es el lugar más inquietante en el que has estado?'),
('friends', 2, 'When the days get shorter, what do you find yourself thinking about more?', 'Cuando los días se acortan, ¿en qué te descubres pensando más?'),
('friends', 2, 'What is a comfort you return to when life gets heavy?', '¿A qué consuelo regresas cuando la vida se pone pesada?'),
('friends', 2, 'What would you love for this group to do together before the year ends?', '¿Qué te encantaría que este grupo hiciera antes de que termine el año?'),
('friends', 2, 'Who here has given you advice you actually used?', '¿Quién aquí te ha dado un consejo que de verdad usaste?'),
('friends', 2, 'What is a quality you admire in someone here that you wish you had more of?', '¿Qué cualidad admiras en alguien de aquí que te gustaría tener más?'),
('friends', 2, 'What do you think friends owe each other?', '¿Qué crees que se deben las amistades entre sí?'),
('friends', 2, 'What is something you changed your mind about in the last year?', '¿Sobre qué cambiaste de opinión en el último año?'),
('friends', 2, 'What matters more when you cannot have both, honesty or kindness?', '¿Qué importa más cuando no puedes tener ambas, la honestidad o la amabilidad?'),
-- Layer 3: vulnerable, real
('friends', 3, 'What are you carrying into this season that you wish you could put down?', '¿Qué cargas en esta temporada que desearías poder soltar?'),
('friends', 3, 'What is a change you resisted that turned out to be good for you?', '¿Qué cambio resististe que al final te hizo bien?'),
('friends', 3, 'Who in this group knew a version of you that you have since left behind?', '¿Quién de este grupo conoció una versión de ti que ya dejaste atrás?'),
('friends', 3, 'What scares you more, staying the same or changing completely?', '¿Qué te da más miedo, seguir igual o cambiar por completo?'),
('friends', 3, 'What have you been quietly struggling with that this group might not know about?', '¿Con qué has estado luchando en silencio que este grupo quizás no sabe?'),
('friends', 3, 'When do you feel lonely, even around people you love?', '¿Cuándo sientes soledad, incluso con gente que quieres?'),
('friends', 3, 'What did you need from a friend at some point that you never got?', '¿Qué necesitaste de una amistad en algún momento que nunca recibiste?'),
('friends', 3, 'Who in this group has shown up for you in a way you never thanked them for?', '¿Quién de este grupo ha estado para ti de una forma que nunca le agradeciste?'),
('friends', 3, 'What is an ending in your life that made room for something better?', '¿Qué final en tu vida abrió espacio para algo mejor?'),
('friends', 3, 'What part of your past still follows you around like a ghost?', '¿Qué parte de tu pasado todavía te sigue como un fantasma?'),
('friends', 3, 'How do you act when you are hurt, and how do you wish you acted?', '¿Cómo actúas cuando algo te duele, y cómo desearías actuar?'),
('friends', 3, 'What do you expect from friends that you sometimes fail to give yourself?', '¿Qué esperas de tus amistades que a veces tú no das?'),
('friends', 3, 'If this group had one rule everyone had to live by, what should it be?', 'Si este grupo tuviera una regla que todo el mundo tuviera que seguir, ¿cuál debería ser?'),
('friends', 3, 'In your experience, what does forgiveness actually require?', 'Según tu experiencia, ¿qué requiere realmente el perdón?'),
('friends', 3, 'What do you believe now that would surprise a younger you?', '¿Qué crees ahora que sorprendería a tu yo del pasado?'),
('friends', 3, 'What kind of support from this group feels best when things fall apart?', '¿Qué tipo de apoyo de este grupo te hace mejor cuando todo se derrumba?'),
('friends', 3, 'Who here do you feel you can be the most honest with, and why?', '¿Con quién de aquí sientes que puedes tener más honestidad, y por qué?'),
('friends', 3, 'What do you think nobody should ever have to earn?', '¿Qué crees que nadie debería tener que ganarse?'),
('friends', 3, 'Where is the line for you between being private and being closed off?', '¿Dónde está para ti el límite entre la privacidad y cerrarte por completo?'),
('friends', 3, 'What is a value you inherited that you have decided to keep?', '¿Qué valor heredaste que has decidido conservar?'),
-- Layer 4: raw, confessional
('friends', 4, 'What was the hardest season of your life that most people here never saw?', '¿Cuál fue la etapa más difícil de tu vida que la mayoría aquí nunca vio?'),
('friends', 4, 'What is something you have done that you still cannot fully explain to yourself?', '¿Qué has hecho que todavía no logras explicarte del todo?'),
('friends', 4, 'Who in this group did you misjudge at first, and what changed your mind?', '¿A quién de este grupo juzgaste mal al principio, y qué te hizo cambiar de opinión?'),
('friends', 4, 'What is a mistake you made in a friendship that you would undo if you could?', '¿Qué error cometiste en una amistad que desharías si pudieras?'),
('friends', 4, 'What part of yourself are you most afraid people will see?', '¿Qué parte de ti te da más miedo que la gente vea?'),
('friends', 4, 'When did you last cry, and what was it really about?', '¿Cuándo lloraste por última vez, y de qué se trataba realmente?'),
('friends', 4, 'What do you need to hear from this group but would never ask for?', '¿Qué necesitas escuchar de este grupo que nunca pedirías?'),
('friends', 4, 'What is a loss you have not fully grieved yet?', '¿Qué pérdida todavía no has terminado de llorar?'),
('friends', 4, 'What is a quiet resentment you have been holding onto?', '¿Qué resentimiento silencioso has estado guardando?'),
('friends', 4, 'What would you tell the person you were five years ago, if they would actually listen?', '¿Qué le dirías a la persona que eras hace cinco años, si de verdad te escuchara?'),
('friends', 4, 'Is there anyone in this group you feel you have drifted from, and why?', '¿Hay alguien en este grupo de quien sientes que te has alejado, y por qué?'),
('friends', 4, 'What is a promise you broke that still bothers you?', '¿Qué promesa rompiste que todavía te molesta?'),
('friends', 4, 'What would you stop doing tomorrow if you stopped worrying what people think?', '¿Qué dejarías de hacer mañana si dejaras de preocuparte por lo que piensa la gente?'),
('friends', 4, 'What is worth losing a friendship over?', '¿Por qué cosa valdría la pena perder una amistad?'),
('friends', 4, 'What does it look like when you are not okay, and how can we tell?', '¿Cómo te ves cuando no estás bien, y cómo podemos darnos cuenta?'),
('friends', 4, 'What do you believe about loyalty that you learned the painful way?', '¿Qué crees sobre la lealtad que aprendiste de la forma más dolorosa?'),
('friends', 4, 'When is honesty not worth the damage it does?', '¿Cuándo no vale la pena la honestidad por el daño que causa?'),
('friends', 4, 'What do you think you deserve that you have been afraid to ask for?', '¿Qué crees merecer que te ha dado miedo pedir?'),
('friends', 4, 'What would you want this group to defend about you if you were not around?', '¿Qué querrías que este grupo defendiera de ti si no estuvieras presente?'),
('friends', 4, 'What would it take for you to fully trust someone again after they hurt you?', '¿Qué haría falta para que volvieras a confiar plenamente en alguien que te lastimó?'),
-- Layer 5: soul, meaning, becoming
('friends', 5, 'What do you want your life to look like when you reach the autumn of it?', '¿Cómo quieres que sea tu vida cuando llegues a su otoño?'),
('friends', 5, 'What are you slowly becoming that excites you?', '¿En qué te estás convirtiendo poco a poco que te emociona?'),
('friends', 5, 'What do you think this group will mean to you in twenty years?', '¿Qué crees que significará este grupo para ti en veinte años?'),
('friends', 5, 'What is a truth about life you only accepted recently?', '¿Qué verdad de la vida aceptaste hace poco?'),
('friends', 5, 'What would you want the people closest to you to remember you for?', '¿Por qué te gustaría que te recordaran las personas más cercanas a ti?'),
('friends', 5, 'What do you think you owe the people who raised you, if anything?', '¿Qué crees que le debes a quienes te criaron, si es que algo?'),
('friends', 5, 'What is a quiet way you hope to make the world better?', '¿De qué forma silenciosa esperas mejorar el mundo?'),
('friends', 5, 'What is the bravest thing a friend can do for another friend?', '¿Qué es lo más valiente que una amistad puede hacer por otra?'),
('friends', 5, 'If you could plant something now that you would only harvest years from now, what would it be?', 'Si pudieras sembrar algo hoy para cosecharlo dentro de años, ¿qué sería?'),
('friends', 5, 'What has this group taught you about who you want to be?', '¿Qué te ha enseñado este grupo sobre quién quieres ser?'),
('friends', 5, 'What does a meaningful life require that a successful one does not?', '¿Qué necesita una vida con sentido que una vida exitosa no?'),
('friends', 5, 'What would you regret not saying to the people here?', '¿Qué lamentarías no haberles dicho a las personas de aquí?'),
('friends', 5, 'What are you learning to let go of so you can grow?', '¿Qué estás aprendiendo a soltar para poder crecer?'),
('friends', 5, 'Which of your values has been tested the most, and did it hold?', '¿Cuál de tus valores ha sido más puesto a prueba, y se mantuvo?'),
('friends', 5, 'What do you think the people in this room need most from you?', '¿Qué crees que más necesitan de ti las personas de esta sala?'),
('friends', 5, 'What kind of lifelong friendship do you hope to give someone one day?', '¿Qué clase de amistad de toda la vida esperas darle a alguien algún día?'),
('friends', 5, 'What is something you would still choose, even knowing how hard it would be?', '¿Qué volverías a elegir aun sabiendo lo difícil que sería?'),
('friends', 5, 'Honestly, what does peace look like for you?', 'Sinceramente, ¿cómo se ve la paz para ti?'),
('friends', 5, 'What do you hope stays the same about you no matter how much you change?', '¿Qué esperas que nunca cambie de ti, sin importar cuánto cambies?'),
('friends', 5, 'When this season of your life ends, what do you hope it leaves behind?', 'Cuando termine esta etapa de tu vida, ¿qué esperas que deje atrás?');
