-- Peelr October 2026 questions: LOVERS
-- Theme: Fall: cozy, reflective, a little spooky.
INSERT INTO questions (deck, layer, text_en, text_es) VALUES
-- Layer 1: playful, flirty, cozy fall
('lovers', 1, 'What would our perfect cozy night in look like from start to finish?', '¿Cómo sería nuestra noche acogedora perfecta en casa, de principio a fin?'),
('lovers', 1, 'Which of my sweaters have you secretly claimed as yours?', '¿Cuál de mis suéteres ya consideras tuyo en secreto?'),
('lovers', 1, 'If we went apple picking, who would eat more than we actually paid for, you or me?', 'Si fuéramos a recoger manzanas, ¿quién se comería más de lo que pagamos, tú o yo?'),
('lovers', 1, 'What fall drink do you think matches my personality?', '¿Qué bebida de otoño crees que va con mi personalidad?'),
('lovers', 1, 'What is the most romantic thing we could do around a bonfire?', '¿Qué es lo más romántico que podríamos hacer alrededor de una fogata?'),
('lovers', 1, 'Which scary movie should I never be allowed to pick again?', '¿Qué película de miedo nunca deberías dejarme elegir otra vez?'),
('lovers', 1, 'What Halloween costume do you think would make me look irresistible?', '¿Con qué disfraz de Halloween crees que me vería irresistible?'),
('lovers', 1, 'If we rented a cabin for a weekend this fall, what would you pack first?', 'Si rentáramos una cabaña un fin de semana este otoño, ¿qué empacarías primero?'),
('lovers', 1, 'What is your favorite thing about me when the weather turns cold?', '¿Qué es lo que más te gusta de mí cuando hace frío?'),
('lovers', 1, 'What fall scent reminds you of me?', '¿Qué aroma de otoño te recuerda a mí?'),
('lovers', 1, 'What fall memory from before we met do you wish you could have shared with me?', '¿Qué recuerdo de otoño de antes de conocernos desearías haber vivido conmigo?'),
('lovers', 1, 'When did you first notice you were falling for me?', '¿Cuándo notaste por primera vez que te estabas enamorando de mí?'),
('lovers', 1, 'What is something small I did recently that made you feel loved?', '¿Qué cosa pequeña hice hace poco que te hizo sentir que te quiero?'),
('lovers', 1, 'What season of your life before me do you think about most?', '¿En qué etapa de tu vida antes de mí piensas más?'),
('lovers', 1, 'What does a slow morning with me feel like to you?', '¿Cómo se siente para ti una mañana tranquila conmigo?'),
('lovers', 1, 'What fall tradition from your childhood would you love to share with me?', '¿Qué tradición de otoño de tu infancia te encantaría compartir conmigo?'),
('lovers', 1, 'What quality of mine do you appreciate more now than when we first met?', '¿Qué cualidad mía aprecias más ahora que cuando nos conocimos?'),
('lovers', 1, 'What makes you feel truly cared for on a hard day?', '¿Qué te hace sentir que de verdad te cuidan en un día difícil?'),
('lovers', 1, 'What is more romantic to you, a grand gesture or a quiet routine?', '¿Qué te parece más romántico, un gran gesto o una rutina tranquila?'),
('lovers', 1, 'What does making time for each other mean to you when life gets busy?', '¿Qué significa para ti sacar tiempo para esta relación cuando la vida se llena de cosas?'),
-- Layer 2: personal, warm
('lovers', 2, 'What fall tradition do you want us to make our own?', '¿Qué tradición de otoño quieres que hagamos nuestra?'),
('lovers', 2, 'What would you want to talk about on a long drive to see the leaves change?', '¿De qué querrías hablar en un viaje largo en carro para ver cambiar las hojas?'),
('lovers', 2, 'What holiday gathering are you secretly nervous about bringing me to?', '¿A qué reunión de fiestas te da nervios llevarme?'),
('lovers', 2, 'What scary movie actually got to you, and why do you think it did?', '¿Qué película de miedo de verdad te afectó, y por qué crees que fue?'),
('lovers', 2, 'What fall evening from your past do you still think about?', '¿Qué tarde de otoño de tu pasado todavía recuerdas?'),
('lovers', 2, 'What would you want to tell me sitting by a fire with no phones around?', '¿Qué querrías decirme junto a una fogata y sin teléfonos cerca?'),
('lovers', 2, 'Like the trees this season, what are you ready to let go of?', 'Como los árboles con sus hojas en esta temporada, ¿qué quieres dejar ir?'),
('lovers', 2, 'What part of your daily life do you wish I understood better?', '¿Qué parte de tu vida diaria desearías que yo entendiera mejor?'),
('lovers', 2, 'What is one way you have grown since we started dating?', '¿De qué forma has crecido desde que empezamos a salir?'),
('lovers', 2, 'What do you find hardest to ask me for?', '¿Qué es lo que más te cuesta pedirme?'),
('lovers', 2, 'What about how you were raised shows up in how you love me?', '¿Qué de tu crianza se nota en cómo me amas?'),
('lovers', 2, 'When do you feel most appreciated by me?', '¿Cuándo sientes que más te aprecio?'),
('lovers', 2, 'What did you used to hide from past partners that you do not hide from me?', '¿Qué escondías de tus parejas anteriores que ya no me escondes a mí?'),
('lovers', 2, 'What dream had you put away that you have started thinking about again?', '¿Qué sueño habías guardado en el que estás volviendo a pensar?'),
('lovers', 2, 'What moment in our relationship made you trust me more?', '¿Qué momento de nuestra relación te hizo confiar más en mí?'),
('lovers', 2, 'How do you know when you need space, and how can I tell?', '¿Cómo sabes cuándo necesitas espacio, y cómo puedo darme cuenta yo?'),
('lovers', 2, 'What does a fair relationship look like to you day to day?', '¿Cómo se ve para ti una relación justa en el día a día?'),
('lovers', 2, 'What kind of rest do you need that you rarely get?', '¿Qué tipo de descanso necesitas que casi nunca tienes?'),
('lovers', 2, 'What do you believe every couple should do at least once a year?', '¿Qué crees que toda pareja debería hacer al menos una vez al año?'),
('lovers', 2, 'How much of yourself do you think should stay private, even from a partner?', '¿Cuánto de ti crees que debería quedarse en privado, incluso para tu pareja?'),
-- Layer 3: vulnerable
('lovers', 3, 'What season of your life do you rarely talk about?', '¿De qué etapa de tu vida casi nunca hablas?'),
('lovers', 3, 'What loss are you still grieving that I might not fully know about?', '¿Por qué pérdida todavía sientes un duelo que yo quizás no conozco del todo?'),
('lovers', 3, 'What is a way you protect yourself that sometimes keeps me out?', '¿De qué forma te proteges que a veces me deja fuera?'),
('lovers', 3, 'What do you need to hear more often but feel awkward asking for?', '¿Qué necesitas escuchar más seguido pero te da pena pedirlo?'),
('lovers', 3, 'When was the last time you felt lonely even while we were together?', '¿Cuándo fue la última vez que sentiste soledad incluso estando conmigo?'),
('lovers', 3, 'What belief about yourself are you trying to unlearn?', '¿Qué creencia sobre ti estás tratando de desaprender?'),
('lovers', 3, 'What part of your past do you worry still affects us?', '¿Qué parte de tu pasado te preocupa que todavía nos afecte?'),
('lovers', 3, 'What did your parents teach you about love without meaning to?', '¿Qué te enseñaron tus padres sobre el amor sin querer?'),
('lovers', 3, 'When do you feel the most pressure in our relationship?', '¿Cuándo sientes más presión en nuestra relación?'),
('lovers', 3, 'When did you want to reach for me but held back?', '¿En qué momento quisiste buscarme pero te contuviste?'),
('lovers', 3, 'What question have you always wanted to ask me but never have?', '¿Qué pregunta siempre has querido hacerme pero nunca me has hecho?'),
('lovers', 3, 'What do you think I worry about most when I go quiet?', '¿Qué crees que me preocupa más cuando me quedo en silencio?'),
('lovers', 3, 'On these long fall nights, what has been keeping your mind busy lately?', 'En estas noches largas de otoño, ¿qué te ha tenido la mente ocupada últimamente?'),
('lovers', 3, 'What does showing up for someone look like to you when it is inconvenient?', '¿Qué significa para ti estar presente para alguien cuando no es conveniente?'),
('lovers', 3, 'What do you think we should never fight about?', '¿Por qué cosas crees que nunca deberíamos pelear?'),
('lovers', 3, 'What does respect look like in the middle of an argument?', '¿Cómo se ve el respeto en medio de una discusión?'),
('lovers', 3, 'How do you want us to repair things after a bad day between us?', '¿Cómo quieres que arreglemos las cosas después de un mal día entre tú y yo?'),
('lovers', 3, 'What does it mean to you to feel chosen?', '¿Qué significa para ti sentir que te eligen?'),
('lovers', 3, 'What is one value you hope we never compromise on?', '¿Qué valor esperas que nunca sacrifiquemos?'),
('lovers', 3, 'What does trust require of you that is not always easy?', '¿Qué te exige la confianza que no siempre es fácil?'),
-- Layer 4: raw, confessional
('lovers', 4, 'What fear about us have you been carrying without telling me?', '¿Qué miedo sobre nuestra relación has cargado sin contármelo?'),
('lovers', 4, 'What is the most hurt you have ever felt because of me?', '¿Cuál es el dolor más grande que yo te he causado?'),
('lovers', 4, 'What have you forgiven me for without ever telling me?', '¿Qué me has perdonado sin decírmelo nunca?'),
('lovers', 4, 'What part of you do you still hold back in this relationship?', '¿Qué parte de ti todavía te guardas en esta relación?'),
('lovers', 4, 'When have you doubted us the most?', '¿Cuándo has dudado más de esta relación?'),
('lovers', 4, 'What wound from your past do I sometimes press on without knowing?', '¿Qué herida de tu pasado a veces toco sin saberlo?'),
('lovers', 4, 'What is something you envy about me?', '¿Qué me envidias?'),
('lovers', 4, 'If you could not hurt my feelings, what would you change about us?', 'Si no pudieras herir mis sentimientos, ¿qué cambiarías de esta relación?'),
('lovers', 4, 'Like leaves in the fall, what have you had to let die so we could grow?', 'Como las hojas en otoño, ¿qué has tenido que dejar morir para que esta relación creciera?'),
('lovers', 4, 'What fantasy about our future have you never said out loud?', '¿Qué fantasía sobre nuestro futuro nunca has dicho en voz alta?'),
('lovers', 4, 'What would I be most surprised to learn you think about at night?', '¿Qué me sorprendería más saber que piensas por las noches?'),
('lovers', 4, 'What promise to me are you afraid you might not keep?', '¿Qué promesa que me hiciste temes no poder cumplir?'),
('lovers', 4, 'What does faithfulness mean to you beyond the obvious?', '¿Qué significa para ti la fidelidad, más allá de lo obvio?'),
('lovers', 4, 'Where do you draw the line between privacy and secrecy with me?', '¿Dónde pones el límite entre privacidad y secreto conmigo?'),
('lovers', 4, 'What would you change about yourself for us, and what would you not?', '¿Qué cambiarías de ti por esta relación, y qué no?'),
('lovers', 4, 'In your eyes, when does staying become harder than leaving?', 'A tu parecer, ¿cuándo quedarse se vuelve más difícil que irse?'),
('lovers', 4, 'What does it mean to love someone through a season when they are hard to love?', '¿Qué significa amar a alguien durante una etapa en la que cuesta amarle?'),
('lovers', 4, 'What is the bravest honest thing you could tell me right now?', '¿Qué es lo más valiente y honesto que podrías decirme ahora mismo?'),
('lovers', 4, 'In your view, what do you owe me, and what do I owe you?', 'Según tú, ¿qué me debes, y qué te debo yo?'),
('lovers', 4, 'What could you finally stop doing if you felt fully accepted by me?', '¿Qué podrías dejar de hacer por fin si sintieras que te acepto por completo?'),
-- Layer 5: soul, meaning, legacy
('lovers', 5, 'What do you picture on an ordinary fall afternoon with me thirty years from now?', '¿Qué imaginas en una tarde cualquiera de otoño conmigo dentro de treinta años?'),
('lovers', 5, 'What would our younger selves say if they could see us now?', '¿Qué dirían nuestras versiones más jóvenes si pudieran vernos ahora?'),
('lovers', 5, 'What has loving me cost you, and what has it given you?', '¿Qué te ha costado amarme, y qué te ha dado?'),
('lovers', 5, 'What part of yourself did you rediscover because of us?', '¿Qué parte de ti redescubriste gracias a esta relación?'),
('lovers', 5, 'What is the most important thing you have learned about love from me?', '¿Qué es lo más importante que has aprendido sobre el amor gracias a mí?'),
('lovers', 5, 'Which version of yourself are you most at peace with now?', '¿Con qué versión de ti tienes más paz ahora?'),
('lovers', 5, 'What do you hope I carry with me if we ever have to be apart?', '¿Qué esperas que yo lleve conmigo si alguna vez nos toca estar lejos?'),
('lovers', 5, 'When have you felt our love was bigger than both of us?', '¿Cuándo has sentido que nuestro amor era más grande que tú y yo?'),
('lovers', 5, 'What do you think you were meant to give me in this life?', '¿Qué crees que te tocaba darme en esta vida?'),
('lovers', 5, 'Fall is about endings that make room, so what in you is ending so something new can begin?', 'El otoño es de finales que abren espacio, así que ¿qué está terminando en ti para que algo nuevo empiece?'),
('lovers', 5, 'What about us do you think will still matter long after we are gone?', '¿Qué de nuestra relación crees que seguirá importando mucho después de que ya no estemos?'),
('lovers', 5, 'What do you most want to feel grateful for at the end of your life?', '¿Por qué quieres sentir más gratitud al final de tu vida?'),
('lovers', 5, 'What does a meaningful life look like to you, and where do I fit in it?', '¿Cómo es para ti una vida con sentido, y dónde encajo yo en ella?'),
('lovers', 5, 'What kind of love do you want to model for the people around us?', '¿Qué tipo de amor quieres mostrarle a la gente que nos rodea?'),
('lovers', 5, 'What would you refuse to trade for anything, even comfort or success?', '¿Qué no cambiarías por nada, ni siquiera por comodidad o éxito?'),
('lovers', 5, 'What does growing old well together mean to you?', '¿Qué significa para ti envejecer bien en pareja?'),
('lovers', 5, 'What is one thing you want us to always choose, even when it is hard?', '¿Qué quieres que siempre elijamos, incluso cuando sea difícil?'),
('lovers', 5, 'What do you believe love asks of us that nothing else does?', '¿Qué crees que nos pide el amor que nada más nos pide?'),
('lovers', 5, 'What would you want our story to teach someone who is afraid to love?', '¿Qué querrías que nuestra historia le enseñara a alguien que tiene miedo de amar?'),
('lovers', 5, 'If you could bless our next season with one thing, what would it be?', 'Si pudieras bendecir nuestra próxima etapa con una sola cosa, ¿cuál sería?');
