-- Peelr October 2026 questions: STRANGERS
-- Theme: Fall: cozy, reflective, a little spooky.
INSERT INTO questions (deck, layer, text_en, text_es) VALUES
-- Layer 1: playful, light, group energy
('strangers', 1, 'What is your most controversial fall opinion?', '¿Cuál es tu opinión más polémica sobre el otoño?'),
('strangers', 1, 'Who here is most likely to own more than three flannel shirts?', '¿Quién aquí probablemente tiene más de tres camisas de franela?'),
('strangers', 1, 'Pumpkin spice: personality trait or harmless phase?', 'Calabaza especiada: ¿rasgo de personalidad o fase inofensiva?'),
('strangers', 1, 'Who here would last the longest on a haunted hayride without screaming?', '¿Quién aquí aguantaría más tiempo en un paseo embrujado sin gritar?'),
('strangers', 1, 'What is the coziest place you have ever spent a rainy afternoon?', '¿Cuál es el lugar más acogedor donde has pasado una tarde de lluvia?'),
('strangers', 1, 'What fall food would you defend in front of a room full of haters?', '¿Qué comida de otoño defenderías frente a un salón lleno de gente que la odia?'),
('strangers', 1, 'If this group opened a fall pop-up shop, what would we sell?', 'Si este grupo abriera una tienda temporal de otoño, ¿qué venderíamos?'),
('strangers', 1, 'What is a Halloween costume that said more about you than you meant it to?', '¿Qué disfraz de Halloween dijo más de ti de lo que querías?'),
('strangers', 1, 'Which scary movie do you think everyone here should see at least once?', '¿Qué película de miedo crees que todo el mundo aquí debería ver al menos una vez?'),
('strangers', 1, 'What is a superstition from your family that you still half believe?', '¿Qué superstición de tu familia todavía crees a medias?'),
('strangers', 1, 'Who here gives off the strongest cozy cabin energy?', '¿Quién aquí transmite más energía de cabaña acogedora?'),
('strangers', 1, 'What was fall like where you grew up?', '¿Cómo era el otoño en el lugar donde creciste?'),
('strangers', 1, 'What is a song that only feels right once the weather cools down?', '¿Qué canción solo se siente bien cuando empieza a hacer frío?'),
('strangers', 1, 'What seasonal ritual do you refuse to skip, no matter how busy you get?', '¿Qué ritual de temporada te niegas a saltarte, sin importar cuánto trabajo tengas?'),
('strangers', 1, 'What place from your childhood did you truly believe was haunted?', '¿Qué lugar de tu infancia de verdad creías que estaba embrujado?'),
('strangers', 1, 'What does your ideal lazy Sunday in October look like?', '¿Cómo es tu domingo perezoso ideal en octubre?'),
('strangers', 1, 'What first impression of you tends to change once people know you better?', '¿Qué primera impresión de ti suele cambiar cuando la gente te conoce mejor?'),
('strangers', 1, 'What is something small you are looking forward to before the year ends?', '¿Qué cosa pequeña esperas con ganas antes de que termine el año?'),
('strangers', 1, 'Is it better to be the person who plans the gathering or the one who just shows up?', '¿Es mejor ser quien organiza la reunión o quien simplemente llega?'),
('strangers', 1, 'What makes a stranger start to feel like a friend faster than anything else?', '¿Qué hace que alguien desconocido empiece a sentirse como amistad más rápido que cualquier otra cosa?'),
-- Layer 2: personal, safe, curious
('strangers', 2, 'What is a fall tradition you inherited that you plan to keep?', '¿Qué tradición de otoño heredaste que piensas mantener?'),
('strangers', 2, 'Who here do you think has the best story about a holiday gone wrong?', '¿Quién aquí crees que tiene la mejor historia de una fiesta que salió mal?'),
('strangers', 2, 'What is a meal that tastes like your childhood?', '¿Qué comida te sabe a tu infancia?'),
('strangers', 2, 'Who here seems most likely to have a secret talent, and what is your guess?', '¿Quién aquí parece tener un talento secreto, y cuál adivinas que es?'),
('strangers', 2, 'What is something you always mean to slow down and enjoy but never do?', '¿Qué cosa siempre quieres disfrutar con calma pero nunca lo haces?'),
('strangers', 2, 'Are you someone who loves change or someone who needs time to warm up to it?', '¿Eres una persona que ama el cambio o que necesita tiempo para acostumbrarse a él?'),
('strangers', 2, 'What scared you as a kid that you now understand completely?', '¿Qué te daba miedo en tu infancia que ahora entiendes por completo?'),
('strangers', 2, 'What hobby would you pick up if winter lasted a full year?', '¿Qué pasatiempo empezarías si el invierno durara un año entero?'),
('strangers', 2, 'What does your family argue about every single holiday?', '¿Sobre qué discute tu familia en cada fiesta sin falta?'),
('strangers', 2, 'Who here would be the best company to wait out a snowstorm with in a cabin?', '¿Quién aquí sería la mejor compañía para pasar una tormenta de nieve en una cabaña?'),
('strangers', 2, 'What is a kind of comfort you only discovered as an adult?', '¿Qué forma de consuelo descubriste recién en la adultez?'),
('strangers', 2, 'What is a place you have outgrown but still miss?', '¿Qué lugar ya no es para ti pero todavía extrañas?'),
('strangers', 2, 'What is something you have changed your mind about in the past year?', '¿Sobre qué has cambiado de opinión en el último año?'),
('strangers', 2, 'What do people from your hometown get right that the rest of the world could learn from?', '¿Qué hace bien la gente de tu lugar de origen que el resto del mundo podría aprender?'),
('strangers', 2, 'Who here do you think has moved around the most, and where have they lived?', '¿Quién aquí crees que se ha mudado más veces, y dónde ha vivido?'),
('strangers', 2, 'What part of your daily routine would surprise people?', '¿Qué parte de tu rutina diaria sorprendería a la gente?'),
('strangers', 2, 'What is a season of your life you look back on fondly?', '¿Qué etapa de tu vida recuerdas con cariño?'),
('strangers', 2, 'What is something you think every home should have, besides the basics?', '¿Qué crees que todo hogar debería tener, además de lo básico?'),
('strangers', 2, 'What is an act of generosity from someone else that has stuck with you?', '¿Qué acto de generosidad de otra persona se te ha quedado grabado?'),
('strangers', 2, 'What does being a good guest mean to you?', '¿Qué significa para ti ser una buena visita?'),
-- Layer 3: reflective, what shaped you
('strangers', 3, 'What is something you are letting go of this year, the way trees let go of their leaves?', '¿Qué estás dejando ir este año, como los árboles sueltan sus hojas?'),
('strangers', 3, 'Who here do you think has had to start over more than once?', '¿Quién aquí crees que ha tenido que empezar de cero más de una vez?'),
('strangers', 3, 'What is a moment that changed the direction of your life in a small way?', '¿Qué momento cambió un poco el rumbo de tu vida?'),
('strangers', 3, 'What is a lesson you learned from someone much older than you?', '¿Qué lección aprendiste de alguien con muchos más años que tú?'),
('strangers', 3, 'What role do you end up playing in groups that you never actually chose?', '¿Qué papel terminas cumpliendo en los grupos sin haberlo elegido?'),
('strangers', 3, 'Who here do you think is the best listener, based on tonight alone?', '¿Quién aquí crees que escucha mejor, solo por lo de esta noche?'),
('strangers', 3, 'What part of who you are came from the place you grew up?', '¿Qué parte de quien eres viene del lugar donde creciste?'),
('strangers', 3, 'What do you wish you had known at the start of your twenties?', '¿Qué te hubiera gustado saber al comienzo de tus veinte?'),
('strangers', 3, 'What is a compliment that would genuinely surprise you?', '¿Qué cumplido te sorprendería de verdad?'),
('strangers', 3, 'In what way are you more like your parents than you expected?', '¿En qué aspecto tienes más de tus padres de lo que esperabas?'),
('strangers', 3, 'Who here seems like they keep a lot of their thoughts to themselves?', '¿Quién aquí parece guardarse muchos de sus pensamientos?'),
('strangers', 3, 'What is a decision you made that most people around you did not understand?', '¿Qué decisión tomaste que la mayoría de la gente a tu alrededor no entendió?'),
('strangers', 3, 'What is something you are slowly getting better at?', '¿En qué estás mejorando poco a poco?'),
('strangers', 3, 'What does real rest actually look like for you?', '¿Cómo se ve el descanso de verdad para ti?'),
('strangers', 3, 'What is a rule you live by that you made up yourself?', '¿Qué regla de vida inventaste tú?'),
('strangers', 3, 'Where do you draw the line between honesty and kindness?', '¿Dónde pones el límite entre la honestidad y la amabilidad?'),
('strangers', 3, 'What is something you think is worth being patient for?', '¿Por qué cosa crees que vale la pena tener paciencia?'),
('strangers', 3, 'What is a tradition you think the world should bring back?', '¿Qué tradición crees que el mundo debería recuperar?'),
('strangers', 3, 'What do you think each of us owes our community?', '¿Qué crees que cada persona le debe a su comunidad?'),
('strangers', 3, 'If you could relive one ordinary day from your past, which would you pick?', 'Si pudieras revivir un día común de tu pasado, ¿cuál escogerías?'),
-- Layer 4: honest self-assessment, aspirations
('strangers', 4, 'What is something you are working on about yourself that nobody else would notice?', '¿Qué estás trabajando en ti que nadie más notaría?'),
('strangers', 4, 'What is a goal you quietly gave up on, and are you at peace with it?', '¿Qué meta dejaste ir sin decir nada, y estás en paz con eso?'),
('strangers', 4, 'Where in your life are you playing it too safe?', '¿En qué parte de tu vida estás jugando demasiado a lo seguro?'),
('strangers', 4, 'What is a strength of yours that can also get you into trouble?', '¿Qué fortaleza tuya también te puede meter en problemas?'),
('strangers', 4, 'What do you think you will be glad you did ten years from now?', '¿Qué crees que te alegrará haber hecho dentro de diez años?'),
('strangers', 4, 'Who here do you think would give you the most honest feedback, and would you want it?', '¿Quién aquí crees que te daría la opinión más honesta, y la querrías?'),
('strangers', 4, 'What part of your life looks different from the inside than from the outside?', '¿Qué parte de tu vida se ve diferente desde dentro que desde fuera?'),
('strangers', 4, 'What do you do when you need to feel grounded again?', '¿Qué haces cuando necesitas volver a sentir los pies en la tierra?'),
('strangers', 4, 'What version of success did you used to want that you no longer care about?', '¿Qué versión del éxito querías antes que ya no te importa?'),
('strangers', 4, 'What is a mistake you are glad you made early?', '¿Qué error te alegra haber cometido temprano?'),
('strangers', 4, 'What do you want more of in your life, and what is getting in the way?', '¿Qué quieres más en tu vida, y qué te lo impide?'),
('strangers', 4, 'What is a belief you hold that you have never had to defend out loud?', '¿Qué creencia tienes que nunca has tenido que defender en voz alta?'),
('strangers', 4, 'What kind of person do you think deserves more credit than the world gives them?', '¿Qué tipo de persona crees que merece más reconocimiento del que le da el mundo?'),
('strangers', 4, 'What is a line you would not cross, even if it meant getting ahead?', '¿Qué límite no cruzarías, aunque te ayudara a salir adelante?'),
('strangers', 4, 'What does loyalty mean to you, and where does it end?', '¿Qué significa para ti la lealtad, y dónde termina?'),
('strangers', 4, 'Is it more important to you to be understood or to understand others?', '¿Qué es más importante para ti, que te entiendan o entender a los demás?'),
('strangers', 4, 'What is something you think people should forgive more easily?', '¿Qué crees que la gente debería perdonar con más facilidad?'),
('strangers', 4, 'What is a cause you would happily give your free time to?', '¿A qué causa le darías tu tiempo libre con gusto?'),
('strangers', 4, 'If you could spend a whole autumn learning from one person, who would it be?', 'Si pudieras pasar un otoño entero aprendiendo de una persona, ¿quién sería?'),
('strangers', 4, 'What is a question you wish someone here would ask you tonight?', '¿Qué pregunta te gustaría que alguien de aquí te hiciera esta noche?'),
-- Layer 5: meaning, becoming, beliefs
('strangers', 5, 'What season of life do you feel like you are in right now?', '¿En qué estación de la vida sientes que estás ahora mismo?'),
('strangers', 5, 'What are you becoming that you could not have predicted a few years ago?', '¿En qué te estás convirtiendo que no habrías podido predecir hace unos años?'),
('strangers', 5, 'What do you hope people feel after spending an evening with you?', '¿Qué esperas que la gente sienta después de pasar una noche contigo?'),
('strangers', 5, 'What is a small thing you do that you hope outlasts you?', '¿Qué cosa pequeña haces que esperas que perdure después de ti?'),
('strangers', 5, 'What part of yourself are you still growing into?', '¿Qué parte de ti todavía estás aprendiendo a habitar?'),
('strangers', 5, 'What do you believe now that would have surprised you at fifteen?', '¿Qué crees ahora que te habría sorprendido a los quince años?'),
('strangers', 5, 'What would you want written on the first page of your life story?', '¿Qué te gustaría que dijera la primera página de la historia de tu vida?'),
('strangers', 5, 'What do you think you are here to learn?', '¿Qué crees que viniste a aprender en esta vida?'),
('strangers', 5, 'What does home mean to you now, compared to when you were younger?', '¿Qué significa el hogar para ti ahora, comparado con cuando tenías menos años?'),
('strangers', 5, 'What do you think turns an ordinary life into an extraordinary one?', '¿Qué crees que convierte una vida común en extraordinaria?'),
('strangers', 5, 'What is something you consider sacred, even if it is not religious?', '¿Qué te parece sagrado, aunque no sea religioso?'),
('strangers', 5, 'What is worth holding on to when everything else is changing?', '¿Qué vale la pena conservar cuando todo lo demás está cambiando?'),
('strangers', 5, 'What do you think we owe the people who come after us?', '¿Qué crees que le debemos a quienes vendrán después?'),
('strangers', 5, 'What is the difference between a good life and a full one?', '¿Cuál es la diferencia entre una vida buena y una vida plena?'),
('strangers', 5, 'What do you think gratitude asks of us?', '¿Qué crees que nos pide la gratitud?'),
('strangers', 5, 'When have you felt most like yourself, and what does that say about what matters to you?', '¿Cuándo te has sentido más tú, y qué dice eso de lo que te importa?'),
('strangers', 5, 'What would you want a stranger to take away from your life?', '¿Qué te gustaría que alguien desconocido se llevara de tu vida?'),
('strangers', 5, 'What is one belief about people you hope you never lose?', '¿Qué creencia sobre la gente esperas nunca perder?'),
('strangers', 5, 'What do you think connects everyone in this room right now?', '¿Qué crees que une a todas las personas en este cuarto ahora mismo?'),
('strangers', 5, 'If tonight were a chapter in your life, what would you title it?', 'Si esta noche fuera un capítulo de tu vida, ¿qué título le pondrías?');
